'use client';
import {useEffect,useRef,useState} from 'react';
import type {ClosetSession} from '../supabase';
import type {Trip,TripMoment} from '../travelStore';
import {refreshMomentWeather} from '../travelWeather';

type Props={session:ClosetSession;trip:Trip;moment:TripMoment;onUpdate:(moment:TripMoment)=>void};
function thermalLabel(n?:number|null){if(!n)return'';if(n>=5)return'frio intenso';if(n===4)return'frio';if(n===3)return'camada leve';if(n===2)return'clima ameno';return'clima quente'}
function shouldAutoRefresh(moment:TripMoment){if(!moment.starts_at)return false;const target=new Date(moment.starts_at),days=(target.getTime()-Date.now())/86400000;if(days<-1)return false;const checked=moment.metadata?.weather_checked_at?new Date(moment.metadata.weather_checked_at).getTime():0;if(!checked)return true;const age=Date.now()-checked;const source=String(moment.weather_source||'').toLowerCase();if(days<=16&&source.includes('típico'))return true;return age>12*60*60*1000}
export default function TravelMomentWeather({session,trip,moment,onUpdate}:Props){const [busy,setBusy]=useState(false),[error,setError]=useState(''),autoTried=useRef(false);const has=moment.expected_temp_min!=null||moment.expected_temp_max!=null||moment.rain_probability!=null;async function refresh(silent=false){if(busy)return;setBusy(true);if(!silent)setError('');try{const r=await refreshMomentWeather(session,trip,moment);onUpdate(r.moment)}catch(e:any){if(!silent)setError(e?.message||'Não consegui atualizar o clima.')}finally{setBusy(false)}}useEffect(()=>{if(autoTried.current||!shouldAutoRefresh(moment))return;autoTried.current=true;const timer=setTimeout(()=>refresh(true),250);return()=>clearTimeout(timer)},[moment.id]);const change=moment.metadata?.weather_change;return <div style={{marginTop:10,padding:'11px 12px',border:'1px solid #e4d8ca',borderRadius:15,background:'#f8f2e9'}}>{has?<><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><strong style={{fontSize:12}}>{moment.expected_temp_min!=null&&moment.expected_temp_max!=null?`${Math.round(moment.expected_temp_min)}–${Math.round(moment.expected_temp_max)}°C`:moment.expected_temp_max!=null?`até ${Math.round(moment.expected_temp_max)}°C`:`${Math.round(Number(moment.expected_temp_min))}°C`}</strong>{moment.rain_probability!=null&&<span style={{fontSize:10,color:'#74675c'}}>· chuva {Math.round(moment.rain_probability)}%</span>}{moment.thermal_need&&<span style={{fontSize:10,padding:'4px 7px',borderRadius:999,background:'#eee2d2',color:'#6f5843'}}>{thermalLabel(moment.thermal_need)}</span>}{busy&&<span style={{fontSize:9,color:'#96795b'}}>atualizando…</span>}</div><small style={{display:'block',marginTop:5,color:'#8a7867',lineHeight:1.35}}>{moment.metadata?.weather_note||`Contexto: ${moment.weather_source||'clima'}`}</small>{change?.meaningful&&<div style={{marginTop:8,padding:'8px 9px',borderRadius:11,background:'#f4e0d7',color:'#7b493d',fontSize:10,fontWeight:750}}>⚠ {change.summary||'A previsão mudou desde o planejamento.'} Vale revisar este look.</div>}</>:<small style={{display:'block',color:'#8a7867'}}>{busy?'Buscando o clima deste momento…':'Ainda sem contexto climático para este momento.'}</small>}{error&&<small style={{display:'block',marginTop:6,color:'#984f42'}}>{error}</small>}<button disabled={busy||!moment.starts_at} onClick={()=>refresh(false)} style={{marginTop:8,border:0,background:'transparent',padding:0,color:'#4a382b',fontSize:10,fontWeight:800,textDecoration:'underline'}}>{busy?'Atualizando clima…':has?'Atualizar agora':'Consultar clima deste dia'}</button></div>}
