const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'public, max-age=900, s-maxage=21600',...headers}})
function isoDate(v){const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
function avg(xs){const a=xs.filter(x=>Number.isFinite(x));return a.length?a.reduce((s,x)=>s+x,0)/a.length:null}
function round(v){return Number.isFinite(v)?Math.round(v):null}
async function fetchJson(url){const r=await fetch(url,{headers:{'User-Agent':'ClosetTravel/1.0'}});if(!r.ok)throw new Error(`Weather provider ${r.status}`);return r.json()}
async function geocode(name){const u=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=5&language=pt&format=json`;const d=await fetchJson(u),rows=d?.results||[];if(!rows.length)return null;return rows[0]}
async function forecast(lat,lon,date){const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=temperature_2m_min,temperature_2m_max,precipitation_probability_max,weather_code,wind_speed_10m_max&timezone=auto&forecast_days=16`;const d=await fetchJson(u),i=d?.daily?.time?.indexOf(date)??-1;if(i<0)return null;return{source:'forecast',sourceLabel:'previsão',tempMin:round(d.daily.temperature_2m_min?.[i]),tempMax:round(d.daily.temperature_2m_max?.[i]),rainChance:round(d.daily.precipitation_probability_max?.[i]),weatherCode:d.daily.weather_code?.[i]??null,windMax:round(d.daily.wind_speed_10m_max?.[i])}}
async function historicalExact(lat,lon,date){const u=`https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${date}&end_date=${date}&daily=temperature_2m_min,temperature_2m_max,precipitation_sum,weather_code,wind_speed_10m_max&timezone=auto`;const d=await fetchJson(u);if(!d?.daily?.time?.length)return null;return{source:'historical',sourceLabel:'histórico',tempMin:round(d.daily.temperature_2m_min?.[0]),tempMax:round(d.daily.temperature_2m_max?.[0]),rainChance:(d.daily.precipitation_sum?.[0]||0)>0?60:20,weatherCode:d.daily.weather_code?.[0]??null,windMax:round(d.daily.wind_speed_10m_max?.[0])}}
async function historicalTypical(lat,lon,target){const month=target.slice(5);const year=new Date().getUTCFullYear();const years=[year-1,year-2,year-3,year-4,year-5];const rows=(await Promise.allSettled(years.map(y=>historicalExact(lat,lon,`${y}-${month}`)))).flatMap(x=>x.status==='fulfilled'&&x.value?[x.value]:[]);if(!rows.length)return null;return{source:'historical_typical',sourceLabel:'clima típico',tempMin:round(avg(rows.map(x=>x.tempMin))),tempMax:round(avg(rows.map(x=>x.tempMax))),rainChance:round(avg(rows.map(x=>x.rainChance))),weatherCode:null,windMax:round(avg(rows.map(x=>x.windMax))),sampleYears:rows.length}}
function thermalNeed(ctx){const max=Number(ctx?.tempMax),min=Number(ctx?.tempMin),wind=Number(ctx?.windMax),rain=Number(ctx?.rainChance);let n=2;if(Number.isFinite(max)){if(max<=10)n=5;else if(max<=16)n=4;else if(max<=20)n=3;else if(max>=29)n=1}if(Number.isFinite(min)&&min<=7)n=Math.max(n,5);if(Number.isFinite(wind)&&wind>=30)n=Math.min(5,n+1);if(Number.isFinite(rain)&&rain>=60)n=Math.max(n,3);return n}
export async function onRequestGet({request}){try{const q=new URL(request.url).searchParams,destination=String(q.get('destination')||'').trim(),place=String(q.get('place')||'').trim(),date=isoDate(q.get('date')||'');if(!destination||!date)return json({ok:false,message:'Destino e data são obrigatórios.'},400);const geo=await geocode(destination);if(!geo)return json({ok:false,message:'Não consegui localizar este destino.'},404);const today=new Date();today.setUTCHours(0,0,0,0);const target=new Date(`${date}T00:00:00Z`),days=Math.round((target.getTime()-today.getTime())/86400000);let ctx=null;if(days>=0&&days<=15)ctx=await forecast(geo.latitude,geo.longitude,date);else if(days<0)ctx=await historicalExact(geo.latitude,geo.longitude,date);else ctx=await historicalTypical(geo.latitude,geo.longitude,date);if(!ctx)return json({ok:false,message:'Não encontrei contexto climático para esta data.'},404);return json({ok:true,location:{name:geo.name,admin1:geo.admin1||null,country:geo.country||null,latitude:geo.latitude,longitude:geo.longitude,timezone:geo.timezone||null},place:place||destination,date,...ctx,thermalNeed:thermalNeed(ctx),note:ctx.source==='forecast'?'Previsão disponível para a data planejada.':ctx.source==='historical_typical'?'Ainda não há previsão confiável para esta data; usei o comportamento típico recente deste período.':'Usei o histórico meteorológico da data.'})}catch(e){return json({ok:false,message:e?.message||'Falha ao consultar clima.'},502)}}
