'use client';

import { useEffect, useMemo, useState } from 'react';
import styles from './saved-looks.module.css';
import { loadClosetItems, restoreClosetSession, type ClosetSession } from '../supabase';
import { loadSavedLooks, markLookWorn, rateLook, type SavedLook } from '../savedLooks';
import { learnFromSavedLooks } from '../stylistMemory';

type Piece={id:string;name:string;category:string;image:string;meta:string;status:string};
const filters=['Todos','Igreja','Sair','Trabalho','Faculdade','Evento','Encontro','Festa','Viagem'];
function mapRows(rows:any[]):Piece[]{return rows.map(r=>({id:String(r.id),name:r.name,category:r.category,image:r.image||'',meta:[r.color,r.subcategory,r.pattern,r.style].filter(Boolean).join(' · '),status:r.metadata?.wardrobe_status||'available'}))}

export default function SavedLooksPage(){
 const [session,setSession]=useState<ClosetSession|null>(null),[looks,setLooks]=useState<SavedLook[]>([]),[pieces,setPieces]=useState<Piece[]>([]),[filter,setFilter]=useState('Todos'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[ratingId,setRatingId]=useState('');
 function notify(m:string){setToast(m);window.setTimeout(()=>setToast(''),2200)}
 useEffect(()=>{let alive=true;(async()=>{try{const s=await restoreClosetSession();if(!alive)return;if(!s){setLoading(false);return}setSession(s);const [saved,rows]=await Promise.all([loadSavedLooks(s),loadClosetItems(s)]);if(!alive)return;setLooks(saved);setPieces(mapRows(rows));learnFromSavedLooks(s,saved)}catch(e:any){setError(e?.message||'Não consegui carregar seus looks.')}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const pieceMap=useMemo(()=>new Map(pieces.map(p=>[p.id,p])),[pieces]);
 const visible=useMemo(()=>filter==='Todos'?looks:looks.filter(l=>l.occasion===filter),[looks,filter]);
 function itemsFor(look:SavedLook){return (look.item_ids||[]).map(String).map(id=>pieceMap.get(id)).filter(Boolean) as Piece[]}
 async function worn(look:SavedLook){if(!session)return;const unavailable=itemsFor(look).filter(p=>p.status!=='available');if(unavailable.length){notify(`Este look tem ${unavailable.length} ${unavailable.length===1?'peça indisponível':'peças indisponíveis'}. Adapte antes de marcar como usado.`);return}try{const next=await markLookWorn(session,look);const updated=looks.map(x=>x.id===look.id?next:x);setLooks(updated);learnFromSavedLooks(session,updated);notify('Marcado como usado hoje ✦')}catch(e:any){notify(e?.message||'Não consegui atualizar o look.')}}
 async function feedback(look:SavedLook,rating:'love'|'wear'|'not_me'){if(!session||ratingId)return;setRatingId(look.id);try{const next=await rateLook(session,look.id,rating);const updated=looks.map(x=>x.id===look.id?next:x);setLooks(updated);learnFromSavedLooks(session,updated);notify(rating==='love'?'Amei registrado ♡ Vou aprender com isso.':rating==='wear'?'Funcionou ✦ Vou considerar isso nos próximos looks.':'Entendi. Vou reduzir combinações parecidas.')}catch(e:any){notify(e?.message||'Não consegui registrar seu feedback.')}finally{setRatingId('')}}
 function reopen(look:SavedLook){const unavailable=itemsFor(look).filter(p=>p.status!=='available');window.location.href=unavailable.length?`/closet/look?occasion=${encodeURIComponent(look.occasion)}`:`/closet/look?saved=${encodeURIComponent(look.id)}`}
 if(!session&&!loading)return <main className={styles.page}><section className={styles.empty}><span>MEUS LOOKS</span><h1>Entre no closet.</h1><p>Seus favoritos ficam ligados à sua conta.</p><button onClick={()=>window.location.href='/closet'}>Voltar</button></section></main>;
 return <main className={styles.page}>
  <header className={styles.header}><button onClick={()=>window.location.href='/closet'}>‹</button><div><span>SEU ACERVO</span><strong>Meus looks</strong></div><button onClick={()=>window.location.href='/closet/look'}>＋</button></header>
  <section className={styles.hero}><span>LOOKS SALVOS</span><h1>Combinações que já são suas.</h1><p>Organizadas por ocasião para você repetir, adaptar e ensinar seu stylist.</p><div className={styles.heroActions}><button onClick={()=>window.location.href='/closet/look'}>Montar novo look</button><button onClick={()=>window.location.href='/closet/style'}>Ajustar meu estilo</button></div></section>
  <nav className={styles.filters}>{filters.map(f=><button key={f} className={filter===f?styles.active:''} onClick={()=>setFilter(f)}>{f}</button>)}</nav>
  {loading?<div className={styles.loading}>Carregando seu acervo…</div>:error?<div className={styles.error}><strong>{error}</strong><small>O arquivo de configuração já está no projeto em <b>docs/closet-saved-looks.sql</b>. Depois de executar esse SQL no Supabase, seus favoritos passam a aparecer aqui.</small></div>:!visible.length?<section className={styles.emptyCard}><span>{filter==='Todos'?'AINDA VAZIO':filter.toUpperCase()}</span><h2>{filter==='Todos'?'Seu primeiro favorito começa no provador.':'Nenhum look salvo aqui ainda.'}</h2><button onClick={()=>window.location.href=`/closet/look?occasion=${encodeURIComponent(filter==='Todos'?'Sair':filter)}`}>Montar um look</button></section>:<section className={styles.grid}>{visible.map(saved=>{const items=itemsFor(saved),unavailable=items.filter(p=>p.status!=='available');return <article className={styles.card} key={saved.id}><button className={styles.preview} onClick={()=>reopen(saved)}>{items.slice(0,6).map((p,i)=><img key={p.id} src={p.image} alt={p.name} style={{animationDelay:`${i*45}ms`,opacity:p.status==='available'?1:.45}}/>)}<span>{unavailable.length?`${unavailable.length} indisponível${unavailable.length>1?'is':''}`:saved.occasion}</span></button><div className={styles.meta}><div><small>{saved.occasion.toUpperCase()}</small><strong>{saved.title||`Look para ${saved.occasion}`}</strong><p>{unavailable.length?`${unavailable.length} ${unavailable.length===1?'peça está':'peças estão'} fora de uso no momento`:saved.worn_count?`Usado ${saved.worn_count} ${saved.worn_count===1?'vez':'vezes'}`:'Ainda não marcado como usado'}</p></div><button className={styles.heart}>♥</button></div><div className={styles.actions}><button onClick={()=>reopen(saved)}>{unavailable.length?'Adaptar look':'Vestir novamente'}</button><button disabled={Boolean(unavailable.length)} onClick={()=>worn(saved)}>Usei hoje</button></div><div className={styles.feedback}><span>Como esse look funcionou?</span><div><button disabled={ratingId===saved.id} className={saved.rating==='love'?styles.feedbackActive:''} onClick={()=>feedback(saved,'love')}>♡ Amei</button><button disabled={ratingId===saved.id} className={saved.rating==='wear'?styles.feedbackActive:''} onClick={()=>feedback(saved,'wear')}>✓ Funcionou</button><button disabled={ratingId===saved.id} className={saved.rating==='not_me'?styles.feedbackActive:''} onClick={()=>feedback(saved,'not_me')}>× Não é minha cara</button></div></div></article>})}</section>}
  <div className={`${styles.toast} ${toast?styles.toastShow:''}`}>{toast}</div>
 </main>
}
