'use client'

import { FormEvent, useEffect, useState } from 'react'

type Student={id:string;name:string;whatsapp:string;email?:string;modality:string;address?:string;neighborhood?:string;city?:string;day:string;dayOrder:number;time:string;endTime?:string;durationMinutes?:number;monthlyValue?:string;paymentDay?:string;notes?:string;color?:string;status:'active'|'inactive';createdAt?:string}
const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
const colors=['#7427b9','#236da0','#168c8c','#26784d','#6d7f2b','#aa7220','#b85620','#ad386f','#873044']
const toMin=(t:string)=>{const [h,m]=String(t||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:0}
const addMinutes=(t:string,n=60)=>{const total=(toMin(t)+n)%(24*60);return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
const emptyStudent:Student={id:'',name:'',whatsapp:'',email:'',modality:'Online',address:'',neighborhood:'',city:'Salvador',day:'Segunda',dayOrder:1,time:'09:00',endTime:'10:00',durationMinutes:60,monthlyValue:'500',paymentDay:'10',notes:'',color:'#7427b9',status:'active'}
function wa(phone:string,message:string){const raw=String(phone||'').trim();const digits=raw.replace(/\D/g,'');const p=raw.startsWith('+')?digits:(digits.startsWith('55')?digits:`55${digits}`);return `https://wa.me/${p}?text=${encodeURIComponent(message)}`}

export default function AlunosManagerV2(){
  const [students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(false),[form,setForm]=useState<Student>({...emptyStudent}),[saving,setSaving]=useState(false),[error,setError]=useState('')
  async function load(){setLoading(true);const r=await fetch('/api/admin/alunos',{cache:'no-store'});if(r.ok){const d=await r.json();setStudents(Array.isArray(d.students)?d.students:[])}setLoading(false)}
  useEffect(()=>{load()},[])
  function open(student?:Student){setError('');if(student){const duration=Number(student.durationMinutes||60);setForm({...student,endTime:student.endTime||addMinutes(student.time,duration)})}else setForm({...emptyStudent});setModal(true)}
  function setStart(time:string){const currentDuration=Math.max(15,toMin(form.endTime||'')-toMin(form.time||''))||Number(form.durationMinutes||60)||60;setForm({...form,time,endTime:addMinutes(time,currentDuration),durationMinutes:currentDuration})}
  function setEnd(endTime:string){const duration=toMin(endTime)-toMin(form.time);setForm({...form,endTime,durationMinutes:duration>0?duration:form.durationMinutes})}
  async function submit(e:FormEvent){e.preventDefault();setError('');const duration=toMin(form.endTime||'')-toMin(form.time);if(duration<=0){setError('O término precisa ser depois do horário de início.');return}setSaving(true);const payload={...form,durationMinutes:duration,dayOrder:days.indexOf(form.day)+1};const r=await fetch('/api/admin/alunos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',student:payload})});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setError(d.error||'Não foi possível salvar o aluno.');return}setModal(false);await load()}
  async function doRelease(student:Student){const r=await fetch('/api/admin/alunos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'release',id:student.id})});if(!r.ok){alert('Não foi possível liberar o horário.');return false}return true}
  async function release(student:Student){if(!confirm(`Liberar o horário de ${student.name}? O aluno será mantido no histórico.`))return;if(await doRelease(student))await load()}
  async function replace(student:Student){if(!confirm(`Substituir ${student.name}?\n\nO horário ${student.day} das ${student.time} às ${student.endTime||addMinutes(student.time,student.durationMinutes||60)} será liberado.`))return;if(await doRelease(student))window.location.href='/gestao/aulas/interesse/'}

  return <main className="ga-page"><header className="ga-top"><div><span>FOCO EM CANTO</span><h1>Alunos Particulares</h1></div><a href="/gestao/aulas/">← Voltar para agenda</a></header><section className="ga-shell">
    <nav className="ga-tabs" style={{display:'flex',gap:8,marginBottom:20}}><a href="/gestao/aulas/">Agenda</a><a href="/gestao/aulas/alunos/">Alunos</a><a href="/gestao/aulas/interesse/">Lista de interesse</a></nav>
    <div className="ga-student-toolbar"><div><strong>Base de alunos</strong><span>Agora cada aula bloqueia todo o intervalo entre início e término.</span></div><button onClick={()=>open()}>+ Cadastrar aluno</button></div>
    {loading?<div className="ga-empty students">Carregando alunos...</div>:<div className="ga-student-list">{students.map(student=>{const end=student.endTime||addMinutes(student.time,student.durationMinutes||60);return <article className="ga-student-card" key={student.id} style={{borderLeft:`4px solid ${student.color||'#7427b9'}`}}><div className="ga-student-id"><span style={{background:student.color||'#242c36'}}>{(student.name||'A').charAt(0).toUpperCase()}</span><div><strong>{student.name}</strong><small>{student.whatsapp||'WhatsApp não informado'}</small><i className={`ga-student-status ${student.status}`}>{student.status==='active'?'Ativo':'Inativo'}</i></div></div><div className="ga-student-schedule"><strong>{student.day} • {student.time}–{end}</strong><small>{student.modality}{student.neighborhood?` • ${student.neighborhood}`:''}</small></div><div className="ga-student-meta"><strong>{student.monthlyValue?`R$ ${student.monthlyValue}`:'Valor não informado'}</strong><small>{student.paymentDay?`Pagamento dia ${student.paymentDay}`:''}</small></div><div className="ga-student-actions">{student.whatsapp&&<a target="_blank" href={wa(student.whatsapp,`Oi, ${student.name.split(' ')[0]}! Tudo bem?`)}>WhatsApp</a>}<button onClick={()=>open(student)}>Editar</button>{student.status==='active'&&<><button className="release" onClick={()=>release(student)}>Liberar vaga</button><button onClick={()=>replace(student)} style={{background:'#efcc89',color:'#17120b',fontWeight:900}}>Buscar substituto</button></>}</div></article>})}</div>}
  </section>
  {modal&&<div className="ga-modal-backdrop" onClick={()=>setModal(false)}><div className="ga-student-modal" onClick={e=>e.stopPropagation()}><div className="ga-modal-head"><div><span>{form.id?'EDITAR ALUNO':'NOVO ALUNO'}</span><h2>{form.id?form.name:'Cadastrar aluno atual'}</h2></div><button onClick={()=>setModal(false)}>×</button></div><form className="ga-student-form" onSubmit={submit}>
    <div className="ga-form-section"><strong>Dados do aluno</strong><div className="ga-form-grid"><label className="ga-field"><span>Nome *</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="ga-field"><span>WhatsApp</span><input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><label className="ga-field full"><span>E-mail</span><input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label></div></div>
    <div className="ga-form-section"><strong>Aula fixa</strong><div className="ga-form-grid"><label className="ga-field"><span>Modalidade *</span><select value={form.modality} onChange={e=>setForm({...form,modality:e.target.value})}><option>Online</option><option>Presencial</option></select></label><label className="ga-field"><span>Dia *</span><select value={form.day} onChange={e=>setForm({...form,day:e.target.value})}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label className="ga-field"><span>Início *</span><input type="time" required value={form.time} onChange={e=>setStart(e.target.value)}/></label><label className="ga-field"><span>Término *</span><input type="time" required value={form.endTime||''} onChange={e=>setEnd(e.target.value)}/></label></div><small style={{display:'block',marginTop:8,color:'#8e98a5'}}>Duração: {Math.max(0,toMin(form.endTime||'')-toMin(form.time))} min. Todo esse intervalo ficará reservado.</small></div>
    {form.modality==='Presencial'&&<div className="ga-form-section"><strong>Local da aula presencial</strong><div className="ga-form-grid"><label className="ga-field full"><span>Endereço</span><input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="ga-field"><span>Bairro</span><input value={form.neighborhood||''} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></label><label className="ga-field"><span>Cidade</span><input value={form.city||''} onChange={e=>setForm({...form,city:e.target.value})}/></label></div></div>}
    <div className="ga-form-section"><strong>Financeiro e observações</strong><div className="ga-form-grid"><label className="ga-field"><span>Mensalidade (R$)</span><input value={form.monthlyValue||''} onChange={e=>setForm({...form,monthlyValue:e.target.value})}/></label><label className="ga-field"><span>Dia do pagamento</span><input value={form.paymentDay||''} onChange={e=>setForm({...form,paymentDay:e.target.value})}/></label><label className="ga-field full"><span>Observações</span><textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div></div>
    <div className="ga-form-section"><strong>Cor na agenda</strong><div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:10}}>{colors.map(c=><button key={c} type="button" onClick={()=>setForm({...form,color:c})} style={{width:34,height:34,borderRadius:99,background:c,border:form.color===c?'3px solid #fff':'1px solid rgba(255,255,255,.25)'}}/>)}</div></div>
    {error&&<div className="ga-form-error">{error}</div>}<div className="ga-form-footer"><button type="button" className="secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="ga-student-primary" disabled={saving}>{saving?'Salvando...':'Salvar aluno e reservar intervalo'}</button></div>
  </form></div></div>}
  </main>
}