'use client';
import {useEffect,useMemo,useState} from 'react';
import {loadClosetItems,restoreClosetSession,type ClosetSession} from '../supabase';
import {loadSavedLooks,type SavedLook} from '../savedLooks';
import styles from './insights.module.css';

type Piece={id:string;name:string;category:string;image:string;status:string;createdAt?:string};
function mapRows(rows:any[]):Piece[]{return rows.map(r=>({id:String(r.id),name:r.name,category:r.category,image:r.image||'',status:r.metadata?.wardrobe_status||'available',createdAt:r.created_at}))}
export default function InsightsPage(){
 const [session,setSession]=useState<ClosetSession|null>(null),[pieces,setPieces]=useState<Piece[]>([]),[looks,setLooks]=useState<SavedLook[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{const s=await restoreClosetSession();if(!alive)return;if(!s){setLoading(false);return}setSession(s);const [rows,saved]=await Promise.all([loadClosetItems(s),loadSavedLooks(s).catch(()=>[])]);if(!alive)return;setPieces(mapRows(rows));setLooks(saved);setLoading(false)})().catch(()=>setLoading(false));return()=>{alive=false}},[]);
 const stats=useMemo(()=>{const wear:Record<string,number>={},last:Record<string,string>={};for(const l of looks){for(const id of (l.item_ids||[]).map(String)){wear[id]=(wear[id]||0)+Number(l.worn_count||0);if(l.last_worn_at&&(!last[id]||new Date(l.last_worn_at)>new Date(last[id])))last[id]=l.last_worn_at}}const available=pieces.filter(p=>p.status==='available'),categories=Object.entries(available.reduce((a,p)=>{a[p.category]=(a[p.category]||0)+1;return a},{} as Record<string,number>)).sort((a,b)=>b[1]-a[1]);const most=[...available].sort((a,b)=>(wear[b.id]||0)-(wear[a.id]||0)).slice(0,5);const forgotten=available.filter(p=>!last[p.id]||Date.now()-new Date(last[p.id]).getTime()>1000*60*60*24*30).slice(0,6);return{available:available.length,unavailable:pieces.filter(p=>p.status!=='available').length,totalWorn:Object.values(wear).reduce((a,b)=>a+b,0),categories,most,forgotten,wear,last}},[pieces,looks]);
 const tip=stats.categories.length>1&&stats.categories[0][1]>stats.categories[1][1]*2?`Seu closet está concentrado em ${stats.categories[0][0].toLowerCase()}. Talvez valha equilibrar outras categorias antes de comprar mais.`:stats.forgotten.length>=4?'Você tem várias peças pouco usadas. O Stylist pode montar novos looks começando por elas.':'Seu closet está relativamente equilibrado. Continue registrando o que usa para o app aprender melhor.';
 if(!session&&!loading)return <main className={styles.page}><div className={styles.empty}><h1>Entre no closet primeiro.</h1><button onClick={()=>location.href='/closet'}>Voltar</button></div></main>;
 return <main className={styles.page}><header className={styles.header}><button onClick={()=>history.back()}>‹</button><div><span>INTELIGÊNCIA DO CLOSET</span><strong>Insights</strong></div><button onClick={()=>location.href='/closet'}>⌂</button></header>{loading?<div className={styles.loading}>Analisando seu guarda-roupa…</div>:<><section className={styles.hero}><span>SEU GUARDA-ROUPA EM NÚMEROS</span><h1>Use melhor o que você já tem.</h1><p>Esses dados ajudam o Stylist a variar mais, evitar excessos e recuperar peças esquecidas.</p></section><section className={styles.metrics}><article><strong>{stats.available}</strong><span>disponíveis</span></article><article><strong>{stats.unavailable}</strong><span>fora de uso</span></article><article><strong>{stats.totalWorn}</strong><span>usos registrados</span></article></section><section className={styles.card}><span>LEITURA DO CLOSET</span><h2>{tip}</h2></section><section className={styles.card}><div className={styles.sectionHead}><div><span>CATEGORIAS</span><h2>Como seu closet está distribuído</h2></div></div><div className={styles.bars}>{stats.categories.map(([name,count])=><div key={name}><div><strong>{name}</strong><span>{count}</span></div><i><b style={{width:`${Math.max(12,Math.round(count/Math.max(1,stats.categories[0]?.[1]||1)*100))}%`}}/></i></div>)}</div></section><section className={styles.card}><div className={styles.sectionHead}><div><span>MAIS USADAS</span><h2>Peças que realmente trabalham por você</h2></div></div><div className={styles.pieces}>{stats.most.filter(p=>(stats.wear[p.id]||0)>0).map(p=><button key={p.id} onClick={()=>location.href=`/closet/look?anchor=${encodeURIComponent(p.id)}`}><img src={p.image} alt={p.name}/><strong>{p.name}</strong><small>{stats.wear[p.id]||0} usos</small></button>)}</div>{!stats.most.some(p=>(stats.wear[p.id]||0)>0)&&<p className={styles.muted}>Marque “Usei hoje” nos looks para começar a construir este histórico.</p>}</section><section className={styles.card}><div className={styles.sectionHead}><div><span>REDESCOBRIR</span><h2>Peças que merecem voltar para a rotação</h2></div><button onClick={()=>location.href='/closet/rediscover'}>Ver todas</button></div><div className={styles.pieces}>{stats.forgotten.map(p=><button key={p.id} onClick={()=>location.href=`/closet/look?anchor=${encodeURIComponent(p.id)}`}><img src={p.image} alt={p.name}/><strong>{p.name}</strong><small>{stats.last[p.id]?`há ${Math.floor((Date.now()-new Date(stats.last[p.id]).getTime())/86400000)} dias`:'ainda sem uso registrado'}</small></button>)}</div></section></>}</main>}
