import { driveConfigured } from '../../_lib/google-drive.js'
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}}),clean=(v,n=500)=>String(v||'').trim().slice(0,n)
const cats=new Set(['ministerio','segunda-voz','funcionou','preciso-de-divisao']),shows=new Set(['video','blur','audio']),types=new Set(['video/mp4','video/quicktime','video/webm','audio/mpeg','audio/mp4','audio/wav','audio/x-m4a'])
const phone=v=>{const d=clean(v,30).replace(/\D/g,'');return d.length>=10&&d.length<=15?d:''}
async function hash(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,24)}
export async function onRequestPost({request,env}){if(request.headers.get('Origin')&&request.headers.get('Origin')!==new URL(request.url).origin)return json({message:'Origem não autorizada.'},403);if(!env.FOCO_LINKS)return json({message:'Base de envios indisponível.'},503);if(!driveConfigured(env))return json({message:'Google Drive ainda não está conectado ao formulário.'},503);let b;try{b=await request.json()}catch{return json({message:'Dados inválidos.'},400)}if(clean(b.website))return json({ok:true,id:'received'},201)
 const ipKey=`divisoes:rate:${await hash(request.headers.get('CF-Connecting-IP')||'unknown')}`;if(await env.FOCO_LINKS.get(ipKey))return json({message:'Aguarde alguns minutos antes de outro envio.'},429)
 const d={name:clean(b.name,120),whatsapp:phone(b.whatsapp),instagram:clean(b.instagram,100),ministry:clean(b.ministry,140),city:clean(b.city,120),category:clean(b.category,40),song:clean(b.song,160),songVersion:clean(b.songVersion,160),key:clean(b.key,20),audioSource:clean(b.audioSource,50),question:clean(b.question,1200),appearance:clean(b.appearance,20),allowIdentification:b.allowIdentification==='sim',participantConsent:b.participantConsent==='sim',minorConsent:b.minorConsent==='sim',rightsDeclaration:b.rightsDeclaration==='sim',editingPermission:b.editingPermission==='sim',termsAccepted:b.termsAccepted==='sim',updatesOptIn:b.updatesOptIn==='sim',fileName:clean(b.fileName,220),fileType:clean(b.fileType,100),fileSize:Number(b.fileSize||0)}
 if(!d.name||!d.whatsapp||!d.city||!cats.has(d.category)||!d.song||!d.songVersion||!d.audioSource||!d.question||!shows.has(d.appearance)||!d.participantConsent||!d.minorConsent||!d.rightsDeclaration||!d.editingPermission||!d.termsAccepted)return json({message:'Confira os campos e autorizações obrigatórias.'},422);if(!types.has(d.fileType)||d.fileSize<1||d.fileSize>90*1024*1024)return json({message:'Formato inválido ou arquivo maior que 90 MB.'},422)
 const id=`DIV-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`,uploadToken=crypto.randomUUID()+crypto.randomUUID(),now=new Date().toISOString();await env.FOCO_LINKS.put(`divisoes:submission:${id}`,JSON.stringify({...d,id,createdAt:now,updatedAt:now,status:'pending_upload',termsVersion:'2026-09-02-v1',uploadToken}),{expirationTtl:86400});await env.FOCO_LINKS.put(ipKey,'1',{expirationTtl:180});return json({ok:true,id,uploadToken},201)}
