'use client';
import type {ClosetSession} from './supabase';
const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
function headers(token:string,extra:Record<string,string>={}){return{apikey:anon,Authorization:`Bearer ${token}`,...extra}}async function read(r:Response){const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error||`Marketplace ${r.status}`);return d}async function get<T>(s:ClosetSession,path:string):Promise<T>{return read(await fetch(`${url}/rest/v1/${path}`,{headers:headers(s.access_token)}))}async function rpc<T>(s:ClosetSession,name:string,payload:Record<string,any>):Promise<T>{return read(await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:headers(s.access_token,{'Content-Type':'application/json'}),body:JSON.stringify(payload)}))}
export type BuyerOrder={id:string;order_number:number;status:string;currency:string;products_amount:number;shipping_amount:number;discount_amount:number;total_amount:number;store_id:string;seller_id:string;placed_at?:string|null;paid_at?:string|null;delivered_at?:string|null;completed_at?:string|null;created_at:string;store?:{id:string;name:string;slug:string;verified_identity:boolean;verified_company:boolean;official_brand:boolean;closet_partner:boolean}|null;items?:any[]};
export type BuyerDispute={id:string;order_id:string;reason_code:string;status:string;buyer_statement?:string|null;seller_statement?:string|null;seller_response_due_at?:string|null;payout_hold:boolean;resolution_type?:string|null;resolution_amount?:number|null;opened_at:string;decided_at?:string|null;closed_at?:string|null};
export async function loadBuyerOrders(s:ClosetSession){const select='*,store:closet_stores(id,name,slug,verified_identity,verified_company,official_brand,closet_partner)';return get<BuyerOrder[]>(s,`closet_orders?select=${encodeURIComponent(select)}&buyer_user_id=eq.${encodeURIComponent(s.user.id)}&order=created_at.desc&limit=200`)}
export async function loadOrderItems(s:ClosetSession,orderId:string){const select='*,variant:closet_product_variants(id,title,color,size,price),product:closet_products(id,name,category,subcategory,brand),snapshot:closet_order_item_snapshots(product_snapshot,commercial_snapshot)';return get<any[]>(s,`closet_order_items?select=${encodeURIComponent(select)}&order_id=eq.${encodeURIComponent(orderId)}&order=created_at.asc`)}
export async function loadOrderShipments(s:ClosetSession,orderId:string){return get<any[]>(s,`closet_shipments?select=*&order_id=eq.${encodeURIComponent(orderId)}&order=created_at.desc`)}
export async function loadOrderShipmentEvents(s:ClosetSession,orderId:string){return get<any[]>(s,`closet_shipment_events?select=*&order_id=eq.${encodeURIComponent(orderId)}&order=occurred_at.desc`)}
export async function loadOrderDisputes(s:ClosetSession,orderId:string){return get<BuyerDispute[]>(s,`closet_disputes?select=*&order_id=eq.${encodeURIComponent(orderId)}&order=created_at.desc`)}
export async function loadDisputeMessages(s:ClosetSession,disputeId:string){return get<any[]>(s,`closet_dispute_messages?select=*&dispute_id=eq.${encodeURIComponent(disputeId)}&order=created_at.asc`)}
export async function loadDisputeEvidence(s:ClosetSession,disputeId:string){return get<any[]>(s,`closet_dispute_evidence?select=*&dispute_id=eq.${encodeURIComponent(disputeId)}&order=created_at.asc`)}
export async function openDispute(s:ClosetSession,orderId:string,reason:string,statement:string){return rpc<any>(s,'closet_open_dispute',{p_order_id:orderId,p_reason_code:reason,p_statement:statement})}
export async function addDisputeMessage(s:ClosetSession,disputeId:string,message:string){return rpc<any>(s,'closet_add_dispute_message',{p_dispute_id:disputeId,p_message:message})}
export async function requestReturn(s:ClosetSession,orderId:string,reason:string){return rpc<any>(s,'closet_request_return',{p_order_id:orderId,p_reason:reason})}
export async function createVerifiedReview(s:ClosetSession,orderItemId:string,input:{overall:number;quality:number;fit:string;colorMatches:boolean;materialMatches:boolean;comment:string}){return rpc<any>(s,'closet_create_verified_review',{p_order_item_id:orderItemId,p_overall:input.overall,p_quality:input.quality,p_fit:input.fit,p_color_matches:input.colorMatches,p_material_matches:input.materialMatches,p_comment:input.comment})}
export async function uploadDisputeEvidence(s:ClosetSession,disputeId:string,file:File,caption:string){const form=new FormData();form.append('dispute_id',disputeId);form.append('caption',caption);form.append('file',file);return read(await fetch('/api/closet/disputes/evidence',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`},body:form}))}
export async function getEvidenceUrl(s:ClosetSession,evidenceId:string){return read(await fetch(`${url}/functions/v1/closet-evidence-url`,{method:'POST',headers:{apikey:anon,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({evidence_id:evidenceId})}))}
