export type StylistCategory='Blusas'|'Calças'|'Vestidos'|'Calçados'|'Bolsas'|'Acessórios';
export type ItemStylistPreference={frequency?:'normal'|'rare'|'special'|'never';only_occasions?:string[];note?:string};
export type StylistPiece={id:string|number;category:StylistCategory|string;name:string;meta:string;image:string;stylistPreference?:ItemStylistPreference;wardrobeStatus?:string;rotationPenalty?:number;lastWornAt?:string;wearCount?:number};
export type StyleProfile={wardrobe_gender?:'masculino'|'feminino'|'misto'|string;gender?:string;styles?:string[];preferred_styles?:string[];colors?:string[];preferred_colors?:string[];avoid_colors?:string[];fit?:string;boldness?:number;formality?:number;likes?:Record<string,number>;dislikes?:Record<string,number>;[key:string]:unknown};

const neutral=['preto','branco','off-white','off white','bege','creme','cinza','marrom','caramelo','azul marinho','navy'];
const warm=['bege','creme','marrom','caramelo','terracota','laranja','vermelho','vinho','off-white','off white'];
const cool=['azul','azul marinho','verde','verde oliva','cinza','roxo','lilás','preto','branco'];
const formalWords=['social','alfaiataria','blazer','terno','camisa','oxford','mocassim','loafer','sapato','vestido','saia midi','relógio','relogio'];
const casualWords=['camiseta','tênis','tenis','jeans','malha','suéter','sueter','moletom','chino','sapatênis','sapatenis'];
const sportyWords=['esportivo','running','treino','dry','jogger','sneaker'];
const statementWords=['estampa','estampado','xadrez','listrado','metalizado','brilho','vermelho','laranja','amarelo','roxo'];

function text(p:StylistPiece){return `${p.name} ${p.meta}`.toLowerCase()}
function hasAny(t:string,words:string[]){return words.some(w=>t.includes(w))}
function colorName(p:StylistPiece){const t=text(p);const palette=['off-white','off white','azul marinho','verde oliva','verde escuro','preto','branco','bege','creme','cinza','marrom','caramelo','azul','verde','vermelho','vinho','laranja','amarelo','rosa','roxo','lilás'];return palette.find(c=>t.includes(c))||''}
function garmentType(p:StylistPiece){const t=text(p);if(/camiseta|t-shirt|tee\b/.test(t))return'camiseta';if(/camisa polo|\bpolo\b/.test(t))return'polo';if(/camisa social|dress shirt/.test(t))return'camisa-social';if(/\bcamisa\b/.test(t))return'camisa';if(/su[eé]ter|tricot|tric[oô]/.test(t))return'sueter';if(/moletom|hoodie/.test(t))return'moletom';if(/blazer/.test(t))return'blazer';if(/jaqueta/.test(t))return'jaqueta';if(/casaco|sobretudo/.test(t))return'casaco';if(/cal[cç]a.*alfaiataria|alfaiataria/.test(t))return'alfaiataria';if(/chino/.test(t))return'chino';if(/jeans|denim/.test(t))return'jeans';if(/jogger/.test(t))return'jogger';if(/short|bermuda/.test(t))return'short';if(/saia/.test(t))return'saia';if(/vestido/.test(t))return'vestido';if(/macac[aã]o/.test(t))return'macacao';if(/mocassim|loafer/.test(t))return'mocassim';if(/oxford|derby/.test(t))return'sapato-social';if(/sapat[eê]nis/.test(t))return'sapatenis';if(/t[eê]nis|sneaker/.test(t))return'tenis';if(/bota/.test(t))return'bota';if(/sand[aá]lia/.test(t))return'sandalia';return'outro'}
function accessoryRole(p:StylistPiece){const t=text(p);if(/cinto/.test(t))return'cinto';if(/rel[oó]gio/.test(t))return'relogio';if(/corrente|colar/.test(t))return'colar';if(/pulseira/.test(t))return'pulseira';if(/[oó]culos/.test(t))return'oculos';if(/gravata/.test(t))return'gravata';if(/len[cç]o/.test(t))return'lenco';if(/bon[eé]|chap[eé]u/.test(t))return'chapeu';if(p.category==='Bolsas'||/bolsa|mochila|clutch/.test(t))return'bolsa';return'outro'}
function isPatterned(p:StylistPiece){return /estampa|estampado|xadrez|listr|floral|po[aá]|animal print/.test(text(p))}
function formality(p:StylistPiece){const type=garmentType(p);if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social'].includes(type))return 3;if(['camisa','polo','sueter','chino','vestido','macacao','sapatenis','bota'].includes(type))return 2;if(['camiseta','jeans','tenis','jaqueta','saia'].includes(type))return 1;if(['moletom','jogger','short'].includes(type))return 0;return 1.5}
function profileGender(profile:StyleProfile){return String(profile.wardrobe_gender||profile.gender||'misto').toLowerCase()}
function allowedByProfile(p:StylistPiece,profile:StyleProfile){const g=profileGender(profile),t=text(p);if(g==='misto'||!g)return true;if(g==='masculino'){if(p.category==='Vestidos')return false;if(/\bvestido\b|\bsaia\b|cropped|tomara que caia/.test(t))return false}return true}
function available(p:StylistPiece){return !p.wardrobeStatus||p.wardrobeStatus==='available'}
export function categoriesForProfile(profile:StyleProfile){const g=profileGender(profile);return g==='masculino'?['Todos','Blusas','Calças','Calçados','Bolsas','Acessórios']:['Todos','Blusas','Calças','Vestidos','Calçados','Bolsas','Acessórios']}

function occasionTarget(occasion:string){const o=occasion.toLowerCase();if(['evento','trabalho','igreja'].includes(o))return{formal:3,casual:0,sporty:-2,maxAccessories:3};if(['encontro','festa'].includes(o))return{formal:2,casual:1,sporty:-1,maxAccessories:3};if(['faculdade','escola','sair'].includes(o))return{formal:0,casual:3,sporty:1,maxAccessories:2};if(o==='viagem')return{formal:-1,casual:3,sporty:2,maxAccessories:2};return{formal:1,casual:1,sporty:0,maxAccessories:2}}
function taxonomyScore(p:StylistPiece,occasion:string){const type=garmentType(p),o=occasion.toLowerCase();let s=0;const boost=(types:string[],n:number)=>{if(types.includes(type))s+=n};const punish=(types:string[],n:number)=>{if(types.includes(type))s-=n};if(['faculdade','escola'].includes(o)){boost(['camiseta','polo','sueter','moletom','jeans','chino','jogger','tenis','sapatenis'],7);punish(['camisa-social','blazer','alfaiataria','sapato-social'],6)}if(o==='trabalho'){boost(['camisa','camisa-social','polo','sueter','chino','alfaiataria','mocassim','sapato-social'],8);punish(['moletom','jogger'],7)}if(o==='igreja'){boost(['camisa','camisa-social','polo','sueter','chino','alfaiataria','mocassim','sapato-social'],7);punish(['jogger'],6)}if(o==='evento'){boost(['camisa-social','blazer','alfaiataria','mocassim','sapato-social','vestido'],10);punish(['moletom','jogger','tenis'],8)}if(o==='festa'){boost(['camisa','polo','blazer','chino','alfaiataria','mocassim','vestido','macacao'],6)}if(o==='encontro'){boost(['camisa','polo','sueter','chino','jeans','mocassim','sapatenis','tenis','vestido'],5)}if(o==='sair'){boost(['camiseta','polo','camisa','sueter','jeans','chino','short','tenis','sapatenis'],6);punish(['camisa-social','sapato-social'],3)}if(o==='viagem'){boost(['camiseta','polo','sueter','moletom','jeans','jogger','short','tenis'],8);punish(['blazer','sapato-social'],6)}return s}
function itemPreferenceScore(p:StylistPiece,occasion:string){const pref=p.stylistPreference||{};if(pref.frequency==='never')return-1000;let s=0;if(pref.frequency==='rare')s-=8;if(pref.frequency==='special')s-=5;const only=(pref.only_occasions||[]).map(x=>x.toLowerCase());if(only.length){if(only.includes(occasion.toLowerCase()))s+=14;else s-=30}return s}
function personalScore(p:StylistPiece,profile:StyleProfile){const t=text(p);let s=0;const styles=[...(profile.styles||[]),...(profile.preferred_styles||[])].map(String).map(x=>x.toLowerCase());styles.forEach(v=>{if(t.includes(v))s+=5});const preferred=[...(profile.colors||[]),...(profile.preferred_colors||[])].map(String).map(x=>x.toLowerCase());preferred.forEach(v=>{if(t.includes(v))s+=3});(profile.avoid_colors||[]).map(String).map(x=>x.toLowerCase()).forEach(v=>{if(t.includes(v))s-=7});if(profile.fit&&t.includes(String(profile.fit).toLowerCase()))s+=3;const bold=Number(profile.boldness??.45);if(hasAny(t,statementWords))s+=(bold-.5)*8;Object.entries(profile.likes||{}).forEach(([k,v])=>{if(t.includes(k.toLowerCase()))s+=Number(v)||0});Object.entries(profile.dislikes||{}).forEach(([k,v])=>{if(t.includes(k.toLowerCase()))s-=Math.abs(Number(v)||0)});return s}
function occasionScore(p:StylistPiece,occasion:string){const t=text(p),target=occasionTarget(occasion);let s=taxonomyScore(p,occasion);if(hasAny(t,formalWords))s+=target.formal*3;if(hasAny(t,casualWords))s+=target.casual*3;if(hasAny(t,sportyWords))s+=target.sporty*3;return s}
function colorCompatibility(a:StylistPiece,b:StylistPiece){const ca=colorName(a),cb=colorName(b);if(!ca||!cb)return 0;if(ca===cb)return neutral.includes(ca)?2:0;if(neutral.includes(ca)||neutral.includes(cb))return 5;if((warm.includes(ca)&&warm.includes(cb))||(cool.includes(ca)&&cool.includes(cb)))return 3;return-1}
function pairScore(a:StylistPiece,b:StylistPiece){let s=colorCompatibility(a,b);const ta=text(a),tb=text(b),fa=formality(a),fb=formality(b);const gap=Math.abs(fa-fb);if(gap<=1)s+=3;else if(gap>=2)s-=5;if(hasAny(ta,formalWords)&&hasAny(tb,formalWords))s+=2;if(hasAny(ta,casualWords)&&hasAny(tb,casualWords))s+=2;if(/alfaiataria|social/.test(ta)&&/running|treino/.test(tb))s-=10;if(/alfaiataria|social/.test(tb)&&/running|treino/.test(ta))s-=10;if(isPatterned(a)&&isPatterned(b))s-=7;return s}
function outfitCoherence(items:StylistPiece[],occasion:string){let s=0;for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++)s+=pairScore(items[i],items[j]);const forms=items.filter(p=>!['Acessórios','Bolsas'].includes(String(p.category))).map(formality);if(forms.length){const spread=Math.max(...forms)-Math.min(...forms);if(spread<=1)s+=8;else if(spread>2)s-=10}const patterned=items.filter(isPatterned).length;if(patterned===0)s+=2;if(patterned===1)s+=5;if(patterned>1)s-=8*(patterned-1);const o=occasion.toLowerCase();if(['faculdade','escola','viagem'].includes(o)&&items.some(p=>garmentType(p)==='sapato-social'))s-=8;if(o==='evento'&&items.some(p=>['moletom','jogger'].includes(garmentType(p))))s-=12;return s}
function individualScore(p:StylistPiece,occasion:string,profile:StyleProfile){return occasionScore(p,occasion)+personalScore(p,profile)+itemPreferenceScore(p,occasion)-Number(p.rotationPenalty||0)}
function rank(list:StylistPiece[],occasion:string,profile:StyleProfile,withPieces:StylistPiece[],seed=0){return[...list].filter(p=>available(p)&&allowedByProfile(p,profile)).map((p,i)=>({p,s:individualScore(p,occasion,profile)+withPieces.reduce((n,x)=>n+pairScore(p,x),0)+(((i+seed*7)%11)*.07)})).sort((a,b)=>b.s-a.s).map(x=>x.p)}
function pick(list:StylistPiece[],occasion:string,profile:StyleProfile,withPieces:StylistPiece[],seed=0){const ranked=rank(list.filter(p=>itemPreferenceScore(p,occasion)>-900),occasion,profile,withPieces,seed);return ranked.length?ranked[Math.abs(seed)%Math.min(3,ranked.length)]:undefined}

function bestBaseCombination(wardrobe:StylistPiece[],occasion:string,profile:StyleProfile,seed=0){const tops=rank(wardrobe.filter(p=>p.category==='Blusas'),occasion,profile,[],seed).slice(0,5);const bottoms=rank(wardrobe.filter(p=>p.category==='Calças'),occasion,profile,[],seed+1).slice(0,5);const shoes=rank(wardrobe.filter(p=>p.category==='Calçados'),occasion,profile,[],seed+2).slice(0,5);const dresses=rank(wardrobe.filter(p=>p.category==='Vestidos'),occasion,profile,[],seed).slice(0,4);const candidates:{items:StylistPiece[];score:number}[]=[];
 for(const top of tops)for(const bottom of bottoms)for(const shoe of shoes){const items=[top,bottom,shoe];candidates.push({items,score:items.reduce((n,p)=>n+individualScore(p,occasion,profile),0)+outfitCoherence(items,occasion)})}
 if(profileGender(profile)!=='masculino')for(const dress of dresses)for(const shoe of shoes){const items=[dress,shoe];candidates.push({items,score:items.reduce((n,p)=>n+individualScore(p,occasion,profile),0)+outfitCoherence(items,occasion)+2})}
 candidates.sort((a,b)=>b.score-a.score);if(!candidates.length)return[];const pool=candidates.slice(0,Math.min(4,candidates.length));return pool[Math.abs(seed)%pool.length].items}

function accessoryAllowed(p:StylistPiece,occasion:string,base:StylistPiece[]){const role=accessoryRole(p),o=occasion.toLowerCase(),baseText=base.map(text).join(' ');if(itemPreferenceScore(p,occasion)<-900)return false;if(['faculdade','escola','viagem','sair'].includes(o)&&['gravata','lenco'].includes(role))return false;if(o==='faculdade'&&role==='bolsa'&&/clutch/.test(text(p)))return false;if(role==='gravata'&&!/camisa|social|terno|blazer/.test(baseText))return false;return true}
export function isCompleteLook(items:StylistPiece[]){const dress=items.some(p=>p.category==='Vestidos'),top=items.some(p=>p.category==='Blusas'),bottom=items.some(p=>p.category==='Calças'),shoe=items.some(p=>p.category==='Calçados');return shoe&&(dress||(top&&bottom))}
function addAccessories(all:StylistPiece[],occasion:string,profile:StyleProfile,result:StylistPiece[],seed=0){const accessories=all.filter(p=>available(p)&&allowedByProfile(p,profile)&&(p.category==='Acessórios'||p.category==='Bolsas'));const target=occasionTarget(occasion),usedRoles=new Set<string>();for(const existing of result){if(existing.category==='Acessórios'||existing.category==='Bolsas'){const role=accessoryRole(existing);if(role!=='outro')usedRoles.add(role)}}for(const p of rank(accessories,occasion,profile,result,seed+3)){if(result.length>=3+target.maxAccessories)break;if(result.some(x=>String(x.id)===String(p.id)))continue;const role=accessoryRole(p);if(!accessoryAllowed(p,occasion,result))continue;if(role!=='outro'&&usedRoles.has(role))continue;const compatibility=result.reduce((n,x)=>n+pairScore(p,x),0);if(compatibility<-3)continue;result.push(p);usedRoles.add(role)}return result}
export function buildStyledLook(all:StylistPiece[],occasion:string,profile:StyleProfile={},seed=0){const wardrobe=all.filter(p=>available(p)&&allowedByProfile(p,profile));const base=bestBaseCombination(wardrobe,occasion,profile,seed);if(!isCompleteLook(base))return base;return addAccessories(wardrobe,occasion,profile,[...base],seed)}
export function buildStyledLookWithAnchor(all:StylistPiece[],anchor:StylistPiece,occasion:string,profile:StyleProfile={},seed=0){if(!available(anchor)||!allowedByProfile(anchor,profile))return buildStyledLook(all,occasion,profile,seed);const result:StylistPiece[]=[anchor];const others=all.filter(p=>available(p)&&allowedByProfile(p,profile)&&String(p.id)!==String(anchor.id));if(anchor.category==='Vestidos'){const shoe=pick(others.filter(p=>p.category==='Calçados'),occasion,profile,result,seed+1);if(shoe)result.push(shoe)}else if(anchor.category==='Blusas'){const bottom=pick(others.filter(p=>p.category==='Calças'),occasion,profile,result,seed+1);if(bottom)result.push(bottom);const shoe=pick(others.filter(p=>p.category==='Calçados'),occasion,profile,result,seed+2);if(shoe)result.push(shoe)}else if(anchor.category==='Calças'){const top=pick(others.filter(p=>p.category==='Blusas'),occasion,profile,result,seed+1);if(top)result.unshift(top);const shoe=pick(others.filter(p=>p.category==='Calçados'),occasion,profile,result,seed+2);if(shoe)result.push(shoe)}else if(anchor.category==='Calçados'){const top=pick(others.filter(p=>p.category==='Blusas'),occasion,profile,result,seed+1);if(top)result.unshift(top);const bottom=pick(others.filter(p=>p.category==='Calças'),occasion,profile,result,seed+2);if(bottom)result.splice(top?1:0,0,bottom)}else{const base=buildStyledLook(others,occasion,profile,seed);result.splice(0,result.length,...base,anchor)}if(!isCompleteLook(result))return result;return addAccessories(others,occasion,profile,result,seed)}
export function replacementCandidates(all:StylistPiece[],current:StylistPiece,look:StylistPiece[],occasion:string,profile:StyleProfile={}){const role=accessoryRole(current),base=look.filter(x=>x.id!==current.id);return rank(all.filter(p=>available(p)&&allowedByProfile(p,profile)&&p.id!==current.id&&itemPreferenceScore(p,occasion)>-900&&(current.category==='Acessórios'||current.category==='Bolsas'?((p.category==='Acessórios'||p.category==='Bolsas')&&accessoryRole(p)===role&&accessoryAllowed(p,occasion,base)):p.category===current.category)),occasion,profile,base,0)}