'use client';

import {buildStyledLook,buildStyledLookWithAnchor,type StylistPiece,type StyleProfile} from './lookEngine';
import {memoryScore,type StylistMemory} from './stylistMemory';
import {fashionPulseScore} from './fashionPulse';
import {isBaseTop,isOuterwear} from './lookSemantics';

type V2Context={occasion?:string;period?:string;detail?:string;colors?:string[];paletteMode?:'auto'|'priority'|'strict'|string;work_profile?:{profession?:string;dress_code?:string;notes?:string}|null};
export type LookV2Explanation={mode:string;selectedColors:string[];matched:string[];fallback:string[];message:string};
const neutrals=['preto','branco','off white','off-white','bege','areia','cinza','cinza claro','grafite','marrom','caramelo','azul marinho','azul-marinho'];
const warmFamilies=['bege','areia','nude','caqui','marrom','chocolate','cafe','caramelo','vinho','bordo','marsala','terracota','laranja','ferrugem','coral','amarelo','mostarda','vermelho','rosa','rosa claro'];
const coolFamilies=['azul','azul marinho','azul petroleo','azul royal','azul celeste','verde','verde oliva','verde escuro','verde musgo','verde militar','esmeralda','menta','roxo','lilas','lavanda','magenta','fucsia','cinza','grafite','preto','branco'];
const colors=['off-white','off white','azul-marinho','azul marinho','azul petróleo','azul royal','azul celeste','verde oliva','verde escuro','verde musgo','verde militar','cinza claro','rosa claro','grafite','preto','branco','bege','areia','nude','cáqui','cinza','marrom','chocolate','café','caramelo','azul','verde','esmeralda','menta','vermelho','vinho','bordô','marsala','terracota','laranja','ferrugem','coral','amarelo','mostarda','rosa','roxo','lilás','lavanda','magenta','fúcsia'];
function norm(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim()}
function readContext():V2Context{if(typeof window==='undefined')return{};try{return JSON.parse(sessionStorage.getItem('closet_stylist_context')||'{}')||{}}catch{return{}}}
function writeContext(c:V2Context){if(typeof window!=='undefined')sessionStorage.setItem('closet_stylist_context',JSON.stringify(c))}
function text(p:StylistPiece){return norm(`${p.name||''} ${p.meta||''}`)}
function colorOf(p:StylistPiece){const t=text(p);return colors.find(c=>t.includes(norm(c)))||''}
function selectedColor(p:StylistPiece,c:V2Context){const col=colorOf(p);return Boolean(col&&c.colors?.some(x=>norm(x)===norm(col)))}
function isNeutralColor(p:StylistPiece){const col=norm(colorOf(p));return Boolean(col&&neutrals.some(n=>norm(n)===col))}
function colorFamily(v:string){const n=norm(v);if(neutrals.some(x=>norm(x)===n))return 'neutral';if(warmFamilies.some(x=>norm(x)===n))return 'warm';if(coolFamilies.some(x=>norm(x)===n))return 'cool';return 'other'}
function garment(p:StylistPiece){const t=text(p);if(/camisa social|dress shirt/.test(t))return 'camisa-social';if(/camiseta|t shirt|tee\b/.test(t))return 'camiseta';if(/camisa polo|\bpolo\b/.test(t))return 'polo';if(/\bcamisa\b/.test(t))return 'camisa';if(/blazer/.test(t))return 'blazer';if(/jaqueta|bomber|overshirt/.test(t))return 'jaqueta';if(/sueter|tricot/.test(t))return 'sueter';if(/calca.*alfaiataria|alfaiataria/.test(t))return 'alfaiataria';if(/calca.*moletom|jogger/.test(t))return 'jogger';if(/chino/.test(t))return 'chino';if(/jeans|denim/.test(t))return 'jeans';if(/cargo/.test(t))return 'cargo';if(/short|bermuda/.test(t))return 'short';if(/mocassim|loafer/.test(t))return 'mocassim';if(/oxford|derby|sapato social/.test(t))return 'sapato-social';if(/sapatenis/.test(t))return 'sapatenis';if(/tenis|sneaker/.test(t))return 'tenis';if(/bota/.test(t))return 'bota';if(/sandalia/.test(t))return 'sandalia';if(/vestido/.test(t))return 'vestido';return 'outro'}
function formalLevel(p:StylistPiece){const g=garment(p);if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social'].includes(g))return 3;if(['camisa','polo','sueter','chino','sapatenis','bota','vestido','jaqueta'].includes(g))return 2;if(['camiseta','jeans','cargo','tenis'].includes(g))return 1;if(['jogger','short','sandalia'].includes(g))return 0;return 1.5}
function volume(p:StylistPiece){const t=text(p);if(/oversized|over size|wide|ampla|amplo|larga|largo|baggy|relaxed|boxy/.test(t))return 2;if(/slim|skinny|ajustad|fit/.test(t))return 0;return 1}
function sportyShoe(p:StylistPiece){return garment(p)==='tenis'&&/running|corrida|treino|esportivo|performance|chunky/.test(text(p))}
function notes(c:V2Context){return norm(`${c.work_profile?.profession||''} ${c.work_profile?.notes||''}`)}
function workDressCode(c:V2Context){return String(c.work_profile?.dress_code||'social-casual')}
function workFit(p:StylistPiece,c:V2Context){if(norm(c.occasion||'')!=='trabalho')return 0;const code=workDressCode(c),g=garment(p),f=formalLevel(p),n=notes(c);let s=0;if(code==='formal'){if(['jogger','short','sandalia','tenis','camiseta'].includes(g))return -100;s+=f>=2.5?26:f>=2?8:-22}else if(code==='social'){if(['jogger','short','sandalia'].includes(g))return -100;if(g==='tenis')s-=16;s+=f>=2?21:0}else if(code==='social-casual'){if(['jogger','short'].includes(g))return -90;if(['camisa','polo','chino','jeans','sapatenis','tenis','sueter'].includes(g))s+=18;if(['camisa-social','alfaiataria','mocassim'].includes(g))s+=12}else if(code==='casual'){if(['camiseta','polo','camisa','jeans','chino','cargo','tenis','sapatenis'].includes(g))s+=18;if(['blazer','sapato-social'].includes(g))s-=8}else if(code==='criativo'){if(['camiseta','camisa','polo','jeans','chino','cargo','tenis','sapatenis','blazer','jaqueta'].includes(g))s+=12}else if(code==='uniforme'){if(f>=1&&f<=2.5)s+=8}if(/posso usar tenis|uso tenis|tenis liberado|tenis ok|mobilidade|muito tempo em pe|dirijo|motorista/.test(n)&&g==='tenis')s+=16;if(/nao uso blazer|sem blazer/.test(n)&&g==='blazer')s-=40;if(/nao uso tenis|sem tenis/.test(n)&&g==='tenis')s-=60;if(/camisa social obrigatoria|social obrigatorio/.test(n)&&g==='camisa-social')s+=18;return s}
function contextFit(p:StylistPiece,c:V2Context){const o=norm(c.occasion||''),d=norm(c.detail||''),g=garment(p);let s=workFit(p,c);if(o==='igreja'){if(['camisa','camisa-social','polo','chino','alfaiataria','mocassim','sapatenis'].includes(g))s+=12;if(['jogger','short'].includes(g))s-=45;if(/ministrar|servir|evento especial/.test(d)&&['camisa-social','alfaiataria','mocassim'].includes(g))s+=10}if(o==='evento'){if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social','vestido'].includes(g))s+=16;if(['jogger','short'].includes(g))s-=60}if(o==='festa'){if(['camisa','polo','chino','jeans','tenis','sapatenis','blazer'].includes(g))s+=8}if(['aula','faculdade','escola','passeio','sair'].includes(o)){if(['camiseta','polo','camisa','jeans','chino','cargo','tenis','sapatenis'].includes(g))s+=10}if(/casamento|formatura|cerimonia/.test(o)){if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social','vestido'].includes(g))s+=18;if(['jogger','short'].includes(g))s-=70}if(/parque|shopping|cinema|passeio/.test(o)&&['camiseta','polo','jeans','chino','tenis'].includes(g))s+=10;if(/reuniao|palestra|congresso/.test(o)&&['camisa','camisa-social','polo','chino','alfaiataria','mocassim','sapatenis'].includes(g))s+=12;return s}
function silhouettePairFit(a:StylistPiece,b:StylistPiece){const ga=garment(a),gb=garment(b),va=volume(a),vb=volume(b);let s=0;const topA=['camiseta','camisa','camisa-social','polo','sueter','blazer','jaqueta'].includes(ga),topB=['camiseta','camisa','camisa-social','polo','sueter','blazer','jaqueta'].includes(gb),bottomA=['alfaiataria','jogger','chino','jeans','cargo','short'].includes(ga),bottomB=['alfaiataria','jogger','chino','jeans','cargo','short'].includes(gb);if(((topA&&bottomB)||(topB&&bottomA))&&va===2&&vb===2)s-=9;if(((topA&&bottomB)||(topB&&bottomA))&&Math.abs(va-vb)>=1)s+=2;if((ga==='alfaiataria'&&sportyShoe(b))||(gb==='alfaiataria'&&sportyShoe(a)))s-=34;if((['camisa-social','blazer'].includes(ga)&&sportyShoe(b))||(['camisa-social','blazer'].includes(gb)&&sportyShoe(a)))s-=28;if((ga==='blazer'&&gb==='short')||(gb==='blazer'&&ga==='short'))s-=30;return s}
function pairFit(a:StylistPiece,b:StylistPiece){const ga=garment(a),gb=garment(b);if((['camisa-social','blazer'].includes(ga)&&['jogger','short'].includes(gb))||(['camisa-social','blazer'].includes(gb)&&['jogger','short'].includes(ga)))return -120;if((ga==='sapato-social'&&['jogger','short'].includes(gb))||(gb==='sapato-social'&&['jogger','short'].includes(ga)))return -80;const gap=Math.abs(formalLevel(a)-formalLevel(b));let s=gap<=1?8:gap>=2?-24:0;s+=silhouettePairFit(a,b);const ca=colorOf(a),cb=colorOf(b);if(ca&&cb){const fa=colorFamily(ca),fb=colorFamily(cb);if(norm(ca)===norm(cb))s+=3;else if(fa==='neutral'||fb==='neutral')s+=7;else if(fa===fb)s+=4;else s-=2}return s}
function paletteFit(p:StylistPiece,c:V2Context){if(!c.colors?.length||c.paletteMode==='auto')return 0;if(selectedColor(p,c))return c.paletteMode==='strict'?34:26;if(c.paletteMode==='strict')return -100;if(isNeutralColor(p))return 7;const pc=colorFamily(colorOf(p)),wanted=new Set(c.colors.map(colorFamily));return wanted.has(pc)?4:0}
function availabilityFit(p:StylistPiece){if(p.wardrobeStatus&&p.wardrobeStatus!=='available')return -100;if(p.stylistPreference?.frequency==='never')return -100;if(p.stylistPreference?.frequency==='rare')return -5;if(p.stylistPreference?.frequency==='special')return -2;return 0}
function learnedFit(p:StylistPiece,current:StylistPiece[],c:V2Context,profile:StyleProfile){const m=(profile as any).stylist_memory as StylistMemory|undefined;if(!m)return 0;return memoryScore(m,String(p.id),String(c.occasion||'Geral'),current.map(x=>String(x.id)),{detail:c.detail,period:c.period,dress_code:c.work_profile?.dress_code})*.8}
function candidateScore(p:StylistPiece,current:StylistPiece[],c:V2Context,baseIds:Set<string>,profile:StyleProfile){let s=contextFit(p,c)+paletteFit(p,c)+availabilityFit(p)+(baseIds.has(String(p.id))?9:0)-Number(p.rotationPenalty||0)*1.2+learnedFit(p,current,c,profile)+fashionPulseScore(p,profile);for(const x of current)s+=pairFit(p,x);return s}
function eligible(p:StylistPiece,c:V2Context){if(availabilityFit(p)<=-100)return false;if(c.paletteMode==='strict'&&c.colors?.length&&!selectedColor(p,c))return false;if(contextFit(p,c)<=-90)return false;return true}
function comboScore(items:StylistPiece[],c:V2Context,baseIds:Set<string>,profile:StyleProfile){let s=0;for(const p of items)s+=candidateScore(p,items.filter(x=>String(x.id)!==String(p.id)),c,baseIds,profile);const selectedCount=items.filter(p=>selectedColor(p,c)).length;if(c.paletteMode==='priority'&&c.colors?.length)s+=selectedCount*8;if(items.some(p=>contextFit(p,c)<=-90))return -9999;for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++)if(pairFit(items[i],items[j])<=-100)return -9999;return s}
function isEssentialPiece(p:StylistPiece){return p.category==='Vestidos'||p.category==='Calças'||p.category==='Calçados'||isBaseTop(p)}
function chooseEssentials(base:StylistPiece[],all:StylistPiece[],c:V2Context,profile:StyleProfile,seed=0,anchor?:StylistPiece){const baseIds=new Set(base.map(x=>String(x.id))),fixed=anchor?String(anchor.id):'';const categoryPool=(cat:string)=>all.filter(x=>x.category===cat&&eligible(x,c)).sort((a,b)=>candidateScore(b,[],c,baseIds,profile)-candidateScore(a,[],c,baseIds,profile)).slice(0,28);const tops=categoryPool('Blusas').filter(isBaseTop),bottoms=categoryPool('Calças'),shoes=categoryPool('Calçados'),dresses=categoryPool('Vestidos');const combos:{items:StylistPiece[];score:number}[]=[];const anchorIsEssential=Boolean(anchor&&isEssentialPiece(anchor));const anchored=(items:StylistPiece[])=>!fixed||!anchorIsEssential||items.some(x=>String(x.id)===fixed);for(const top of tops)for(const bottom of bottoms)for(const shoe of shoes){const items=[top,bottom,shoe];if(!anchored(items))continue;const score=comboScore(items,c,baseIds,profile);if(score>-9000)combos.push({items,score})}if(dresses.length)for(const dress of dresses)for(const shoe of shoes){const items=[dress,shoe];if(!anchored(items))continue;const score=comboScore(items,c,baseIds,profile)+4;if(score>-9000)combos.push({items,score})}combos.sort((a,b)=>b.score-a.score);if(combos.length){const ceiling=combos[0].score,viable=combos.filter(x=>x.score>=ceiling-12).slice(0,8);return viable[Math.abs(seed)%viable.length].items}if(anchor&&eligible(anchor,c)&&anchorIsEssential){const fallback=[anchor];const pools:[string,StylistPiece[]][]=[['Blusas',tops],['Calças',bottoms],['Calçados',shoes]];for(const [cat,pool] of pools){if((cat==='Blusas'&&fallback.some(isBaseTop))||fallback.some(x=>x.category===cat)||(anchor.category==='Vestidos'&&cat!=='Calçados'))continue;const candidate=[...pool].sort((a,b)=>candidateScore(b,fallback,c,baseIds,profile)-candidateScore(a,fallback,c,baseIds,profile))[0];if(candidate)fallback.push(candidate)}return fallback}return base.filter(isEssentialPiece)}
function mergeAccessories(base:StylistPiece[],essentials:StylistPiece[],anchor?:StylistPiece){const ids=new Set(essentials.map(x=>String(x.id))),extra=base.filter(x=>!isEssentialPiece(x)&&!ids.has(String(x.id)));const out=[...essentials,...extra.slice(0,3)];if(anchor&&!out.some(x=>String(x.id)===String(anchor.id))&&!isEssentialPiece(anchor))out.push(anchor);return out}
function runV1(all:StylistPiece[],occasion:string,profile:StyleProfile,seed:number,anchor?:StylistPiece){const ctx=readContext(),original={...ctx};try{if(ctx.paletteMode==='strict')writeContext({...ctx,paletteMode:'selected'});else if(ctx.paletteMode==='priority')writeContext({...ctx,paletteMode:'auto'});return anchor?buildStyledLookWithAnchor(all,anchor,occasion,profile,seed):buildStyledLook(all,occasion,profile,seed)}finally{writeContext(original)}}
function build(all:StylistPiece[],occasion:string,profile:StyleProfile,seed:number,anchor?:StylistPiece){const c={...readContext(),occasion},base=runV1(all,occasion,profile,seed,anchor) as StylistPiece[];const essentials=chooseEssentials(base,all,c,profile,seed,anchor);return mergeAccessories(base,essentials,anchor)}
export function explainLookV2(items:StylistPiece[]):LookV2Explanation{const c=readContext(),selectedColors=Array.isArray(c.colors)?c.colors:[],essentials=items.filter(isEssentialPiece),matched=essentials.filter(x=>selectedColor(x,c)).map(x=>x.name),fallback=essentials.filter(x=>!selectedColor(x,c)).map(x=>x.name);let message='O Stylist escolheu a harmonia automaticamente.';if(c.paletteMode==='strict'&&selectedColors.length)message=fallback.length?'Há uma peça fora da paleta estrita; revise o cadastro de cor desta peça.':'Todas as peças principais seguem exatamente a paleta escolhida.';else if(c.paletteMode==='priority'&&selectedColors.length){if(!fallback.length)message='Todas as peças principais seguem sua paleta.';else if(matched.length)message=`Priorizei ${selectedColors.join(' + ')} e completei o look com ${fallback.length===1?'uma peça harmoniosa do seu Closet':'alternativas harmoniosas do seu Closet'}.`;else message=`Não encontrei uma composição coerente somente em ${selectedColors.join(' + ')}, então usei a melhor alternativa disponível no seu Closet.`}return{mode:String(c.paletteMode||'auto'),selectedColors,matched,fallback,message}}
export function buildStyledLookV2(all:StylistPiece[],occasion:string,profile:StyleProfile={},seed=0){return build(all,occasion,profile,seed)}
export function buildStyledLookWithAnchorV2(all:StylistPiece[],anchor:StylistPiece,occasion:string,profile:StyleProfile={},seed=0){return build(all,occasion,profile,seed,anchor)}