'use client';

import {buildStyledLook,buildStyledLookWithAnchor,type StylistPiece,type StyleProfile} from './lookEngine';

type V2Context={occasion?:string;period?:string;detail?:string;colors?:string[];paletteMode?:'auto'|'priority'|'strict'|string;work_profile?:{profession?:string;dress_code?:string;notes?:string}|null};
const neutrals=['preto','branco','off white','off-white','bege','cinza','cinza claro','grafite','marrom','caramelo','azul marinho','azul-marinho'];
const colors=['off-white','off white','azul-marinho','azul marinho','azul petróleo','azul royal','azul celeste','verde oliva','verde escuro','verde musgo','verde militar','cinza claro','rosa claro','grafite','preto','branco','bege','areia','nude','cáqui','cinza','marrom','chocolate','café','caramelo','azul','verde','esmeralda','menta','vermelho','vinho','bordô','marsala','terracota','laranja','ferrugem','coral','amarelo','mostarda','rosa','roxo','lilás','lavanda','magenta','fúcsia'];
function norm(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim()}
function readContext():V2Context{if(typeof window==='undefined')return{};try{return JSON.parse(sessionStorage.getItem('closet_stylist_context')||'{}')||{}}catch{return{}}}
function writeContext(c:V2Context){if(typeof window!=='undefined')sessionStorage.setItem('closet_stylist_context',JSON.stringify(c))}
function text(p:StylistPiece){return norm(`${p.name||''} ${p.meta||''}`)}
function colorOf(p:StylistPiece){const t=text(p);return colors.find(c=>t.includes(norm(c)))||''}
function selectedColor(p:StylistPiece,c:V2Context){const col=colorOf(p);return Boolean(col&&c.colors?.some(x=>norm(x)===norm(col)))}
function garment(p:StylistPiece){const t=text(p);if(/camisa social|dress shirt/.test(t))return'camisa-social';if(/camiseta|t shirt|tee\b/.test(t))return'camiseta';if(/camisa polo|\bpolo\b/.test(t))return'polo';if(/\bcamisa\b/.test(t))return'camisa';if(/blazer/.test(t))return'blazer';if(/sueter|tricot/.test(t))return'sueter';if(/calca.*alfaiataria|alfaiataria/.test(t))return'alfaiataria';if(/calca.*moletom|jogger/.test(t))return'jogger';if(/chino/.test(t))return'chino';if(/jeans|denim/.test(t))return'jeans';if(/cargo/.test(t))return'cargo';if(/short|bermuda/.test(t))return'short';if(/mocassim|loafer/.test(t))return'mocassim';if(/oxford|derby|sapato social/.test(t))return'sapato-social';if(/sapatenis/.test(t))return'sapatenis';if(/tenis|sneaker/.test(t))return'tenis';if(/bota/.test(t))return'bota';if(/sandalia/.test(t))return'sandalia';return'outro'}
function formalLevel(p:StylistPiece){const g=garment(p);if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social'].includes(g))return 3;if(['camisa','polo','sueter','chino','sapatenis','bota'].includes(g))return 2;if(['camiseta','jeans','cargo','tenis'].includes(g))return 1;if(['jogger','short','sandalia'].includes(g))return 0;return 1.5}
function workFit(p:StylistPiece,c:V2Context){if(norm(c.occasion||'')!=='trabalho')return 0;const code=String(c.work_profile?.dress_code||'social-casual'),g=garment(p),f=formalLevel(p);if(code==='formal'){if(['jogger','short','sandalia','tenis','camiseta'].includes(g))return -100;return f>=2.5?24:f>=2?8:-20}if(code==='social'){if(['jogger','short','sandalia'].includes(g))return -100;if(g==='tenis')return -18;return f>=2?20:0}if(code==='social-casual'){if(['jogger','short'].includes(g))return -90;if(['camisa','polo','chino','jeans','sapatenis','tenis','sueter'].includes(g))return 18;if(['camisa-social','alfaiataria','mocassim'].includes(g))return 12;return 0}if(code==='casual'){if(['camiseta','polo','camisa','jeans','chino','cargo','tenis','sapatenis'].includes(g))return 18;if(['blazer','sapato-social'].includes(g))return -8;return 0}if(code==='criativo')return ['camiseta','camisa','polo','jeans','chino','cargo','tenis','sapatenis','blazer'].includes(g)?12:0;if(code==='uniforme')return f>=1&&f<=2.5?8:0;return 0}
function pairFit(a:StylistPiece,b:StylistPiece){const ga=garment(a),gb=garment(b);if((['camisa-social','blazer'].includes(ga)&&['jogger','short'].includes(gb))||(['camisa-social','blazer'].includes(gb)&&['jogger','short'].includes(ga)))return -100;const gap=Math.abs(formalLevel(a)-formalLevel(b));let s=gap<=1?6:gap>=2?-20:0;const ca=colorOf(a),cb=colorOf(b);if(ca&&cb){if(norm(ca)===norm(cb))s+=2;else if(neutrals.some(n=>norm(n)===norm(ca))||neutrals.some(n=>norm(n)===norm(cb)))s+=5}return s}
function candidateScore(p:StylistPiece,current:StylistPiece[],c:V2Context){let s=workFit(p,c);if(c.paletteMode==='priority'&&c.colors?.length)s+=selectedColor(p,c)?28:(neutrals.some(n=>norm(n)===norm(colorOf(p)))?7:0);for(const x of current)s+=pairFit(p,x);return s}
function eligible(p:StylistPiece,c:V2Context){if(p.wardrobeStatus&&p.wardrobeStatus!=='available')return false;if(p.stylistPreference?.frequency==='never')return false;if(c.paletteMode==='strict'&&c.colors?.length&&!selectedColor(p,c))return false;if(workFit(p,c)<=-90)return false;return true}
function refineEssential(base:StylistPiece[],all:StylistPiece[],c:V2Context,anchorId?:string|number){if(c.paletteMode!=='priority'&&norm(c.occasion||'')!=='trabalho')return base;const essential=['Blusas','Calças','Calçados'];let out=[...base];for(const category of essential){const current=out.find(x=>x.category===category);if(current&&String(current.id)===String(anchorId||''))continue;const others=out.filter(x=>x.category!==category);const pool=all.filter(x=>x.category===category&&eligible(x,c));if(!pool.length)continue;const ranked=pool.map(p=>({p,s:candidateScore(p,others,c)+(current&&String(current.id)===String(p.id)?2:0)})).sort((a,b)=>b.s-a.s);const best=ranked[0];if(!best)continue;if(!current){if(best.s>-60)out.push(best.p);continue}const currentScore=candidateScore(current,others,c);if(best.s>currentScore+4)out=out.map(x=>String(x.id)===String(current.id)?best.p:x)}return out}
function runV1(all:StylistPiece[],occasion:string,profile:StyleProfile,seed:number,anchor?:StylistPiece){const ctx=readContext(),original={...ctx};try{if(ctx.paletteMode==='strict')writeContext({...ctx,paletteMode:'selected'});else if(ctx.paletteMode==='priority')writeContext({...ctx,paletteMode:'auto'});return anchor?buildStyledLookWithAnchor(all,anchor,occasion,profile,seed):buildStyledLook(all,occasion,profile,seed)}finally{writeContext(original)}}
export function buildStyledLookV2(all:StylistPiece[],occasion:string,profile:StyleProfile={},seed=0){const c=readContext();const base=runV1(all,occasion,profile,seed) as StylistPiece[];return refineEssential(base,all,c)}
export function buildStyledLookWithAnchorV2(all:StylistPiece[],anchor:StylistPiece,occasion:string,profile:StyleProfile={},seed=0){const c=readContext();const base=runV1(all,occasion,profile,seed,anchor) as StylistPiece[];return refineEssential(base,all,c,anchor.id)}
