export type StylistCategory='Blusas'|'Calças'|'Vestidos'|'Calçados'|'Bolsas'|'Acessórios';
export type ItemStylistPreference={frequency?:'normal'|'rare'|'special'|'never';only_occasions?:string[];note?:string};
export type StylistMemoryContext={occasionLikes?:Record<string,Record<string,number>>;pairLikes?:Record<string,number>;itemLikes?:Record<string,number>};
export type StylistPiece={id:string|number;category:StylistCategory|string;name:string;meta:string;image:string;stylistPreference?:ItemStylistPreference;wardrobeStatus?:string;rotationPenalty?:number;lastWornAt?:string;wearCount?:number};
export type StyleProfile={wardrobe_gender?:'masculino'|'feminino'|'misto'|string;gender?:string;styles?:string[];preferred_styles?:string[];colors?:string[];preferred_colors?:string[];avoid_colors?:string[];fit?:string;boldness?:number;formality?:number;likes?:Record<string,number>;dislikes?:Record<string,number>;weather_context?:Record<string,any>;travel_context?:Record<string,any>;stylist_memory?:StylistMemoryContext;[key:string]:unknown};

type StylistContext={occasion?:string;period?:'manha'|'tarde'|'noite'|string;detail?:string;colors?:string[];paletteMode?:'selected'|'auto'|string};

const neutral=['preto','branco','off-white','off white','bege','creme','cinza','grafite','marrom','caramelo','azul marinho','azul-marinho','navy'];
const warm=['bege','creme','marrom','caramelo','terracota','laranja','vermelho','vinho','off-white','off white'];
const cool=['azul','azul marinho','azul-marinho','verde','verde oliva','cinza','grafite','roxo','lilás','preto','branco'];
const formalWords=['social','alfaiataria','blazer','terno','camisa','oxford','mocassim','loafer','sapato','vestido','saia midi','relógio','relogio'];
const casualWords=['camiseta','tênis','tenis','jeans','malha','suéter','sueter','moletom','chino','sapatênis','sapatenis'];
const sportyWords=['esportivo','running','treino','dry','jogger','sneaker'];
const statementWords=['estampa','estampado','xadrez','listrado','metalizado','brilho','vermelho','laranja','amarelo','roxo'];
const lightColors=['branco','off-white','off white','bege','creme','cinza claro','azul claro','rosa claro'];
const darkColors=['preto','grafite','azul marinho','azul-marinho','navy','vinho','marrom','verde escuro'];

function normalize(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function text(p:StylistPiece){return `${p.name} ${p.meta}`.toLowerCase()}
function hasAny(t:string,w:string[]){return w.some(x=>t.includes(x))}
function profileGender(p:StyleProfile){return String(p.wardrobe_gender||p.gender||'misto').toLowerCase()}
function available(p:StylistPiece){return !p.wardrobeStatus||p.wardrobeStatus==='available'}
function allowedByProfile(p:StylistPiece,profile:StyleProfile){const g=profileGender(profile),t=text(p);if(g==='misto'||!g)return true;if(g==='masculino'&&(p.category==='Vestidos'||/\bvestido\b|\bsaia\b|cropped|tomara que caia/.test(t)))return false;return true}
export function categoriesForProfile(profile:StyleProfile){return profileGender(profile)==='masculino'?['Todos','Blusas','Calças','Calçados','Bolsas','Acessórios']:['Todos','Blusas','Calças','Vestidos','Calçados','Bolsas','Acessórios']}
function readContext():StylistContext{if(typeof window==='undefined')return{};try{return JSON.parse(sessionStorage.getItem('closet_stylist_context')||'{}')||{}}catch{return{}}}
function contextFor(o:string){const c=readContext();return normalize(c.occasion||'')===normalize(o)?c:{} as StylistContext}
function colorName(p:StylistPiece){const t=text(p),palette=['off-white','off white','azul-marinho','azul marinho','verde oliva','verde escuro','azul claro','cinza claro','grafite','preto','branco','bege','creme','cinza','marrom','caramelo','azul','verde','vermelho','vinho','laranja','amarelo','rosa','roxo','lilás'];return palette.find(c=>t.includes(c))||''}
function sameColor(a:string,b:string){return normalize(a).replace(/-/g,' ')===normalize(b).replace(/-/g,' ')}
function paletteAllows(p:StylistPiece,o:string){const c=contextFor(o);if(c.paletteMode!=='selected'||!c.colors?.length)return true;const col=colorName(p);if(!col)return true;return c.colors.some(x=>sameColor(x,col))}
function garmentType(p:StylistPiece){const t=text(p);if(/camiseta|t-shirt|tee\b/.test(t))return'camiseta';if(/camisa polo|\bpolo\b/.test(t))return'polo';if(/camisa social|dress shirt/.test(t))return'camisa-social';if(/\bcamisa\b/.test(t))return'camisa';if(/su[eé]ter|tricot|tric[oô]/.test(t))return'sueter';if(/moletom|hoodie/.test(t))return'moletom';if(/blazer/.test(t))return'blazer';if(/jaqueta/.test(t))return'jaqueta';if(/casaco|sobretudo/.test(t))return'casaco';if(/cal[cç]a.*alfaiataria|alfaiataria/.test(t))return'alfaiataria';if(/chino/.test(t))return'chino';if(/jeans|denim/.test(t))return'jeans';if(/jogger/.test(t))return'jogger';if(/short|bermuda/.test(t))return'short';if(/saia/.test(t))return'saia';if(/vestido/.test(t))return'vestido';if(/macac[aã]o/.test(t))return'macacao';if(/mocassim|loafer/.test(t))return'mocassim';if(/oxford|derby|sapato social/.test(t))return'sapato-social';if(/sapat[eê]nis/.test(t))return'sapatenis';if(/t[eê]nis|sneaker/.test(t))return'tenis';if(/bota/.test(t))return'bota';if(/sand[aá]lia/.test(t))return'sandalia';if(/salto/.test(t))return'salto';return'outro'}
function accessoryRole(p:StylistPiece){const t=text(p);if(/cinto/.test(t))return'cinto';if(/rel[oó]gio/.test(t))return'relogio';if(/corrente|colar/.test(t))return'colar';if(/pulseira/.test(t))return'pulseira';if(/[oó]culos/.test(t))return'oculos';if(/gravata/.test(t))return'gravata';if(/len[cç]o/.test(t))return'lenco';if(/bon[eé]|chap[eé]u/.test(t))return'chapeu';if(p.category==='Bolsas'||/bolsa|mochila|clutch/.test(t))return'bolsa';return'outro'}
function isPatterned(p:StylistPiece){return /estampa|estampado|xadrez|listr|floral|po[aá]|animal print/.test(text(p))}
function formality(p:StylistPiece){const t=garmentType(p);if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social','salto'].includes(t))return 3;if(['camisa','polo','sueter','chino','vestido','macacao','sapatenis','bota'].includes(t))return 2;if(['camiseta','jeans','tenis','jaqueta','saia'].includes(t))return 1;if(['moletom','jogger','short','sandalia'].includes(t))return 0;return 1.5}
function thermalClass(p:StylistPiece){const type=garmentType(p),t=text(p);if(['sueter','moletom','casaco','jaqueta','blazer','bota'].includes(type)||/l[aã]|tricot|inverno|quente/.test(t))return'frio';if(['short','sandalia','camiseta'].includes(type)||/linho|leve|dry|respir[aá]vel/.test(t))return'quente';return'meia'}
function occasionTarget(o:string){const x=normalize(o);let formal=1,casual=1,sporty=0,maxAccessories=2;if(['evento','trabalho','igreja'].includes(x)){formal=3;casual=0;sporty=-2;maxAccessories=3}else if(['encontro','festa'].includes(x)){formal=2;casual=1;sporty=-1;maxAccessories=3}else if(['faculdade','escola','sair','passeio'].includes(x)){formal=0;casual=3;sporty=1;maxAccessories=2}else if(x==='viagem'){formal=-1;casual=3;sporty=2;maxAccessories=2}const c=contextFor(o),d=normalize(c.detail||'');if(/formal|cerimonia|casamento|formatura|reuniao importante|evento especial|ministrar|servir/.test(d)){formal+=2;casual-=1;sporty-=1}if(/casual|dia normal|culto comum|aula|passeio/.test(d)){casual+=1;formal-=.5}return{formal,casual,sporty,maxAccessories}}
function taxonomyScore(p:StylistPiece,o:string){const type=garmentType(p),x=normalize(o),d=normalize(contextFor(o).detail||'');let s=0,b=(a:string[],n:number)=>{if(a.includes(type))s+=n},z=(a:string[],n:number)=>{if(a.includes(type))s-=n};if(['faculdade','escola'].includes(x)){b(['camiseta','polo','sueter','moletom','jeans','chino','jogger','tenis','sapatenis'],8);z(['camisa-social','blazer','alfaiataria','sapato-social'],7)}if(x==='trabalho'){b(['camisa','camisa-social','polo','sueter','chino','alfaiataria','mocassim','sapato-social'],8);z(['moletom','jogger','short'],8)}if(x==='igreja'){b(['camisa','camisa-social','polo','sueter','chino','alfaiataria','mocassim','sapato-social'],7);z(['jogger','short'],7)}if(x==='evento'){b(['camisa-social','blazer','alfaiataria','mocassim','sapato-social','vestido','salto'],11);z(['moletom','jogger','tenis','short'],9)}if(x==='festa')b(['camisa','polo','blazer','chino','alfaiataria','mocassim','vestido','macacao','salto'],6);if(x==='encontro')b(['camisa','polo','sueter','chino','jeans','mocassim','sapatenis','tenis','vestido'],5);if(['sair','passeio'].includes(x)){b(['camiseta','polo','camisa','sueter','jeans','chino','short','tenis','sapatenis'],7);z(['camisa-social','sapato-social'],3)}if(x==='viagem'){b(['camiseta','polo','sueter','moletom','jeans','jogger','short','tenis'],8);z(['blazer','sapato-social'],6)}if(/ministrar|servir/.test(d)){b(['camisa','camisa-social','polo','chino','alfaiataria','mocassim','sapato-social'],5);z(['short','jogger','moletom'],6)}if(/reuniao importante|evento profissional/.test(d)){b(['camisa-social','blazer','alfaiataria','mocassim','sapato-social'],6)}if(/jantar|especial|arrumado/.test(d)){b(['camisa','polo','chino','mocassim','sapatenis','vestido'],4)}return s}
function periodScore(p:StylistPiece,o:string){const c=contextFor(o),period=normalize(c.period||''),col=colorName(p);if(!period)return 0;let s=0;if(period==='manha'){if(lightColors.includes(col))s+=3;if(['camiseta','polo','camisa','chino','tenis','sapatenis'].includes(garmentType(p)))s+=1.5}if(period==='noite'){if(darkColors.includes(col))s+=2.5;if(['camisa','camisa-social','polo','blazer','alfaiataria','mocassim','sapato-social','vestido'].includes(garmentType(p)))s+=1.5}return s}
function paletteScore(p:StylistPiece,o:string){const c=contextFor(o);if(c.paletteMode!=='selected'||!c.colors?.length)return 0;const col=colorName(p);if(!col)return-4;return c.colors.some(x=>sameColor(x,col))?24:-40}
function weatherScore(p:StylistPiece,profile:StyleProfile){const w=profile.weather_context||{},tr=profile.travel_context||{},max=Number(w.tempMax??tr.tempMax),min=Number(w.tempMin??tr.tempMin),rain=Number(w.rainChance??tr.rainChance),type=garmentType(p),t=text(p);if(!Number.isFinite(max)&&!Number.isFinite(rain)&&!tr.thermalNeed)return 0;let s=0;if(Number.isFinite(max)&&max>=29){if(['camiseta','polo','camisa','short','sandalia','vestido'].includes(type))s+=7;if(['sueter','moletom','casaco','jaqueta','blazer','bota'].includes(type))s-=10;if(/linho|algod[aã]o|leve|dry|respir[aá]vel/.test(t))s+=5}else if(Number.isFinite(max)&&max<=20){if(['sueter','moletom','casaco','jaqueta','blazer','bota'].includes(type))s+=8;if(['short','sandalia'].includes(type))s-=8}if(Number.isFinite(min)&&min<=16&&['sueter','jaqueta','casaco','blazer'].includes(type))s+=5;if(Number.isFinite(rain)&&rain>=55){if(['bota','sapato-social','mocassim'].includes(type))s+=3;if(type==='sandalia')s-=8;if(/camur[cç]a|suede/.test(t))s-=10}const need=normalize(String(tr.thermalNeed||''));if(need==='warm'&&thermalClass(p)==='frio')s+=4;if(need==='cool'&&thermalClass(p)==='quente')s+=4;return s}
function itemPreferenceScore(p:StylistPiece,o:string){const q=p.stylistPreference||{};if(q.frequency==='never')return-1000;let s=q.frequency==='rare'?-8:q.frequency==='special'?-5:0,only=(q.only_occasions||[]).map(normalize);if(only.length)s+=only.includes(normalize(o))?14:-30;return s}
function personalScore(p:StylistPiece,profile:StyleProfile){const t=text(p);let s=0;[...(profile.styles||[]),...(profile.preferred_styles||[])].map(String).forEach(v=>{if(t.includes(v.toLowerCase()))s+=5});[...(profile.colors||[]),...(profile.preferred_colors||[])].map(String).forEach(v=>{if(t.includes(v.toLowerCase()))s+=3});(profile.avoid_colors||[]).map(String).forEach(v=>{if(t.includes(v.toLowerCase()))s-=7});if(profile.fit&&t.includes(String(profile.fit).toLowerCase()))s+=3;if(hasAny(t,statementWords))s+=(Number(profile.boldness??.45)-.5)*8;return s}
function memoryScore(p:StylistPiece,o:string,profile:StyleProfile,withPieces:StylistPiece[]=[]){const m=profile.stylist_memory;if(!m)return 0;const id=String(p.id);let s=(m.itemLikes?.[id]||0)*.35+(m.occasionLikes?.[o]?.[id]||m.occasionLikes?.[Object.keys(m.occasionLikes||{}).find(k=>normalize(k)===normalize(o))||'']?.[id]||0)*.8;for(const x of withPieces){const k=[id,String(x.id)].sort().join('|');s+=(m.pairLikes?.[k]||0)*.55}return Math.max(-25,Math.min(25,s))}
function recentWearPenalty(p:StylistPiece){let s=Number(p.rotationPenalty||0)*1.7;if(p.lastWornAt){const days=Math.max(0,(Date.now()-new Date(p.lastWornAt).getTime())/86400000);if(days<1)s+=18;else if(days<3)s+=11;else if(days<7)s+=6;else if(days<14)s+=2}if(Number(p.wearCount||0)>5)s+=Math.min(5,Number(p.wearCount||0)*.3);return s}
function occasionScore(p:StylistPiece,o:string){const t=text(p),q=occasionTarget(o);let s=taxonomyScore(p,o);if(hasAny(t,formalWords))s+=q.formal*3;if(hasAny(t,casualWords))s+=q.casual*3;if(hasAny(t,sportyWords))s+=q.sporty*3;return s}
function colorCompatibility(a:StylistPiece,b:StylistPiece){const x=colorName(a),y=colorName(b);if(!x||!y)return 0;if(x===y)return neutral.includes(x)?2:0;if(neutral.includes(x)||neutral.includes(y))return 5;if((warm.includes(x)&&warm.includes(y))||(cool.includes(x)&&cool.includes(y)))return 3;return-1}
function pairScore(a:StylistPiece,b:StylistPiece){let s=colorCompatibility(a,b),ta=text(a),tb=text(b),gap=Math.abs(formality(a)-formality(b));if(gap<=1)s+=3;else if(gap>=2)s-=5;if(hasAny(ta,formalWords)&&hasAny(tb,formalWords))s+=2;if(hasAny(ta,casualWords)&&hasAny(tb,casualWords))s+=2;if((/alfaiataria|social/.test(ta)&&/running|treino/.test(tb))||(/alfaiataria|social/.test(tb)&&/running|treino/.test(ta)))s-=10;if(isPatterned(a)&&isPatterned(b))s-=7;return s}
function individualScore(p:StylistPiece,o:string,profile:StyleProfile,withPieces:StylistPiece[]=[]){return occasionScore(p,o)+personalScore(p,profile)+weatherScore(p,profile)+periodScore(p,o)+paletteScore(p,o)+itemPreferenceScore(p,o)+memoryScore(p,o,profile,withPieces)-recentWearPenalty(p)}
function outfitCoherence(items:StylistPiece[],o:string,profile:StyleProfile){let s=0;for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++)s+=pairScore(items[i],items[j])+memoryScore(items[i],o,profile,[items[j]])*.35;const forms=items.filter(p=>!['Acessórios','Bolsas'].includes(String(p.category))).map(formality);if(forms.length){const spread=Math.max(...forms)-Math.min(...forms);s+=spread<=1?8:spread>2?-10:0}const patterned=items.filter(isPatterned).length;s+=patterned===0?2:patterned===1?5:-8*(patterned-1);const chosen=contextFor(o).colors||[];if(chosen.length){const hits=new Set(items.map(colorName).filter(Boolean).map(normalize).filter(c=>chosen.map(normalize).includes(c))).size;s+=Math.min(hits,chosen.length)*6}return s}
function rank(list:StylistPiece[],o:string,profile:StyleProfile,withPieces:StylistPiece[],seed=0){return[...list].filter(p=>available(p)&&allowedByProfile(p,profile)&&paletteAllows(p,o)).map((p,i)=>({p,s:individualScore(p,o,profile,withPieces)+withPieces.reduce((n,x)=>n+pairScore(p,x),0)+(((i+seed*13)%17)*.13)})).sort((a,b)=>b.s-a.s).map(x=>x.p)}
function pick(list:StylistPiece[],o:string,p:StyleProfile,w:StylistPiece[],seed=0){const r=rank(list.filter(x=>itemPreferenceScore(x,o)>-900),o,p,w,seed);return r.length?r[Math.abs(seed)%Math.min(5,r.length)]:undefined}
function bestBaseCombination(w:StylistPiece[],o:string,p:StyleProfile,seed=0){const tops=rank(w.filter(x=>x.category==='Blusas'),o,p,[],seed).slice(0,8),bottoms=rank(w.filter(x=>x.category==='Calças'),o,p,[],seed+1).slice(0,8),shoes=rank(w.filter(x=>x.category==='Calçados'),o,p,[],seed+2).slice(0,8),dresses=rank(w.filter(x=>x.category==='Vestidos'),o,p,[],seed).slice(0,6),c:{items:StylistPiece[];score:number}[]=[];for(const a of tops)for(const b of bottoms)for(const d of shoes){const items=[a,b,d];c.push({items,score:items.reduce((n,x)=>n+individualScore(x,o,p,items.filter(y=>y!==x)),0)+outfitCoherence(items,o,p)})}if(profileGender(p)!=='masculino')for(const a of dresses)for(const b of shoes){const items=[a,b];c.push({items,score:items.reduce((n,x)=>n+individualScore(x,o,p,items.filter(y=>y!==x)),0)+outfitCoherence(items,o,p)+2})}c.sort((a,b)=>b.score-a.score);const pool=c.slice(0,Math.min(12,c.length));return pool.length?pool[Math.abs(seed)%pool.length].items:[]}
function accessoryAllowed(p:StylistPiece,o:string,base:StylistPiece[]){const role=accessoryRole(p),x=normalize(o),bt=base.map(text).join(' ');if(itemPreferenceScore(p,o)<-900)return false;if(['faculdade','escola','viagem','sair','passeio'].includes(x)&&['gravata','lenco'].includes(role))return false;if(x==='faculdade'&&role==='bolsa'&&/clutch/.test(text(p)))return false;if(role==='gravata'&&!/camisa|social|terno|blazer/.test(bt))return false;return true}
export function isCompleteLook(items:StylistPiece[]){const dress=items.some(p=>p.category==='Vestidos'),top=items.some(p=>p.category==='Blusas'),bottom=items.some(p=>p.category==='Calças'),shoe=items.some(p=>p.category==='Calçados');return shoe&&(dress||(top&&bottom))}
function addAccessories(all:StylistPiece[],o:string,p:StyleProfile,result:StylistPiece[],seed=0){const a=all.filter(x=>available(x)&&allowedByProfile(x,p)&&(x.category==='Acessórios'||x.category==='Bolsas')),target=occasionTarget(o),roles=new Set<string>();for(const x of result){const r=accessoryRole(x);if(r!=='outro')roles.add(r)}for(const x of rank(a,o,p,result,seed+3)){if(result.length>=3+target.maxAccessories)break;const r=accessoryRole(x);if(result.some(y=>String(y.id)===String(x.id))||!accessoryAllowed(x,o,result)||(r!=='outro'&&roles.has(r)))continue;if(result.reduce((n,y)=>n+pairScore(x,y),0)<-3)continue;result.push(x);roles.add(r)}return result}
export function buildStyledLook(all:StylistPiece[],o:string,p:StyleProfile={},seed=0){const w=all.filter(x=>available(x)&&allowedByProfile(x,p)),base=bestBaseCombination(w,o,p,seed);return isCompleteLook(base)?addAccessories(w,o,p,[...base],seed):base}
export function buildStyledLookWithAnchor(all:StylistPiece[],anchor:StylistPiece,o:string,p:StyleProfile={},seed=0){if(!available(anchor)||!allowedByProfile(anchor,p))return buildStyledLook(all,o,p,seed);const r:StylistPiece[]=[anchor],others=all.filter(x=>available(x)&&allowedByProfile(x,p)&&String(x.id)!==String(anchor.id));if(anchor.category==='Vestidos'){const x=pick(others.filter(p=>p.category==='Calçados'),o,p,r,seed+1);if(x)r.push(x)}else if(anchor.category==='Blusas'){const b=pick(others.filter(p=>p.category==='Calças'),o,p,r,seed+1);if(b)r.push(b);const s=pick(others.filter(p=>p.category==='Calçados'),o,p,r,seed+2);if(s)r.push(s)}else if(anchor.category==='Calças'){const t=pick(others.filter(p=>p.category==='Blusas'),o,p,r,seed+1);if(t)r.unshift(t);const s=pick(others.filter(p=>p.category==='Calçados'),o,p,r,seed+2);if(s)r.push(s)}else if(anchor.category==='Calçados'){const t=pick(others.filter(p=>p.category==='Blusas'),o,p,r,seed+1);if(t)r.unshift(t);const b=pick(others.filter(p=>p.category==='Calças'),o,p,r,seed+2);if(b)r.splice(t?1:0,0,b)}else{const base=buildStyledLook(others,o,p,seed);r.splice(0,r.length,...base,anchor)}return isCompleteLook(r)?addAccessories(others,o,p,r,seed):r}
export function replacementCandidates(all:StylistPiece[],current:StylistPiece,look:StylistPiece[],o:string,p:StyleProfile={}):StylistPiece[]{const role=accessoryRole(current),base=look.filter(x=>x.id!==current.id);return rank(all.filter(x=>available(x)&&allowedByProfile(x,p)&&x.id!==current.id&&itemPreferenceScore(x,o)>-900&&(current.category==='Acessórios'||current.category==='Bolsas'?((x.category==='Acessórios'||x.category==='Bolsas')&&accessoryRole(x)===role&&accessoryAllowed(x,o,base)):x.category===current.category)),o,p,base,0)}