'use client';
import {saveAffiliateClosetItem,type ClosetSession} from './supabase';import {learnFromMarketplacePurchase} from './stylistMemory';
export type MarketplaceProduct={id:string;partner_id:string;name:string;category:string;subcategory?:string|null;price?:number|null;currency?:string|null;image_url?:string|null;product_url:string;tags?:string[];thermal_level?:number|null;weather_protection?:Record<string,any>|null;style_tags?:string[];partner?:{id:string;name:string;credit_reward?:number|null}|null};
const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';function headers(token?:string,extra:Record<string,string>={}){return {apikey:anon,...(token?{Authorization:`Bearer ${token}`}:{Authorization:`Bearer ${anon}`}),...extra}}function closetCategory(p:MarketplaceProduct){const t=`${p.category} ${p.subcategory||''} ${p.name}`.toLowerCase();if(/vestido|macacão|macacao/.test(t))return'Vestidos';if(/calça|calca|short|saia|bermuda/.test(t))return'Calças';if(/sapato|tênis|tenis|bota|sandália|sandalia|calçado|calcado/.test(t))return'Calçados';if(/bolsa|mochila|carteira/.test(t))return'Bolsas';if(/cinto|relógio|relogio|óculos|oculos|colar|pulseira|acessório|acessorio/.test(t))return'Acessórios';return'Blusas'}
export async function loadMarketplaceProducts():Promise<MarketplaceProduct[]>{const select='id,partner_id,name,category,subcategory,price,currency,image_url,product_url,tags,thermal_level,weather_protection,style_tags,partner:closet_partners(id,name,credit_reward)';try{const r=await fetch(`${url}/rest/v1/closet_partner_products?active=eq.true&select=${encodeURIComponent(select)}&order=created_at.desc&limit=200`,{headers:headers()}),d=await r.json();return r.ok?d:[]}catch{return[]}}
export function rankMarketplaceProducts(products:MarketplaceProduct[],category:string,query:string){const terms=`${category} ${query}`.toLowerCase().split(/\s+/).filter(x=>x.length>2);return products.map(p=>{const hay=`${p.name} ${p.category} ${p.subcategory||''} ${(p.tags||[]).join(' ')} ${(p.style_tags||[]).join(' ')}`.toLowerCase();let score=terms.reduce((n,t)=>n+(hay.includes(t)?2:0),0);if(p.category.toLowerCase()===category.toLowerCase())score+=8;return{...p,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
async function track(session:ClosetSession|null,event_type:'impression'|'click'|'purchase_confirmed',input:{product:MarketplaceProduct;trip?:string;moment?:string;category:string;query:string;metadata?:Record<string,any>}){if(!session)return;try{await fetch(`${url}/rest/v1/closet_marketplace_events`,{method:'POST',headers:headers(session.access_token,{'Content-Type':'application/json'}),body:JSON.stringify({user_id:session.user.id,partner_id:input.product.partner_id,product_id:input.product.id,trip_id:input.trip||null,moment_id:input.moment||null,event_type,source:'stylist_gap',category:input.category,query:input.query,metadata:{credit_reward:input.product.partner?.credit_reward||0,...(input.metadata||{})}})})}catch{}}
export const trackMarketplaceClick=(session:ClosetSession|null,input:{product:MarketplaceProduct;trip?:string;moment?:string;category:string;query:string})=>track(session,'click',input);export const trackMarketplaceImpression=(session:ClosetSession|null,input:{product:MarketplaceProduct;trip?:string;moment?:string;category:string;query:string})=>track(session,'impression',input);
async function existingImportedItem(session:ClosetSession,productId:string){try{const q=`user_id=eq.${encodeURIComponent(session.user.id)}&is_active=eq.true&metadata->>marketplace_product_id=eq.${encodeURIComponent(productId)}&select=id,name,category,metadata&limit=1`,r=await fetch(`${url}/rest/v1/closet_items?${q}`,{headers:headers(session.access_token)}),d=await r.json();return r.ok&&Array.isArray(d)&&d[0]?d[0]:null}catch{return null}}
export async function confirmMarketplacePurchase(session:ClosetSession,input:{product:MarketplaceProduct;trip?:string;moment?:string;category:string;query:string}){const p=input.product,category=closetCategory(p),existing=await existingImportedItem(session,p.id),item=existing||await saveAffiliateClosetItem(session,{name:p.name,category,subcategory:p.subcategory||p.category||null,brand:p.partner?.name||null,imageUrl:p.image_url||null,productUrl:p.product_url,partnerId:p.partner_id,productId:p.id,tripId:input.trip||null,momentId:input.moment||null,thermalLevel:p.thermal_level||null,tags:p.tags||[]});if(input.trip){try{await fetch(`${url}/rest/v1/closet_trip_packing`,{method:'POST',headers:headers(session.access_token,{'Content-Type':'application/json','Prefer':'resolution=merge-duplicates'}),body:JSON.stringify({trip_id:input.trip,item_id:item.id,user_id:session.user.id,packed:false,purchased_for_trip:true})})}catch{}}if(!existing)learnFromMarketplacePurchase(session,String(item.id),category);await track(session,'purchase_confirmed',{...input,metadata:{confirmation_source:'user',closet_item_id:item.id,existing_item:Boolean(existing)}});return item}
