'use client';

const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
const headers={apikey:anon,Authorization:`Bearer ${anon}`};
async function get<T>(path:string):Promise<T>{if(!url||!anon)throw new Error('Marketplace não configurado.');const r=await fetch(`${url}/rest/v1/${path}`,{headers,cache:'no-store'}),t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||`Marketplace ${r.status}`);return d}
export type PublicSellerProduct={id:string;name:string;description?:string|null;brand?:string|null;category:string;subcategory?:string|null;gender_profile?:string|null;tags:string[];style_tags:string[];thermal_level?:number|null;weather_protection?:Record<string,any>;store:{id:string;name:string;slug:string;verified_identity:boolean;verified_company:boolean;official_brand:boolean;closet_partner:boolean;seller_id:string}|null;variants:{id:string;sku?:string|null;title?:string|null;color?:string|null;size?:string|null;material?:string|null;price:number;currency:string;status:string}[];media:{id:string;url:string;position:number;media_type:string}[]};
export type MarketplaceSettings={transactions_enabled:boolean;payment_provider:string;shipping_provider:string;protection_window_days:number;withdrawal_window_days:number;seller_response_hours:number};
const publicSelect='id,name,description,brand,category,subcategory,gender_profile,tags,style_tags,thermal_level,weather_protection,store:closet_stores(id,name,slug,verified_identity,verified_company,official_brand,closet_partner,seller_id),variants:closet_product_variants(id,sku,title,color,size,material,price,currency,status),media:closet_product_media(id,url,position,media_type)';
export async function loadPublicSellerProducts(limit=120){return get<PublicSellerProduct[]>(`closet_products?select=${encodeURIComponent(publicSelect)}&status=eq.active&order=updated_at.desc&limit=${Math.max(1,Math.min(limit,300))}`)}
export async function loadPublicSellerProduct(id:string){const rows=await get<PublicSellerProduct[]>(`closet_products?select=${encodeURIComponent(publicSelect)}&id=eq.${encodeURIComponent(id)}&status=eq.active&limit=1`);return rows[0]||null}
export async function loadMarketplaceSettings():Promise<MarketplaceSettings>{const rows=await get<any[]>('closet_marketplace_settings?select=transactions_enabled,payment_provider,shipping_provider,protection_window_days,withdrawal_window_days,seller_response_hours&id=eq.true&limit=1');return rows[0]||{transactions_enabled:false,payment_provider:'mercadopago',shipping_provider:'manual_adapter',protection_window_days:30,withdrawal_window_days:7,seller_response_hours:48}}
export async function loadPublicReputations(sellerIds:string[]){if(!sellerIds.length)return[];return get<any[]>(`closet_seller_reputation?select=*&seller_id=in.(${sellerIds.join(',')})&visible=eq.true`)}
export async function loadProductReviews(productId:string){return get<any[]>(`closet_reviews?select=id,overall_rating,quality_rating,fit,color_matches,material_matches,comment,verified_purchase,created_at&product_id=eq.${encodeURIComponent(productId)}&status=eq.published&order=created_at.desc&limit=100`)}
