'use client';

import type { ClosetSession } from './supabase';

const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');
const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';

function configured(){return Boolean(url&&anon)}
function requireConfigured(){if(!configured())throw new Error('Marketplace não configurado no deploy.')}
function headers(token?:string,extra:Record<string,string>={}){return {apikey:anon,Authorization:`Bearer ${token||anon}`,...extra}}
async function readJson(r:Response){const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error_description||d?.error||`Marketplace ${r.status}`);return d}
async function authed(session:ClosetSession,path:string,init:RequestInit={}){requireConfigured();return fetch(`${url}${path}`,{...init,headers:{...headers(session.access_token),...(init.headers||{})}})}
async function rpc<T>(session:ClosetSession,name:string,payload:Record<string,any>={}):Promise<T>{return readJson(await authed(session,`/rest/v1/rpc/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}))}
async function get<T>(session:ClosetSession,path:string):Promise<T>{return readJson(await authed(session,`/rest/v1/${path}`))}
async function post<T>(session:ClosetSession,path:string,payload:any):Promise<T>{return readJson(await authed(session,`/rest/v1/${path}`,{method:'POST',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify(payload)}))}
async function patch<T>(session:ClosetSession,path:string,payload:any):Promise<T>{return readJson(await authed(session,`/rest/v1/${path}`,{method:'PATCH',headers:{'Content-Type':'application/json','Prefer':'return=representation'},body:JSON.stringify(payload)}))}

export type SellerStatus='draft'|'verification_pending'|'under_review'|'approved'|'active'|'restricted'|'suspended'|'rejected'|'closed';
export type Seller={id:string;owner_user_id:string;display_name:string;legal_name?:string|null;entity_type:'individual'|'company';status:SellerStatus;verification_level:string;risk_status:string;country_code:string;metadata?:Record<string,any>;created_at:string;updated_at:string};
export type SellerVerification={id:string;seller_id:string;verification_type:string;provider?:string|null;provider_reference?:string|null;status:string;reason?:string|null;submitted_at?:string|null;verified_at?:string|null;expires_at?:string|null;metadata?:Record<string,any>;created_at:string;updated_at:string};
export type Store={id:string;seller_id:string;name:string;slug:string;description?:string|null;logo_url?:string|null;cover_url?:string|null;support_email?:string|null;support_phone?:string|null;status:string;verified_identity:boolean;verified_company:boolean;official_brand:boolean;closet_partner:boolean;settings?:Record<string,any>;created_at:string;updated_at:string};
export type CommercePlan={id:string;code:string;name:string;default_commission_rate:number;monthly_fee:number;payout_hold_hours:number;active:boolean;metadata?:Record<string,any>};
export type CommercialTerms={id:string;seller_id:string;plan_id:string;custom_commission_rate?:number|null;starts_at:string;ends_at?:string|null;status:string;accepted_at?:string|null;contract_version?:string|null;metadata?:Record<string,any>;plan?:CommercePlan|null};
export type SellerProduct={id:string;store_id:string;seller_id:string;source_type:string;external_id?:string|null;name:string;slug?:string|null;description?:string|null;brand?:string|null;category:string;subcategory?:string|null;gender_profile?:string|null;style_tags:string[];tags:string[];thermal_level?:number|null;weather_protection:Record<string,any>;status:string;moderation_notes?:string|null;created_at:string;updated_at:string};
export type Order={id:string;order_number:number;buyer_user_id:string;seller_id:string;store_id:string;status:string;currency:string;products_amount:number;shipping_amount:number;discount_amount:number;total_amount:number;commission_rate:number;commission_amount:number;processing_fee_amount:number;seller_net_amount:number;platform_net_amount:number;placed_at?:string|null;paid_at?:string|null;delivered_at?:string|null;completed_at?:string|null;created_at:string};
export type Dispute={id:string;order_id:string;buyer_user_id:string;seller_id:string;reason_code:string;status:string;buyer_statement?:string|null;seller_statement?:string|null;seller_response_due_at?:string|null;payout_hold:boolean;resolution_type?:string|null;resolution_amount?:number|null;opened_at:string;decided_at?:string|null;created_at:string};
export type Reputation={seller_id:string;trust_score?:number|null;public_level:string;completed_orders:number;on_time_shipment_rate?:number|null;seller_cancel_rate?:number|null;seller_fault_dispute_rate?:number|null;verified_review_score?:number|null;response_rate?:number|null;complaint_free_rate?:number|null;visible:boolean;calculated_at?:string|null};

export async function createSellerApplication(session:ClosetSession,displayName:string,entityType:'individual'|'company'){return rpc<string>(session,'closet_create_seller_application',{p_display_name:displayName,p_entity_type:entityType})}
export async function submitSellerApplication(session:ClosetSession,sellerId:string){return rpc<Seller>(session,'closet_submit_seller_application',{target_seller:sellerId})}
export async function submitStoreForReview(session:ClosetSession,storeId:string){return rpc<Store>(session,'closet_submit_store_for_review',{target_store:storeId})}
export async function submitProductForReview(session:ClosetSession,productId:string){return rpc<SellerProduct>(session,'closet_submit_product_for_review',{target_product:productId})}

export async function loadSeller(session:ClosetSession):Promise<Seller|null>{const rows=await get<Seller[]>(session,`closet_sellers?select=*&owner_user_id=eq.${encodeURIComponent(session.user.id)}&limit=1`);return rows[0]||null}
export async function updateSellerProfile(session:ClosetSession,sellerId:string,input:Partial<Pick<Seller,'display_name'|'legal_name'|'entity_type'|'country_code'|'metadata'>>){const rows=await patch<Seller[]>(session,`closet_sellers?id=eq.${encodeURIComponent(sellerId)}`,{...input,updated_at:new Date().toISOString()});return rows[0]||null}
export async function loadSellerVerifications(session:ClosetSession,sellerId:string){return get<SellerVerification[]>(session,`closet_seller_verifications?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&order=created_at.asc`)}
export async function loadSellerStores(session:ClosetSession,sellerId:string){return get<Store[]>(session,`closet_stores?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&order=created_at.asc`)}
export async function createStore(session:ClosetSession,sellerId:string,input:{name:string;slug:string;description?:string;support_email?:string;support_phone?:string}){const rows=await post<Store[]>(session,'closet_stores',{seller_id:sellerId,name:input.name,slug:input.slug,description:input.description||null,support_email:input.support_email||null,support_phone:input.support_phone||null,settings:{}});return rows[0]}
export async function updateStore(session:ClosetSession,storeId:string,input:Partial<Pick<Store,'name'|'slug'|'description'|'logo_url'|'cover_url'|'support_email'|'support_phone'|'settings'>>){const rows=await patch<Store[]>(session,`closet_stores?id=eq.${encodeURIComponent(storeId)}`,{...input,updated_at:new Date().toISOString()});return rows[0]||null}
export async function loadCommercialTerms(session:ClosetSession,sellerId:string){const select='*,plan:closet_commerce_plans(*)';return get<CommercialTerms[]>(session,`closet_seller_commercial_terms?select=${encodeURIComponent(select)}&seller_id=eq.${encodeURIComponent(sellerId)}&order=starts_at.desc`)}
export async function loadSellerProducts(session:ClosetSession,sellerId:string){return get<SellerProduct[]>(session,`closet_products?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&order=created_at.desc&limit=300`)}
export async function createSellerProduct(session:ClosetSession,input:{store_id:string;seller_id:string;name:string;category:string;subcategory?:string;description?:string;brand?:string;gender_profile?:string;tags?:string[];style_tags?:string[];thermal_level?:number|null;weather_protection?:Record<string,any>;external_id?:string}){const rows=await post<SellerProduct[]>(session,'closet_products',{store_id:input.store_id,seller_id:input.seller_id,source_type:'seller',external_id:input.external_id||null,name:input.name,description:input.description||null,brand:input.brand||null,category:input.category,subcategory:input.subcategory||null,gender_profile:input.gender_profile||null,tags:input.tags||[],style_tags:input.style_tags||[],thermal_level:input.thermal_level??null,weather_protection:input.weather_protection||{}});return rows[0]}
export async function updateSellerProduct(session:ClosetSession,productId:string,input:Partial<Pick<SellerProduct,'name'|'slug'|'description'|'brand'|'category'|'subcategory'|'gender_profile'|'style_tags'|'tags'|'thermal_level'|'weather_protection'|'external_id'>>){const rows=await patch<SellerProduct[]>(session,`closet_products?id=eq.${encodeURIComponent(productId)}`,{...input,updated_at:new Date().toISOString()});return rows[0]||null}
export async function createVariant(session:ClosetSession,productId:string,input:{sku?:string;title?:string;color?:string;size?:string;material?:string;price:number;compare_at_price?:number|null;weight_grams?:number|null}){const rows=await post<any[]>(session,'closet_product_variants',{product_id:productId,sku:input.sku||null,title:input.title||null,color:input.color||null,size:input.size||null,material:input.material||null,price:input.price,compare_at_price:input.compare_at_price??null,currency:'BRL',weight_grams:input.weight_grams??null,status:'active'});return rows[0]}
export async function setInventory(session:ClosetSession,variantId:string,quantity:number){return post<any[]>(session,'closet_product_inventory?on_conflict=variant_id',{variant_id:variantId,quantity_on_hand:Math.max(0,Math.floor(quantity)),quantity_reserved:0,allow_backorder:false})}
export async function addProductMedia(session:ClosetSession,productId:string,urlValue:string,position=0){const rows=await post<any[]>(session,'closet_product_media',{product_id:productId,media_type:'image',url:urlValue,position});return rows[0]}
export async function loadSellerOrders(session:ClosetSession,sellerId:string){return get<Order[]>(session,`closet_orders?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&order=created_at.desc&limit=200`)}
export async function loadSellerDisputes(session:ClosetSession,sellerId:string){return get<Dispute[]>(session,`closet_disputes?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&order=created_at.desc&limit=200`)}
export async function loadSellerReputation(session:ClosetSession,sellerId:string):Promise<Reputation|null>{const rows=await get<Reputation[]>(session,`closet_seller_reputation?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&limit=1`);return rows[0]||null}

export async function loadSellerWorkspace(session:ClosetSession){const seller=await loadSeller(session);if(!seller)return {seller:null,stores:[],verifications:[],terms:[],products:[],orders:[],disputes:[],reputation:null};const [stores,verifications,terms,products,orders,disputes,reputation]=await Promise.all([loadSellerStores(session,seller.id),loadSellerVerifications(session,seller.id),loadCommercialTerms(session,seller.id),loadSellerProducts(session,seller.id),loadSellerOrders(session,seller.id),loadSellerDisputes(session,seller.id),loadSellerReputation(session,seller.id)]);return {seller,stores,verifications,terms,products,orders,disputes,reputation}}
