'use client';

import type {ClosetSession} from './supabase';
const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
function h(token:string,extra:Record<string,string>={}){return{apikey:anon,Authorization:`Bearer ${token}`,...extra}}async function read(r:Response){const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||`Marketplace ${r.status}`);return d}async function get<T>(s:ClosetSession,path:string):Promise<T>{return read(await fetch(`${url}/rest/v1/${path}`,{headers:h(s.access_token)}))}async function rpc<T>(s:ClosetSession,name:string,p:any):Promise<T>{return read(await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:h(s.access_token,{'Content-Type':'application/json'}),body:JSON.stringify(p)}))}
export type BuyerOrder={id:string;order_number:number;status:string;store_id:string;seller_id:string;products_amount:number;shipping_amount:number;discount_amount:number;total_amount:number;created_at:string;paid_at?:string|null;delivered_at?:string|null;completed_at?:string|null;store?:{id:string;name:string;slug:string}|null};
export type ShippingQuote={service_id:string;name:string;carrier:string;price:number;delivery_days:number;packages:any[]};
export async function quoteMarketplaceShipping(s:ClosetSession,input:{variantId:string;quantity?:number;postalCode:string}){return read(await fetch('/api/closet/shipping/quote',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({variant_id:input.variantId,quantity:input.quantity||1,postal_code:input.postalCode})})) as Promise<{ok:boolean;quotes:ShippingQuote[]}>}
export async function loadBuyerOrders(s:ClosetSession){const select='*,store:closet_stores(id,name,slug)';return get<BuyerOrder[]>(s,`closet_orders?select=${encodeURIComponent(select)}&buyer_user_id=eq.${encodeURIComponent(s.user.id)}&order=created_at.desc&limit=200`)}
export async function loadBuyerOrderDetail(s:ClosetSession,id:string){const orders=await get<any[]>(s,`closet_orders?select=*&id=eq.${encodeURIComponent(id)}&buyer_user_id=eq.${encodeURIComponent(s.user.id)}&limit=1`),order=orders[0];if(!order)return null;const [items,shipments,disputes,returns,reviews,refunds]=await Promise.all([get<any[]>(s,`closet_order_items?select=*&order_id=eq.${encodeURIComponent(id)}`),get<any[]>(s,`closet_shipments?select=*&order_id=eq.${encodeURIComponent(id)}&order=created_at.desc`),get<any[]>(s,`closet_disputes?select=*&order_id=eq.${encodeURIComponent(id)}&order=created_at.desc`),get<any[]>(s,`closet_returns?select=*&order_id=eq.${encodeURIComponent(id)}&order=requested_at.desc`),get<any[]>(s,`closet_reviews?select=*&order_id=eq.${encodeURIComponent(id)}&buyer_user_id=eq.${encodeURIComponent(s.user.id)}`).catch(()=>[]),get<any[]>(s,`closet_refunds?select=*&order_id=eq.${encodeURIComponent(id)}&order=created_at.desc`).catch(()=>[])]);const ids=items.map(x=>x.id);const snapshots=ids.length?await get<any[]>(s,`closet_order_item_snapshots?select=*&order_item_id=in.(${ids.join(',')})`):[];return{order,items,shipments,disputes,returns,snapshots,reviews,refunds}}
export async function openDispute(s:ClosetSession,orderId:string,reason:string,statement:string){return rpc<any>(s,'closet_open_dispute',{p_order_id:orderId,p_reason_code:reason,p_statement:statement})}
export async function addDisputeMessage(s:ClosetSession,disputeId:string,message:string){return rpc<any>(s,'closet_add_dispute_message',{p_dispute_id:disputeId,p_message:message})}
export async function requestReturn(s:ClosetSession,orderId:string,reason:string){return rpc<any>(s,'closet_request_return',{p_order_id:orderId,p_reason:reason})}
export async function createVerifiedReview(s:ClosetSession,input:{orderItemId:string;overall:number;quality?:number|null;fit?:string|null;colorMatches?:boolean|null;materialMatches?:boolean|null;comment?:string}){return rpc<any>(s,'closet_create_verified_review',{p_order_item_id:input.orderItemId,p_overall:input.overall,p_quality:input.quality??null,p_fit:input.fit??null,p_color_matches:input.colorMatches??null,p_material_matches:input.materialMatches??null,p_comment:input.comment||''})}
export async function loadDisputeThread(s:ClosetSession,disputeId:string){const [cases,messages,evidence,decisions]=await Promise.all([get<any[]>(s,`closet_disputes?select=*&id=eq.${encodeURIComponent(disputeId)}&limit=1`),get<any[]>(s,`closet_dispute_messages?select=*&dispute_id=eq.${encodeURIComponent(disputeId)}&order=created_at.asc`),get<any[]>(s,`closet_dispute_evidence?select=*&dispute_id=eq.${encodeURIComponent(disputeId)}&order=created_at.asc`),get<any[]>(s,`closet_dispute_decisions?select=*&dispute_id=eq.${encodeURIComponent(disputeId)}&order=created_at.asc`)]);return{dispute:cases[0]||null,messages,evidence,decisions}}
export async function uploadDisputeEvidence(s:ClosetSession,disputeId:string,file:File,caption=''){const form=new FormData();form.append('dispute_id',disputeId);form.append('caption',caption);form.append('file',file);return read(await fetch('/api/closet/disputes/evidence',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`},body:form}))}
export async function getEvidenceSignedUrl(s:ClosetSession,evidenceId:string){const r=await fetch(`${url}/functions/v1/closet-evidence-url`,{method:'POST',headers:h(s.access_token,{'Content-Type':'application/json'}),body:JSON.stringify({evidence_id:evidenceId})});const d=await read(r);return d?.signed_url||null}
