'use client';
import type {ClosetSession} from './supabase';
export type MarketplaceProduct={id:string;partner_id:string;name:string;category:string;subcategory?:string|null;price?:number|null;currency?:string|null;image_url?:string|null;product_url:string;tags?:string[];thermal_level?:number|null;weather_protection?:Record<string,any>|null;style_tags?:string[];partner?:{id:string;name:string;credit_reward?:number|null}|null};
const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
function headers(token?:string,extra:Record<string,string>={}){return {apikey:anon,...(token?{Authorization:`Bearer ${token}`}:{Authorization:`Bearer ${anon}`}),...extra}}
async function json(r:Response){const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||`Supabase ${r.status}`);return d}
export async function loadMarketplaceProducts():Promise<MarketplaceProduct[]>{const select='id,partner_id,name,category,subcategory,price,currency,image_url,product_url,tags,thermal_level,weather_protection,style_tags,partner:closet_partners(id,name,credit_reward)';try{return await json(await fetch(`${url}/rest/v1/closet_partner_products?active=eq.true&select=${encodeURIComponent(select)}&order=created_at.desc&limit=200`,{headers:headers()}))}catch{return[]}}
export function rankMarketplaceProducts(products:MarketplaceProduct[],category:string,query:string){const terms=`${category} ${query}`.toLowerCase().split(/\s+/).filter(x=>x.length>2);return products.map(p=>{const hay=`${p.name} ${p.category} ${p.subcategory||''} ${(p.tags||[]).join(' ')} ${(p.style_tags||[]).join(' ')}`.toLowerCase();let score=terms.reduce((n,t)=>n+(hay.includes(t)?2:0),0);if(p.category.toLowerCase()===category.toLowerCase())score+=8;return{...p,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
export async function trackMarketplaceClick(session:ClosetSession|null,input:{product:MarketplaceProduct;trip?:string;moment?:string;category:string;query:string}){if(!session)return;try{await fetch(`${url}/rest/v1/closet_marketplace_events`,{method:'POST',headers:headers(session.access_token,{'Content-Type':'application/json'}),body:JSON.stringify({user_id:session.user.id,partner_id:input.product.partner_id,product_id:input.product.id,trip_id:input.trip||null,moment_id:input.moment||null,event_type:'click',source:'stylist_gap',category:input.category,query:input.query,metadata:{credit_reward:input.product.partner?.credit_reward||0}})})}catch{}}
