'use client';
import type {ClosetSession} from './supabase';
const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
function h(token:string,extra:Record<string,string>={}){return{apikey:anon,Authorization:`Bearer ${token}`,...extra}}
async function read(r:Response){const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error||`Marketplace ${r.status}`);return d}
async function get<T>(s:ClosetSession,path:string):Promise<T>{return read(await fetch(`${url}/rest/v1/${path}`,{headers:h(s.access_token),cache:'no-store'}))}
async function post<T>(s:ClosetSession,path:string,payload:any):Promise<T>{return read(await fetch(`${url}/rest/v1/${path}`,{method:'POST',headers:h(s.access_token,{'Content-Type':'application/json','Prefer':'return=representation'}),body:JSON.stringify(payload)}))}
async function patch<T>(s:ClosetSession,path:string,payload:any):Promise<T>{return read(await fetch(`${url}/rest/v1/${path}`,{method:'PATCH',headers:h(s.access_token,{'Content-Type':'application/json','Prefer':'return=representation'}),body:JSON.stringify(payload)}))}
export type SellerAddress={id:string;seller_id:string;address_type:'business'|'return'|'warehouse';postal_code:string;street:string;number?:string|null;complement?:string|null;district?:string|null;city:string;state:string;country_code:string;verified:boolean;created_at:string;updated_at:string};
export async function loadSellerAddresses(s:ClosetSession,sellerId:string){return get<SellerAddress[]>(s,`closet_seller_addresses?select=*&seller_id=eq.${encodeURIComponent(sellerId)}&order=address_type.asc,created_at.asc`)}
export async function saveSellerAddress(s:ClosetSession,sellerId:string,input:Omit<SellerAddress,'id'|'seller_id'|'verified'|'created_at'|'updated_at'>,id?:string){const payload={seller_id:sellerId,...input,country_code:input.country_code||'BR',updated_at:new Date().toISOString()};if(id){const rows=await patch<SellerAddress[]>(s,`closet_seller_addresses?id=eq.${encodeURIComponent(id)}&seller_id=eq.${encodeURIComponent(sellerId)}`,payload);return rows[0]||null}const rows=await post<SellerAddress[]>(s,'closet_seller_addresses',payload);return rows[0]||null}
export async function loadSellerCatalogDetail(s:ClosetSession,sellerId:string){const select='*,variants:closet_product_variants(*,inventory:closet_product_inventory(*)),media:closet_product_media(*)';return get<any[]>(s,`closet_products?select=${encodeURIComponent(select)}&seller_id=eq.${encodeURIComponent(sellerId)}&order=updated_at.desc&limit=300`)}
export async function updateVariant(s:ClosetSession,variantId:string,input:{sku?:string|null;title?:string|null;color?:string|null;size?:string|null;material?:string|null;price?:number;compare_at_price?:number|null;weight_grams?:number|null;status?:string}){const rows=await patch<any[]>(s,`closet_product_variants?id=eq.${encodeURIComponent(variantId)}`,{...input,updated_at:new Date().toISOString()});return rows[0]||null}
export async function setVariantInventory(s:ClosetSession,variantId:string,quantity:number,allowBackorder=false){const rows=await post<any[]>(s,'closet_product_inventory?on_conflict=variant_id',{variant_id:variantId,quantity_on_hand:Math.max(0,Math.floor(quantity)),quantity_reserved:0,allow_backorder:Boolean(allowBackorder),updated_at:new Date().toISOString()});return rows[0]||null}
export async function loadSellerOrderDetail(s:ClosetSession,orderId:string){const [orders,items,shipments]=await Promise.all([get<any[]>(s,`closet_orders?select=*&id=eq.${encodeURIComponent(orderId)}&limit=1`),get<any[]>(s,`closet_order_items?select=*&order_id=eq.${encodeURIComponent(orderId)}`),get<any[]>(s,`closet_shipments?select=*&order_id=eq.${encodeURIComponent(orderId)}&order=created_at.desc`)]);const ids=(shipments||[]).map(x=>x.id);const events=ids.length?await get<any[]>(s,`closet_shipment_events?select=*&shipment_id=in.(${ids.join(',')})&order=occurred_at.desc`).catch(()=>[]):[];return{order:orders[0]||null,items,shipments,events}}
export async function startMercadoPagoConnection(s:ClosetSession,sellerId:string){return read(await fetch('/api/closet/mercadopago/start',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({seller_id:sellerId})}))}
export async function loadPaymentConnection(s:ClosetSession,sellerId:string){const rows=await get<any[]>(s,`closet_seller_payment_connections?select=seller_id,provider,provider_user_id,status,connected_at,expires_at,payouts_enabled,transfers_enabled,requirements_due&seller_id=eq.${encodeURIComponent(sellerId)}&provider=eq.mercadopago&limit=1`);return rows[0]||null}
