'use client';

import type {StylistPiece,StyleProfile} from './lookEngine';
import {hasSemanticBase,isOuterwear} from './lookSemantics';

export type StylistContextLike={occasion?:string;detail?:string;period?:string;colors?:string[];paletteMode?:string;work_profile?:{dress_code?:string}|null;weather?:Record<string,any>|null};

export function normalizeStyleText(v:string){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim()}
export function currentStylistContext():StylistContextLike{if(typeof window==='undefined')return{};try{return JSON.parse(sessionStorage.getItem('closet_stylist_context')||'{}')||{}}catch{return{}}}
function txt(p:StylistPiece){return normalizeStyleText(`${p.name||''} ${p.meta||''}`)}
export function detectedColor(p:StylistPiece){const t=txt(p),colors=['off white','azul marinho','verde oliva','verde escuro','azul claro','cinza claro','rosa claro','terracota','caramelo','grafite','preto','branco','bege','creme','cinza','marrom','vinho','vermelho','laranja','amarelo','verde','azul','lilas','roxo','rosa'];return colors.find(c=>t.includes(c))||''}
function garmentType(p:StylistPiece){const t=txt(p);if(/camisa social|dress shirt/.test(t))return'camisa-social';if(/camiseta|t shirt|tee\b/.test(t))return'camiseta';if(/camisa polo|\bpolo\b/.test(t))return'polo';if(/\bcamisa\b/.test(t))return'camisa';if(/blazer/.test(t))return'blazer';if(/jaqueta/.test(t))return'jaqueta';if(/sobretudo|casaco|parka|puffer/.test(t))return'casaco';if(/sueter|tricot|trico/.test(t))return'sueter';if(/moletom|hoodie/.test(t))return'moletom';if(/jogger|calca.*moletom/.test(t))return'jogger';if(/alfaiataria/.test(t))return'alfaiataria';if(/chino/.test(t))return'chino';if(/jeans|denim/.test(t))return'jeans';if(/cargo/.test(t))return'cargo';if(/short|bermuda/.test(t))return'short';if(/vestido/.test(t))return'vestido';if(/mocassim|loafer/.test(t))return'mocassim';if(/oxford|derby|sapato social/.test(t))return'sapato-social';if(/sapatenis/.test(t))return'sapatenis';if(/running|corrida|treino|performance/.test(t)&&/tenis|sneaker/.test(t))return'tenis-running';if(/tenis|sneaker/.test(t))return'tenis';if(/bota/.test(t))return'bota';if(/sandalia/.test(t))return'sandalia';return'outro'}
function formality(p:StylistPiece){const t=garmentType(p);if(['camisa-social','blazer','alfaiataria','mocassim','sapato-social'].includes(t))return 3;if(['camisa','polo','sueter','chino','bota','sapatenis','vestido'].includes(t))return 2;if(['camiseta','jeans','cargo','jaqueta','tenis'].includes(t))return 1;if(['moletom','jogger','short','sandalia','tenis-running'].includes(t))return 0;return 1.5}
function volume(p:StylistPiece){const t=txt(p);if(/oversized|wide|ampla|amplo|larga|largo|baggy|relaxed|boxy/.test(t))return 2;if(/slim|skinny|ajustad|fitted/.test(t))return 0;return 1}
function patterned(p:StylistPiece){return /estampa|estampado|xadrez|listr|floral|poa|animal print/.test(txt(p))}
function allowedForOccasion(p:StylistPiece,occasion:string){const pref:any=p.stylistPreference||{};if(pref.frequency==='never')return false;const only=Array.isArray(pref.only_occasions)?pref.only_occasions.map((x:any)=>normalizeStyleText(String(x))):[];return !only.length||only.includes(normalizeStyleText(occasion))}
function semanticRole(p:StylistPiece){if(p.category==='Blusas')return isOuterwear(p)?'outerwear':'base';if(p.category==='Calças')return'bottom';if(p.category==='Calçados')return'shoes';if(p.category==='Vestidos')return'dress';return'accessory'}

function targetFormality(occasion:string,ctx:StylistContextLike){const o=normalizeStyleText(occasion),d=normalizeStyleText(ctx.detail||''),work=normalizeStyleText(ctx.work_profile?.dress_code||'');let target=1.4;if(['trabalho','igreja'].includes(o))target=2;if(['evento','casamento','formatura'].includes(o))target=2.7;if(['festa','encontro','jantar'].includes(o))target=1.9;if(['faculdade','escola','aula','passeio','sair','viagem'].includes(o))target=1.1;if(/formal|cerimonia|casamento|formatura|reuniao importante|evento profissional|ministrar|servir/.test(d))target=Math.max(target,2.5);if(/casual|dia normal|culto comum/.test(d))target=Math.min(target,1.6);if(work.includes('formal'))target=2.8;else if(work.includes('social casual'))target=2;else if(work.includes('casual'))target=1.3;return target}

function pairScore(a:StylistPiece,b:StylistPiece,occasion:string){const ta=garmentType(a),tb=garmentType(b),types=new Set([ta,tb]);let s=0;if(types.has('camisa-social')&&(types.has('jogger')||types.has('moletom')))s-=42;if(types.has('alfaiataria')&&types.has('tenis-running'))s-=36;if(types.has('blazer')&&types.has('tenis-running'))s-=34;if(types.has('sapato-social')&&(types.has('jogger')||types.has('moletom')||types.has('short')))s-=38;if(types.has('mocassim')&&(types.has('chino')||types.has('alfaiataria')||types.has('jeans')))s+=8;if(types.has('camisa-social')&&(types.has('alfaiataria')||types.has('chino')))s+=9;if((types.has('camisa')||types.has('polo'))&&(types.has('chino')||types.has('jeans')))s+=6;if(types.has('camiseta')&&(types.has('jeans')||types.has('cargo')||types.has('chino')))s+=5;if(types.has('tenis')&&(types.has('jeans')||types.has('chino')||types.has('cargo')))s+=5;const formalContext=/trabalho|evento|igreja|casamento|formatura/.test(normalizeStyleText(occasion));if(formalContext&&types.has('tenis-running'))s-=18;return s}

function paletteCompositionScore(items:StylistPiece[],ctx:StylistContextLike){const wanted=(ctx.colors||[]).map(normalizeStyleText).filter(Boolean);if(!wanted.length||ctx.paletteMode==='auto')return 0;const main=items.filter(p=>['Blusas','Calças','Calçados','Vestidos'].includes(p.category));if(!main.length)return 0;const colors=main.map(detectedColor).filter(Boolean);const represented=new Set(colors.filter(c=>wanted.includes(c)));let s=represented.size*15;const target=Math.min(wanted.length,main.length);s-=Math.max(0,target-represented.size)*9;if(ctx.paletteMode==='strict'||ctx.paletteMode==='selected'){for(const c of colors)if(c&&!wanted.includes(c))s-=ctx.paletteMode==='strict'?50:12}const counts=new Map<string,number>();for(const c of colors)if(c)counts.set(c,(counts.get(c)||0)+1);const max=Math.max(0,...counts.values());if(wanted.length>=3&&main.length>=3){if(represented.size===1)s-=28;else if(represented.size===2)s-=7;if(max===main.length)s-=18}return s}

function silhouetteScore(items:StylistPiece[]){const base=items.find(p=>semanticRole(p)==='base'),bottom=items.find(p=>semanticRole(p)==='bottom'),outer=items.find(p=>semanticRole(p)==='outerwear');let s=0;if(base&&bottom){const a=volume(base),b=volume(bottom);if(a===2&&b===2)s-=13;else if((a===2&&b<=1)||(b===2&&a<=1))s+=4}if(outer&&base&&volume(outer)===2&&volume(base)===2)s-=9;const patterns=items.filter(patterned).length;if(patterns>1)s-=(patterns-1)*9;return s}

function climateCompositionScore(items:StylistPiece[],profile:StyleProfile,ctx:StylistContextLike){const w:any=ctx.weather||profile.weather_context||{},max=Number(w.feelsMax??w.tempMax),min=Number(w.feelsMin??w.tempMin),sens=Number((profile as any).thermal_sensitivity||3);if(!Number.isFinite(max)&&!Number.isFinite(min))return 0;let s=0;const outer=items.find(p=>semanticRole(p)==='outerwear');if(outer&&Number.isFinite(max)){const type=garmentType(outer);const heavy=['casaco','moletom','sueter'].includes(type);if(max>=29)s-=heavy?30:18;else if(max>=26)s-=heavy?18:8;else if(max<=20)s+=heavy?9:6;if(sens>=4&&max>=25)s-=7;if(sens<=2&&max<=21)s+=5}if(!outer&&Number.isFinite(min)&&min<=16)s-=10;return s}

function formalityCoherenceScore(items:StylistPiece[],occasion:string,ctx:StylistContextLike){const main=items.filter(p=>['Blusas','Calças','Calçados','Vestidos'].includes(p.category));if(!main.length)return 0;const vals=main.map(formality),target=targetFormality(occasion,ctx);let s=0;const avg=vals.reduce((a,b)=>a+b,0)/vals.length;s-=Math.abs(avg-target)*8;const spread=Math.max(...vals)-Math.min(...vals);if(spread>2)s-=18;else if(spread>1.5)s-=7;return s}

export function scoreLookComposition(items:StylistPiece[],occasion:string,profile:StyleProfile={},ctx:StylistContextLike=currentStylistContext()){
 let s=0;if(!items.length)return-999;const dress=items.some(p=>p.category==='Vestidos'),bottom=items.some(p=>p.category==='Calças'),shoes=items.some(p=>p.category==='Calçados'),base=hasSemanticBase(items);if(shoes&&(dress||(base&&bottom)))s+=65;else s-=90;for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++)s+=pairScore(items[i],items[j],occasion);s+=paletteCompositionScore(items,ctx);s+=silhouetteScore(items);s+=climateCompositionScore(items,profile,ctx);s+=formalityCoherenceScore(items,occasion,ctx);return s
}

export function rankSlotAlternatives(all:StylistPiece[],current:StylistPiece[],target:StylistPiece,occasion:string,profile:StyleProfile={},options:{paletteOnly?:boolean}={}){const ctx=currentStylistContext(),role=semanticRole(target),wanted=(ctx.colors||[]).map(normalizeStyleText).filter(Boolean);return all.filter(p=>String(p.id)!==String(target.id)&&allowedForOccasion(p,occasion)&&semanticRole(p)===role).filter(p=>{if(!options.paletteOnly||!wanted.length)return true;const c=detectedColor(p);return Boolean(c&&wanted.includes(c))}).map(p=>{const candidate=current.map(x=>String(x.id)===String(target.id)?p:x);return{piece:p,score:scoreLookComposition(candidate,occasion,profile,ctx)}}).sort((a,b)=>b.score-a.score).map(x=>x.piece)
}
