'use client';
import type {ClosetSession} from './supabase';
import {updateMoment,type Trip,type TripMoment} from './travelStore';
export type TravelWeather={source:'forecast'|'historical'|'historical_typical';sourceLabel:string;tempMin:number|null;tempMax:number|null;rainChance:number|null;weatherCode:number|null;windMax:number|null;thermalNeed:number;note:string;location:{name:string;admin1?:string|null;country?:string|null;latitude:number;longitude:number;timezone?:string|null}};
export type WeatherChange={meaningful:boolean;colder:boolean;warmer:boolean;rainIncreased:boolean;thermalChanged:boolean;summary:string;deltaMin:number;deltaMax:number;deltaRain:number};
export async function fetchTravelWeather(trip:Trip,moment:TripMoment):Promise<TravelWeather>{if(!moment.starts_at)throw new Error('Defina a data deste momento para consultar o clima.');const q=new URLSearchParams({destination:trip.destination,place:moment.location_name||trip.destination,date:new Date(moment.starts_at).toISOString().slice(0,10)}),r=await fetch(`/api/closet/travel-weather?${q.toString()}`),d=await r.json();if(!r.ok||!d?.ok)throw new Error(d?.message||'Não consegui consultar o clima.');return d as TravelWeather}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0}
function compare(moment:TripMoment,w:TravelWeather):WeatherChange|null{const had=moment.expected_temp_min!=null||moment.expected_temp_max!=null||moment.rain_probability!=null;if(!had)return null;const dMin=num(w.tempMin)-num(moment.expected_temp_min),dMax=num(w.tempMax)-num(moment.expected_temp_max),dRain=num(w.rainChance)-num(moment.rain_probability),oldNeed=num(moment.thermal_need),newNeed=num(w.thermalNeed),colder=dMin<=-3||dMax<=-3,warmer=dMin>=4||dMax>=4,rainIncreased=dRain>=25,thermalChanged=oldNeed>0&&newNeed!==oldNeed,meaningful=colder||warmer||rainIncreased||thermalChanged;const bits:string[]=[];if(colder)bits.push(`temperatura caiu ${Math.max(Math.abs(Math.round(dMin)),Math.abs(Math.round(dMax)))}°C`);else if(warmer)bits.push(`temperatura subiu ${Math.max(Math.abs(Math.round(dMin)),Math.abs(Math.round(dMax)))}°C`);if(rainIncreased)bits.push(`chance de chuva aumentou ${Math.round(dRain)} pontos`);if(thermalChanged&&newNeed>oldNeed)bits.push('o look pode precisar de mais proteção');else if(thermalChanged&&newNeed<oldNeed)bits.push('o clima ficou mais leve');return{meaningful,colder,warmer,rainIncreased,thermalChanged,summary:bits.join(' · '),deltaMin:dMin,deltaMax:dMax,deltaRain:dRain}}
export async function refreshMomentWeather(session:ClosetSession,trip:Trip,moment:TripMoment){const w=await fetchTravelWeather(trip,moment),change=compare(moment,w),previous={temp_min:moment.expected_temp_min??null,temp_max:moment.expected_temp_max??null,rain_probability:moment.rain_probability??null,thermal_need:moment.thermal_need??null,weather_source:moment.weather_source??null,checked_at:moment.metadata?.weather_checked_at??null};const metadata={...(moment.metadata||{}),weather_note:w.note,weather_checked_at:new Date().toISOString(),weather_code:w.weatherCode,wind_max:w.windMax,weather_location:w.location,weather_context_version:2,weather_previous:previous,weather_change:change&&change.meaningful?change:null,weather_review_needed:Boolean(change?.meaningful&&(change.colder||change.rainIncreased||(change.thermalChanged&&w.thermalNeed>num(moment.thermal_need))))};const updated=await updateMoment(session,moment.id,{expected_temp_min:w.tempMin,expected_temp_max:w.tempMax,rain_probability:w.rainChance,weather_source:w.sourceLabel,thermal_need:w.thermalNeed,metadata});return{moment:updated,weather:w,change}}
