'use client';
import type {ClosetSession} from './supabase';
export type Trip={id:string;user_id:string;name:string;destination:string;start_date:string;end_date:string;latitude?:number|null;longitude?:number|null;thermal_preference:number;packing_mode:'compact'|'balanced'|'variety';notes?:string|null;metadata?:Record<string,any>|null;created_at?:string};
export type TripMoment={id:string;trip_id:string;user_id:string;title:string;starts_at?:string|null;location_name?:string|null;activity_type?:string|null;environment?:'indoor'|'outdoor'|'mixed'|null;expected_temp_min?:number|null;expected_temp_max?:number|null;rain_probability?:number|null;thermal_need?:number|null;notes?:string|null;metadata?:Record<string,any>|null};
export type TripMomentItem={moment_id:string;item_id:string;user_id:string;locked:boolean;source:'manual'|'stylist';created_at?:string};
export type TripPackingItem={trip_id:string;item_id:string;user_id:string;packed:boolean;purchased_for_trip:boolean;created_at?:string};
const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
function headers(token:string,extra:Record<string,string>={}){return {apikey:anon,Authorization:`Bearer ${token}`,...extra}}
async function json(r:Response){const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.error||`Supabase ${r.status}`);return d}
export async function loadTrips(s:ClosetSession):Promise<Trip[]>{return json(await fetch(`${url}/rest/v1/closet_trips?user_id=eq.${s.user.id}&select=*&order=start_date.asc`,{headers:headers(s.access_token)}))}
export async function loadTrip(s:ClosetSession,id:string):Promise<Trip|null>{const rows=await json(await fetch(`${url}/rest/v1/closet_trips?id=eq.${encodeURIComponent(id)}&user_id=eq.${s.user.id}&select=*&limit=1`,{headers:headers(s.access_token)}));return rows?.[0]||null}
export async function createTrip(s:ClosetSession,input:{name:string;destination:string;start_date:string;end_date:string;thermal_preference:number;packing_mode:'compact'|'balanced'|'variety';notes?:string;metadata?:Record<string,any>}):Promise<Trip>{const rows=await json(await fetch(`${url}/rest/v1/closet_trips`,{method:'POST',headers:headers(s.access_token,{'Content-Type':'application/json','Prefer':'return=representation'}),body:JSON.stringify({user_id:s.user.id,...input})}));return rows[0]}
export async function updateTrip(s:ClosetSession,id:string,patch:Partial<Trip>):Promise<Trip>{const rows=await json(await fetch(`${url}/rest/v1/closet_trips?id=eq.${id}&user_id=eq.${s.user.id}`,{method:'PATCH',headers:headers(s.access_token,{'Content-Type':'application/json','Prefer':'return=representation'}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})}));return rows[0]}
export async function loadTripMoments(s:ClosetSession,tripId:string):Promise<TripMoment[]>{return json(await fetch(`${url}/rest/v1/closet_trip_moments?trip_id=eq.${tripId}&user_id=eq.${s.user.id}&select=*&order=starts_at.asc.nullslast,created_at.asc`,{headers:headers(s.access_token)}))}
export async function loadTripMoment(s:ClosetSession,id:string):Promise<TripMoment|null>{const rows=await json(await fetch(`${url}/rest/v1/closet_trip_moments?id=eq.${encodeURIComponent(id)}&user_id=eq.${s.user.id}&select=*&limit=1`,{headers:headers(s.access_token)}));return rows?.[0]||null}
export async function createMoment(s:ClosetSession,tripId:string,input:{title:string;starts_at?:string|null;location_name?:string|null;activity_type?:string|null;environment?:'indoor'|'outdoor'|'mixed'|null;notes?:string|null;metadata?:Record<string,any>}):Promise<TripMoment>{const rows=await json(await fetch(`${url}/rest/v1/closet_trip_moments`,{method:'POST',headers:headers(s.access_token,{'Content-Type':'application/json','Prefer':'return=representation'}),body:JSON.stringify({trip_id:tripId,user_id:s.user.id,...input})}));return rows[0]}
export async function updateMoment(s:ClosetSession,id:string,patch:Partial<TripMoment>):Promise<TripMoment>{const rows=await json(await fetch(`${url}/rest/v1/closet_trip_moments?id=eq.${id}&user_id=eq.${s.user.id}`,{method:'PATCH',headers:headers(s.access_token,{'Content-Type':'application/json','Prefer':'return=representation'}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})}));return rows[0]}
export async function deleteMoment(s:ClosetSession,id:string){await json(await fetch(`${url}/rest/v1/closet_trip_moments?id=eq.${id}&user_id=eq.${s.user.id}`,{method:'DELETE',headers:headers(s.access_token)}));}
export async function loadTripMomentItems(s:ClosetSession,tripId:string):Promise<TripMomentItem[]>{const moments=await loadTripMoments(s,tripId);if(!moments.length)return[];const ids=moments.map(m=>m.id).join(',');return json(await fetch(`${url}/rest/v1/closet_trip_moment_items?moment_id=in.(${encodeURIComponent(ids)})&user_id=eq.${s.user.id}&select=*&order=created_at.asc`,{headers:headers(s.access_token)}))}
export async function loadTripPacking(s:ClosetSession,tripId:string):Promise<TripPackingItem[]>{return json(await fetch(`${url}/rest/v1/closet_trip_packing?trip_id=eq.${encodeURIComponent(tripId)}&user_id=eq.${s.user.id}&select=*&order=created_at.asc`,{headers:headers(s.access_token)}))}
export async function setTripPackingState(s:ClosetSession,tripId:string,itemId:string,packed:boolean){await json(await fetch(`${url}/rest/v1/closet_trip_packing?trip_id=eq.${encodeURIComponent(tripId)}&item_id=eq.${encodeURIComponent(itemId)}&user_id=eq.${s.user.id}`,{method:'PATCH',headers:headers(s.access_token,{'Content-Type':'application/json'}),body:JSON.stringify({packed})}))}
export async function saveTripMomentLook(s:ClosetSession,momentId:string,itemIds:string[],source:'manual'|'stylist'='stylist',lockedItemId?:string|null){
 await json(await fetch(`${url}/rest/v1/closet_trip_moment_items?moment_id=eq.${encodeURIComponent(momentId)}&user_id=eq.${s.user.id}`,{method:'DELETE',headers:headers(s.access_token)}));
 if(!itemIds.length)return;
 const rows=itemIds.map(item_id=>({moment_id:momentId,item_id,user_id:s.user.id,locked:Boolean(lockedItemId&&String(lockedItemId)===String(item_id)),source}));
 await json(await fetch(`${url}/rest/v1/closet_trip_moment_items`,{method:'POST',headers:headers(s.access_token,{'Content-Type':'application/json'}),body:JSON.stringify(rows)}));
 const moment=await loadTripMoment(s,momentId);if(!moment)return;
 for(const item_id of itemIds){await fetch(`${url}/rest/v1/closet_trip_packing`,{method:'POST',headers:headers(s.access_token,{'Content-Type':'application/json','Prefer':'resolution=merge-duplicates'}),body:JSON.stringify({trip_id:moment.trip_id,item_id,user_id:s.user.id,packed:false,purchased_for_trip:false})})}
}
