'use client';

import {useEffect,useState} from 'react';
import lookStyles from './look.module.css';
import {restoreClosetSession,type ClosetSession} from './supabase';
import {loadAiWallet,type AiWallet} from './aiCredits';

type Piece={id:string|number;category:string;name:string;meta:string;image:string};
type AvatarModel={id:string;name:string;hint:string;glyph:string};
type Props={pieces:Piece[];models:AvatarModel[];avatarId:string;image:string;busy:boolean;error:string;onAvatarChange:(id:string)=>void;onGenerate:()=>void;onSwap:(piece:Piece)=>void;onRemix:()=>void;onResetModel:()=>void;onClose?:()=>void};

async function makeReference(items:Piece[]){const sources=await Promise.all(items.slice(0,7).map(p=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=p.image})));const c=document.createElement('canvas');c.width=1024;c.height=1024;const ctx=c.getContext('2d');if(!ctx)throw new Error('Não consegui preparar o look.');ctx.fillStyle='#f6f0e7';ctx.fillRect(0,0,1024,1024);const rows=Math.ceil(sources.length/2),cellH=1024/Math.max(1,rows);sources.forEach((img,i)=>{const col=i%2,row=Math.floor(i/2),cellW=512,pad=42,maxW=cellW-pad*2,maxH=cellH-pad*2,scale=Math.min(maxW/img.width,maxH/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,col*cellW+(cellW-w)/2,row*cellH+(cellH-h)/2,w,h)});return c.toDataURL('image/png')}

export default function TryOnStage({pieces,models,avatarId,image,busy,error,onAvatarChange,onSwap,onRemix,onResetModel,onClose}:Props){
 const [session,setSession]=useState<ClosetSession|null>(null),[wallet,setWallet]=useState<AiWallet|null>(null),[localImage,setLocalImage]=useState(''),[localBusy,setLocalBusy]=useState(false),[localError,setLocalError]=useState('');
 useEffect(()=>{(async()=>{const s=await restoreClosetSession();setSession(s);if(s)setWallet(await loadAiWallet(s))})()},[]);
 const selected=models.find(m=>m.id===avatarId)||models[0],result=localImage||image,isBusy=localBusy||busy,shownError=localError||error,open=Boolean(result)&&!isBusy,cost=3,balance=wallet?.balance??0;
 const close=()=>{if(onClose)onClose();else window.location.assign('/closet')};
 async function generate(){setLocalError('');if(!session){setLocalError('Entre na sua conta para usar o Closet AI.');return}if(balance<cost){setLocalError(`Você tem ${balance} crédito${balance===1?'':'s'}. Esta experiência precisa de ${cost}.`);return}setLocalBusy(true);setLocalImage('');try{const reference=await makeReference(pieces);const r=await fetch('/api/closet/try-on',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({image:reference,avatarId,items:pieces.map(p=>({name:p.name,category:p.category,meta:p.meta}))})});const data=await r.json();if(!r.ok||!data?.ok||!data?.image)throw new Error(data?.message||'Não consegui vestir este look.');setLocalImage(String(data.image));if(data?.credits?.balance!=null)setWallet(prev=>({balance:Number(data.credits.balance),lifetime_earned:prev?.lifetime_earned??0,lifetime_spent:(prev?.lifetime_spent??0)+cost,updated_at:new Date().toISOString()}));else setWallet(await loadAiWallet(session))}catch(e:any){setLocalError(String(e?.message||'Não consegui gerar esta visualização.'))}finally{setLocalBusy(false)}}
 function reset(){setLocalImage('');setLocalError('');onResetModel()}
 return <div className={lookStyles.lookExperience}>
  <header className={lookStyles.lookExperienceHeader}><div><small>SEU LOOK</small><strong>Provador</strong></div><button onClick={close} aria-label="Fechar provador">×</button></header>
  <div className={lookStyles.lookExperienceIntro}><span>CLOSET AI · 3 CRÉDITOS</span><h2>{open?'Seu look está pronto.':'Veja a combinação no provador.'}</h2><p>{isBusy?'Estou vestindo exatamente as peças escolhidas. A cortina abre assim que estiver pronto.':'A montagem normal do look é grátis. Só descontamos 3 créditos quando você pedir esta visualização realista.'}</p><small>{session?`Saldo: ${balance} crédito${balance===1?'':'s'}`:'Entre na sua conta para acessar seus créditos.'}</small></div>
  <div className={lookStyles.fittingRoomWrap}>
   <div className={`${lookStyles.fittingRoom} ${open?lookStyles.fittingRoomOpen:''} ${isBusy?lookStyles.fittingRoomBusy:''}`}><div className={lookStyles.roomBackdrop}/><div className={lookStyles.roomGlow}/><div className={lookStyles.platform}/><div className={lookStyles.modelArea}>{result?<img className={lookStyles.tryOnResult} src={result} alt="Look vestido no modelo"/>:<div className={lookStyles.modelPlaceholder}><span>{selected?.glyph||'M'}</span><strong>{isBusy?'Vestindo seu look...':selected?.name}</strong><small>{isBusy?'Ajustando caimento, proporções e acessórios.':selected?.hint}</small></div>}</div><i className={`${lookStyles.curtain} ${lookStyles.curtainLeft}`}/><i className={`${lookStyles.curtain} ${lookStyles.curtainRight}`}/><div className={lookStyles.stageLabel}>{isBusy?'✦ preparando atrás da cortina':open?'✦ seu look no provador':'✦ cortina fechada'}</div></div>
   <div className={lookStyles.pieceRail}>{pieces.map(p=><button key={p.id} onClick={()=>onSwap(p)} aria-label={`Trocar ${p.name}`} title={p.name}><img src={p.image} alt={p.name}/></button>)}</div>
   {!result&&<div className={lookStyles.modelPicker}>{models.map(m=><button key={m.id} className={avatarId===m.id?lookStyles.modelSelected:''} onClick={()=>{setLocalImage('');setLocalError('');onAvatarChange(m.id)}}><span>{m.glyph}</span><div><strong>{m.name}</strong><small>{m.hint}</small></div></button>)}</div>}
   {shownError&&<div className={lookStyles.tryOnNotice}><strong>Não foi possível gerar agora.</strong><p>{shownError}</p>{balance<cost&&<button type="button" onClick={()=>window.location.href='/closet/credits'}>Como ganhar créditos</button>}</div>}
   <div className={lookStyles.fittingActions}>{!result?<button className={lookStyles.primaryStageButton} disabled={isBusy||!session||balance<cost} onClick={generate}>{isBusy?'Vestindo atrás da cortina...':balance<cost?'Créditos insuficientes':`✦ Experimentar com IA · ${cost} créditos`}</button>:<button className={lookStyles.primaryStageButton} disabled={isBusy||balance<cost} onClick={reset}>Ver em outro modelo · 3 créditos</button>}<button onClick={onRemix}>⤨ Sortear outro look · grátis</button><button type="button" onClick={()=>window.location.href='/closet/credits'}>✦ Meus créditos · {balance}</button></div>
  </div>
 </div>
}
