'use client';
export type ClosetWeather={date:string;code:number;label:string;tempMax:number|null;tempMin:number|null;feelsMax:number|null;feelsMin:number|null;rainChance:number|null;rainMm:number|null;windMax:number|null;timezone?:string|null;lat?:number;lon?:number};
const LOCATION_KEY='closet.weatherLocation.v1';
function validLoc(v:any):v is {lat:number;lon:number}{return Boolean(v&&Number.isFinite(Number(v.lat))&&Number.isFinite(Number(v.lon))&&Math.abs(Number(v.lat))<=90&&Math.abs(Number(v.lon))<=180)}
export function storedWeatherLocation():{lat:number;lon:number}|null{if(typeof window==='undefined')return null;try{const parsed=JSON.parse(localStorage.getItem(LOCATION_KEY)||'null');if(!validLoc(parsed)){if(parsed)localStorage.removeItem(LOCATION_KEY);return null}return {lat:Number(parsed.lat),lon:Number(parsed.lon)}}catch{try{localStorage.removeItem(LOCATION_KEY)}catch{}return null}}
export function requestWeatherLocation(){return new Promise<{lat:number;lon:number}>((resolve,reject)=>{if(typeof navigator==='undefined'||!navigator.geolocation)return reject(new Error('Localização não disponível neste aparelho.'));navigator.geolocation.getCurrentPosition(p=>{const loc={lat:Number(p.coords.latitude),lon:Number(p.coords.longitude)};if(!validLoc(loc))return reject(new Error('O aparelho retornou uma localização inválida.'));try{localStorage.setItem(LOCATION_KEY,JSON.stringify(loc))}catch{}resolve(loc)},err=>{const msg=err?.code===1?'Permita o acesso à localização para considerar o clima.':err?.code===2?'Não consegui obter sua localização agora.':err?.code===3?'A localização demorou para responder. Tente novamente.':'Não consegui acessar sua localização.';reject(new Error(msg))},{enableHighAccuracy:false,timeout:12000,maximumAge:1000*60*60*6})})}
function validDate(date:string){return /^\d{4}-\d{2}-\d{2}$/.test(String(date||''))}
export async function forecastForDate(date:string,loc:{lat:number;lon:number}){if(!validDate(date))throw new Error('Data inválida para consultar o clima.');if(!validLoc(loc))throw new Error('Localização inválida. Ative sua localização novamente.');const params=new URLSearchParams();params.set('lat',String(Number(loc.lat)));params.set('lon',String(Number(loc.lon)));params.set('date',date);let r:Response;try{r=await fetch(`/api/closet/weather?${params.toString()}`,{method:'GET',headers:{Accept:'application/json'},cache:'no-store'})}catch(e:any){throw new Error(e?.message&&/network|load failed|failed to fetch/i.test(String(e.message))?'Não consegui conectar ao serviço de clima.':String(e?.message||'Não consegui consultar o clima.'))}let d:any=null;try{d=await r.json()}catch{throw new Error('O serviço de clima respondeu em formato inválido.')}if(!r.ok||!d?.ok)throw new Error(d?.message||'Não consegui consultar o clima.');return {...d.weather,lat:Number(loc.lat),lon:Number(loc.lon)} as ClosetWeather}
export function weatherStylistHint(w?:ClosetWeather|Record<string,any>){if(!w)return'';const max=Number(w.tempMax),min=Number(w.tempMin),rain=Number(w.rainChance);const hints:string[]=[];if(Number.isFinite(max)){if(max>=30)hints.push('muito quente');else if(max>=26)hints.push('quente');else if(max<=17)hints.push('frio');else if(max<=21)hints.push('fresco');else hints.push('temperatura amena')}if(Number.isFinite(min)&&min<=16)hints.push('pode esfriar');if(Number.isFinite(rain)&&rain>=60)hints.push('alta chance de chuva');else if(Number.isFinite(rain)&&rain>=35)hints.push('possibilidade de chuva');return hints.join(', ')}
