import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequestPost as exchange} from '../../functions/api/trade/bridge/exchange';
const env={TRADE_BRIDGE_TOKEN:'isolated-transport-fixture-token-32-characters',TRADE_SUPABASE_URL:'https://fixture.invalid',TRADE_SUPABASE_SERVICE_KEY:'never-log-service-key',TRADE_EXECUTION_ENABLED:'false'};
const batch=()=>({bridgeId:'xp-mt5-primary',symbol:'WINV26',session:'fixture',batch:0,accountHash:'a'.repeat(64),ticks:[{symbol:'WINV26',timeMsc:1,bid:135000,ask:135005,last:135000,volume:1,flags:0}],candles:[],events:[],state:{protocolVersion:2,connected:true,executionAllowed:false,tickSize:5,positions:[],orders:[]}});
const request=(b:any,token=env.TRADE_BRIDGE_TOKEN)=>new Request('https://fixture.invalid/api/trade/bridge/exchange',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:typeof b==='string'?b:JSON.stringify(b)});
test('transport auth rejects bad token with stage authenticate before persistence',async()=>{const r=await exchange({env,request:request(batch(),'wrong')});assert.equal(r.status,401);assert.equal((await r.json() as any).stage,'authenticate');});
for(const [name,change,code] of [
 ['symbol',(b:any)=>b.symbol='WDO','BRIDGE_SYMBOL_MISMATCH'],
 ['account',(b:any)=>b.accountHash='invalid','BRIDGE_ACCOUNT_MISMATCH'],
 ['tick',(b:any)=>b.ticks[0].volume=-1,'BRIDGE_TICK_INVALID'],
 ['unclosed candle',(b:any)=>b.candles=[{symbol:b.symbol,timeframe:'1m',timestamp:Math.floor(Date.now()/1000),open:1,close:1,high:1,low:1,volume:1}],'BRIDGE_CANDLE_UNCLOSED_OR_SYMBOL'],
 ['tick size',(b:any)=>b.state.tickSize=0,'BRIDGE_TICK_SIZE_INVALID'],
] as const)test('transport diagnosis identifies '+name+' without exposing secrets',async()=>{const original=globalThis.fetch,log=console.error;globalThis.fetch=async()=>Response.json(null);console.error=()=>{};try{const b=batch();change(b);const r=await exchange({env,request:request(b)}),d:any=await r.json();assert.equal(r.status,400);assert.equal(d.stage,'validateBatch');assert.equal(d.errorCode,code);const s=JSON.stringify(d);assert.ok(!s.includes(env.TRADE_BRIDGE_TOKEN));assert.ok(!s.includes(env.TRADE_SUPABASE_SERVICE_KEY));assert.ok(!s.includes('a'.repeat(64)));}finally{globalThis.fetch=original;console.error=log;}});
test('parse error cannot echo raw token or fingerprint from invalid JSON',async()=>{const original=globalThis.fetch,log=console.error;globalThis.fetch=async()=>Response.json(null);console.error=()=>{};try{const r=await exchange({env,request:request('{'+env.TRADE_BRIDGE_TOKEN)});const d:any=await r.json();assert.equal(d.stage,'parse');assert.equal(d.error,'JSON inválido');assert.ok(!JSON.stringify(d).includes(env.TRADE_BRIDGE_TOKEN));}finally{globalThis.fetch=original;console.error=log;}});
test('disarmed valid v2 uses exact RPC signature and ignores any returned command; old ticks allowed on Sunday',async()=>{const original=globalThis.fetch,seen:any[]=[];globalThis.fetch=async(u,init)=>{const name=String(u).split('/').pop();const args=JSON.parse(String(init?.body));seen.push({name,args});return Response.json(name==='trade_operations_read'?[]:{command:{signatureVersion:2}});};try{const r=await exchange({env,request:request(batch())});assert.equal(r.status,200);assert.equal(await r.text(),'OK\n');const rpc=seen.find(x=>x.name==='trade_bridge_exchange_v2');assert.equal(rpc.args.p_execution,false);assert.equal(rpc.args.p_batch.state.backendDiagnostics.executionExplicitlyDisabled,true);assert.deepEqual(Object.keys(rpc.args),['p_batch','p_execution','p_max','p_account','p_max_age']);}finally{globalThis.fetch=original;}});
test('missing v2 RPC reports stage and schema code without echoing database error',async()=>{const original=globalThis.fetch,log=console.error;globalThis.fetch=async(u)=>String(u).endsWith('trade_bridge_exchange_v2')?Response.json({code:'PGRST202',message:env.TRADE_SUPABASE_SERVICE_KEY},{status:404}):Response.json([]);console.error=()=>{};try{const r=await exchange({env,request:request(batch())});const d:any=await r.json();assert.equal(r.status,400);assert.equal(d.stage,'trade_bridge_exchange_v2');assert.equal(d.errorCode,'SCHEMA_MISSING');assert.equal(d.rpcCode,'PGRST202');assert.ok(!JSON.stringify(d).includes(env.TRADE_SUPABASE_SERVICE_KEY));}finally{globalThis.fetch=original;console.error=log;}});
