const KEY='assistant:campaigns'
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function auth({request,env}){if(!env.ADMIN_TOKEN)return false;const cookie=request.headers.get('Cookie')||'';const m=cookie.match(/(?:^|;\s*)foco_admin_session=([^;]+)/);return Boolean(m&&decodeURIComponent(m[1])===env.ADMIN_TOKEN)}
async function read(env){if(!env.FOCO_LINKS)throw new Error('FOCO_LINKS não configurado.');return await env.FOCO_LINKS.get(KEY,{type:'json'})||[]}
const clean=v=>String(v||'').trim()
function buildPlan(p){const product=clean(p.product)||'Produto Foco em Canto',goal=clean(p.goal)||'vendas',theme=clean(p.theme)||`transformação com ${product}`,audience=clean(p.audience)||'cantores que desejam evoluir tecnicamente',date=clean(p.startDate)||new Date().toISOString().slice(0,10);return {title:clean(p.title)||`Campanha ${product} — ${theme}`,product,goal,theme,audience,startDate:date,status:'draft',strategy:['Diagnóstico da dor','Quebra de objeção','Demonstração de método','Prova e autoridade','Convite para a oferta','Urgência e fechamento'],content:[{channel:'Reel',day:'Segunda',title:`O erro que impede ${audience} de avançar`,cta:'Comente EU QUERO'},{channel:'Stories',day:'Terça',title:`Bastidores: como resolver ${theme}`,cta:'Responder enquete'},{channel:'WhatsApp',day:'Quarta',title:`Convite para aula ao vivo sobre ${theme}`,cta:'Entrar na live'},{channel:'Live',day:'Quarta 20h',title:`Aula principal: ${theme}`,cta:`Conhecer ${product}`},{channel:'WhatsApp',day:'Quinta',title:'Resumo, prova e abertura da oferta',cta:'Ver oferta'},{channel:'Stories',day:'Sexta',title:'Objeções frequentes e casos reais',cta:'Enviar dúvida'},{channel:'WhatsApp',day:'Domingo',title:'Fechamento e última chamada',cta:'Garantir vaga'}],messages:[{type:'Aquecimento',text:`Você sente que ainda não consegue avançar em ${theme}? Nesta semana vou mostrar um caminho prático para mudar isso.`},{type:'Convite',text:`Nesta quarta, às 20h, teremos uma aula especial sobre ${theme}. Separe esse horário — vai ser direto ao ponto.`},{type:'Oferta',text:`As inscrições para ${product} estão abertas. É o próximo passo para quem quer transformar conhecimento em resultado com direção e acompanhamento.`},{type:'Fechamento',text:`Última chamada para entrar no ${product}. Depois de hoje, esta condição sai do ar.`}],links:[{name:'Instagram',source:'instagram',medium:'social',campaign:slug(product),content:'reel'},{name:'WhatsApp',source:'whatsapp',medium:'grupo',campaign:slug(product),content:'live'},{name:'Stories',source:'instagram',medium:'stories',campaign:slug(product),content:'oferta'}]}}
const slug=v=>clean(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
export async function onRequestGet(c){if(!auth(c))return json({ok:false,message:'Não autorizado.'},401);try{return json({ok:true,campaigns:await read(c.env)})}catch(e){return json({ok:false,message:e.message},500)}}
export async function onRequestPost(c){if(!auth(c))return json({ok:false,message:'Não autorizado.'},401);try{const p=await c.request.json(),items=await read(c.env),now=new Date().toISOString();let item;if(p.action==='generate'){item={id:crypto.randomUUID(),...buildPlan(p),prompt:clean(p.prompt),createdAt:now,updatedAt:now}}else{const old=items.find(x=>x.id===p.id)||{};item={...old,...p,id:p.id||crypto.randomUUID(),updatedAt:now,createdAt:old.createdAt||now}}const i=items.findIndex(x=>x.id===item.id);i>=0?items.splice(i,1,item):items.unshift(item);await c.env.FOCO_LINKS.put(KEY,JSON.stringify(items));return json({ok:true,campaign:item})}catch(e){return json({ok:false,message:e.message},500)}}
export async function onRequestDelete(c){if(!auth(c))return json({ok:false,message:'Não autorizado.'},401);try{const {id}=await c.request.json(),items=(await read(c.env)).filter(x=>x.id!==id);await c.env.FOCO_LINKS.put(KEY,JSON.stringify(items));return json({ok:true})}catch(e){return json({ok:false,message:e.message},500)}}