const PRODUCTS_KEY='catalog:products'
const ENROLLMENTS_KEY='catalog:enrollments'
const LEADS_KEY='crm:leads'
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function auth({request,env}){if(!env.ADMIN_TOKEN)return false;const cookie=request.headers.get('Cookie')||'';const match=cookie.match(/(?:^|;\s*)foco_admin_session=([^;]+)/);return Boolean(match&&decodeURIComponent(match[1])===env.ADMIN_TOKEN)}
async function read(env,key){if(!env.FOCO_LINKS)throw new Error('FOCO_LINKS não configurado.');return await env.FOCO_LINKS.get(key,{type:'json'})||[]}
function normalize(value){return String(value||'').trim().toLowerCase()}
async function syncLeadFromEnrollment(env,enrollment,products){
  const leads=await read(env,LEADS_KEY)
  const product=products.find(x=>x.id===enrollment.productId)
  const email=normalize(enrollment.email),phone=normalize(enrollment.phone)
  let index=leads.findIndex(x=>(email&&normalize(x.email)===email)||(phone&&normalize(x.phone)===phone))
  const now=new Date().toISOString()
  const base=index>=0?leads[index]:{id:crypto.randomUUID(),createdAt:now}
  const updated={...base,name:enrollment.student||base.name||'',email:enrollment.email||base.email||'',phone:enrollment.phone||base.phone||'',source:enrollment.source||base.source||'',campaign:base.campaign||'',product:product?.name||base.product||'',status:enrollment.status==='cancelled'?'lead':'cliente',value:Number(enrollment.amount||0),notes:[base.notes,enrollment.notes].filter(Boolean).join('\n'),updatedAt:now}
  if(index>=0)leads[index]=updated;else leads.unshift(updated)
  await env.FOCO_LINKS.put(LEADS_KEY,JSON.stringify(leads))
}
export async function onRequestGet(c){if(!auth(c))return json({ok:false,message:'Não autorizado.'},401);try{return json({ok:true,products:await read(c.env,PRODUCTS_KEY),enrollments:await read(c.env,ENROLLMENTS_KEY)})}catch(e){return json({ok:false,message:e.message},500)}}
export async function onRequestPost(c){if(!auth(c))return json({ok:false,message:'Não autorizado.'},401);try{const p=await c.request.json(),now=new Date().toISOString();if(p.kind==='product'){const items=await read(c.env,PRODUCTS_KEY),item={id:p.id||crypto.randomUUID(),name:String(p.name||'').trim(),slug:String(p.slug||'').trim(),price:Number(p.price||0),status:String(p.status||'active'),description:String(p.description||'').trim(),createdAt:p.createdAt||now,updatedAt:now};if(!item.name)return json({ok:false,message:'Informe o nome do produto.'},400);const i=items.findIndex(x=>x.id===item.id);i>=0?items.splice(i,1,{...items[i],...item}):items.unshift(item);await c.env.FOCO_LINKS.put(PRODUCTS_KEY,JSON.stringify(items));return json({ok:true,product:item})}const products=await read(c.env,PRODUCTS_KEY),items=await read(c.env,ENROLLMENTS_KEY),item={id:p.id||crypto.randomUUID(),student:String(p.student||'').trim(),email:String(p.email||'').trim(),phone:String(p.phone||'').trim(),productId:String(p.productId||'').trim(),status:String(p.status||'active'),amount:Number(p.amount||0),source:String(p.source||'').trim(),purchasedAt:p.purchasedAt||now.slice(0,10),notes:String(p.notes||'').trim(),createdAt:p.createdAt||now,updatedAt:now};if(!item.student&&!item.email&&!item.phone)return json({ok:false,message:'Informe aluno, e-mail ou telefone.'},400);if(!item.productId)return json({ok:false,message:'Selecione um produto.'},400);const i=items.findIndex(x=>x.id===item.id);i>=0?items.splice(i,1,{...items[i],...item}):items.unshift(item);await c.env.FOCO_LINKS.put(ENROLLMENTS_KEY,JSON.stringify(items));await syncLeadFromEnrollment(c.env,item,products);return json({ok:true,enrollment:item,crmSynced:true})}catch(e){return json({ok:false,message:e.message},500)}}
export async function onRequestDelete(c){if(!auth(c))return json({ok:false,message:'Não autorizado.'},401);try{const p=await c.request.json(),key=p.kind==='product'?PRODUCTS_KEY:ENROLLMENTS_KEY,items=(await read(c.env,key)).filter(x=>x.id!==p.id);await c.env.FOCO_LINKS.put(key,JSON.stringify(items));if(p.kind==='product'){const enrollments=(await read(c.env,ENROLLMENTS_KEY)).filter(x=>x.productId!==p.id);await c.env.FOCO_LINKS.put(ENROLLMENTS_KEY,JSON.stringify(enrollments))}return json({ok:true})}catch(e){return json({ok:false,message:e.message},500)}}