'use client';

import { useEffect, useMemo, useState } from 'react';
import styles from './look-page.module.css';
import TryOnStage from '../TryOnStage';
import { loadClosetItems, restoreClosetSession, updateClosetItemPreference, type ClosetSession } from '../supabase';
import { loadSavedLooks, saveLook } from '../savedLooks';
import { enrichWithRotation } from '../rotation';
import { loadStyleProfile } from '../styleProfile';
import { loadTrip,loadTripMoment,saveTripMomentLook,type Trip,type TripMoment } from '../travelStore';
import { isCompleteLook, replacementCandidates, manualReplacementCandidates, pieceMatchesSelectedPalette, type StylistPiece, type StyleProfile } from '../lookEngine';
import { explainLookV2 } from '../lookEngineV2';
import { buildStyledLookV3, buildStyledLookWithAnchorV3, stylistV3Meta } from '../lookEngineV3';
import {ensureBaseUnderOuterwear,ensureMandatoryAccessories,hasSemanticBase,isOuterwear,isMandatoryAccessory} from '../lookSemantics';

type Piece=StylistPiece&{dbMetadata?:Record<string,any>};
type LookGap={category:string;label:string};
const avatarModels=[{id:'m-1',name:'Masculino clássico',hint:'Corpo médio · atlético',glyph:'M'},{id:'m-2',name:'Masculino slim',hint:'Corpo mais esguio',glyph:'M'},{id:'m-3',name:'Masculino amplo',hint:'Estrutura mais larga',glyph:'M'},{id:'f-1',name:'Feminino clássico',hint:'Corpo médio',glyph:'F'},{id:'f-2',name:'Feminino slim',hint:'Corpo mais esguio',glyph:'F'},{id:'f-3',name:'Feminino curvas',hint:'Corpo com curvas',glyph:'F'}];
function mapRows(rows:any[]):Piece[]{return rows.map(r=>({id:r.id,category:r.category,name:r.name,meta:[r.color,r.subcategory,r.pattern,r.style].filter(Boolean).join(' · '),image:r.image||'',dbMetadata:r.metadata||{},stylistPreference:r.metadata?.stylist_preference||{},wardrobeStatus:r.metadata?.wardrobe_status||'available'}))}
function slot(p:Piece,i:number){if(p.category==='Vestidos')return styles.dress;if(p.category==='Blusas')return isOuterwear(p)?styles.outerwear:styles.top;if(p.category==='Calças')return styles.bottom;if(p.category==='Calçados')return styles.shoes;return[styles.accLeft,styles.accRight,styles.accLowerLeft,styles.accLowerRight][i%4]}
function gapSlot(category:string){if(category==='Blusas')return styles.top;if(category==='Calças')return styles.bottom;if(category==='Calçados')return styles.shoes;return styles.bottom}
function quickable(p:Piece){return p.category==='Blusas'||p.category==='Calças'||p.category==='Calçados'||p.category==='Vestidos'}
function quickKey(p:Piece){if(p.category==='Blusas')return isOuterwear(p)?'outerwear':'base';if(p.category==='Calças')return'bottom';if(p.category==='Calçados')return'shoes';if(p.category==='Vestidos')return'dress';return String(p.id)}
function norm(v:string){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim()}
function inferTravelOccasion(moment:TripMoment){const t=`${moment.title||''} ${moment.location_name||''}`.toLowerCase();if(/igreja|culto|templo/.test(t))return'Igreja';if(/casamento|formatura|cerim[oô]nia|evento/.test(t))return'Evento';if(/festa|anivers[aá]rio|balada/.test(t))return'Festa';if(/encontro|date|rom[aâ]nt|jantar especial/.test(t))return'Encontro';if(/aeroporto|voo|avi[aã]o|rodovi[aá]ria|viagem|check.?in/.test(t))return'Viagem';if(/trabalho|reuni[aã]o|congresso|escrit[oó]rio/.test(t))return'Trabalho';if(/faculdade|universidade/.test(t))return'Faculdade';return'Sair'}
function readStylistContext(){if(typeof window==='undefined')return{} as any;try{return JSON.parse(sessionStorage.getItem('closet_stylist_context')||'{}')||{}}catch{return{} as any}}
function missingEssentials(items:Piece[]):LookGap[]{const dress=items.some(p=>p.category==='Vestidos'),top=hasSemanticBase(items),bottom=items.some(p=>p.category==='Calças'),shoe=items.some(p=>p.category==='Calçados');const gaps:LookGap[]=[];if(dress){if(!shoe)gaps.push({category:'Calçados',label:'calçado'});return gaps}if(!top)gaps.push({category:'Blusas',label:'parte de cima / base'});if(!bottom)gaps.push({category:'Calças',label:'calça / parte de baixo'});if(!shoe)gaps.push({category:'Calçados',label:'calçado'});return gaps}
function semanticallyComplete(items:Piece[]){return isCompleteLook(items)&&hasSemanticBase(items)}
async function makeLookReference(items:Piece[]){const sources=await Promise.all(items.slice(0,8).map(p=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=p.image})));const c=document.createElement('canvas');c.width=1024;c.height=1024;const ctx=c.getContext('2d');if(!ctx)throw new Error('Não consegui preparar o look.');ctx.fillStyle='#f6f0e7';ctx.fillRect(0,0,1024,1024);const rows=Math.ceil(sources.length/2),cellW=512,cellH=1024/Math.max(1,rows);sources.forEach((img,i)=>{const col=i%2,row=Math.floor(i/2),pad=42,maxW=cellW-pad*2,maxH=cellH-pad*2,scale=Math.min(maxW/img.width,maxH/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,col*cellW+(cellW-w)/2,row*cellH+(cellH-h)/2,w,h)});return c.toDataURL('image/png')}

export default function LookPage(){
 const [session,setSession]=useState<ClosetSession|null>(null),[pieces,setPieces]=useState<Piece[]>([]),[profile,setProfile]=useState<StyleProfile>({}),[occasion,setOccasion]=useState('Sair');
 const [trip,setTrip]=useState<Trip|null>(null),[tripMoment,setTripMoment]=useState<TripMoment|null>(null),[travelMode,setTravelMode]=useState(false),[travelSource,setTravelSource]=useState<'manual'|'stylist'>('stylist');
 const [look,setLook]=useState<Piece[]>([]),[seed,setSeed]=useState(0),[anchorId,setAnchorId]=useState<string|null>(null),[building,setBuilding]=useState(true),[revealed,setRevealed]=useState(false),[swap,setSwap]=useState<Piece|null>(null),[itemMenu,setItemMenu]=useState<Piece|null>(null),[note,setNote]=useState(''),[savingPref,setSavingPref]=useState(false),[savingLook,setSavingLook]=useState(false),[saved,setSaved]=useState(false),[toast,setToast]=useState(''),[quickCycles,setQuickCycles]=useState<Record<string,number>>({});
 const [tryOn,setTryOn]=useState(false),[avatarId,setAvatarId]=useState('m-1'),[tryOnImage,setTryOnImage]=useState(''),[tryOnBusy,setTryOnBusy]=useState(false),[tryOnError,setTryOnError]=useState('');
 const candidates=useMemo(()=>swap?manualReplacementCandidates(pieces,swap,occasion,profile):[],[pieces,swap,occasion,profile]);
 const complete=semanticallyComplete(look);
 const partialLook=useMemo(()=>{if(complete||look.length)return look;const fake=(category:string):Piece=>({id:`gap-${category}`,category,name:'',meta:'',image:''});const strictPick=(category:string)=>replacementCandidates(pieces,fake(category),[],occasion,profile)[0] as Piece|undefined;const manualPick=(category:string)=>manualReplacementCandidates(pieces,fake(category),occasion,profile)[0] as Piece|undefined;const top=strictPick('Blusas'),bottom=strictPick('Calças'),shoe=strictPick('Calçados')||manualPick('Calçados'),dress=strictPick('Vestidos');if(dress&&shoe&&!top&&!bottom)return[dress,shoe];return[top,bottom,shoe].filter(Boolean) as Piece[]},[complete,look,pieces,occasion,profile]);
 const displayLook=complete?look:(look.length?look:partialLook),displayComplete=semanticallyComplete(displayLook),gaps=missingEssentials(displayLook),ctx=readStylistContext(),selectedColors=Array.isArray(ctx.colors)?ctx.colors:[],strictPalette=ctx?.paletteMode==='strict',paletteExplanation=useMemo(()=>explainLookV2(displayLook),[displayLook,occasion]);
 const gapColorText=strictPalette&&selectedColors.length?` em ${selectedColors.join(' + ')}`:'';
 function marketplaceForGap(gap:LookGap){return `/closet/marketplace/?category=${encodeURIComponent(gap.category)}&colors=${encodeURIComponent(selectedColors.join(','))}&occasion=${encodeURIComponent(occasion)}`}
 function notify(m:string){setToast(m);window.setTimeout(()=>setToast(''),2200)}
 function withShoeFallback(next:Piece[],all:Piece[],o:string,p:StyleProfile){if(semanticallyComplete(next))return next;if(readStylistContext()?.paletteMode==='strict')return next;const miss=missingEssentials(next).find(x=>x.category==='Calçados');if(!miss)return next;const fake:Piece={id:'gap-Calçados',category:'Calçados',name:'',meta:'',image:''};const shoe=manualReplacementCandidates(all,fake,o,p).find(x=>!next.some(y=>String(y.id)===String(x.id))) as Piece|undefined;return shoe?[...next,shoe]:next}
 function finalize(next:Piece[],all:Piece[],o:string){let out=ensureBaseUnderOuterwear(next,all,o) as Piece[];out=ensureMandatoryAccessories(out,all,o) as Piece[];return out}
 function openClosetSuggestion(gap:LookGap){setSwap({id:`gap-${gap.category}`,category:gap.category,name:`Sugestão para ${gap.label}`,meta:'',image:''})}
 function reveal(next:Piece[],delay=1050,alreadySaved=false){setBuilding(true);setRevealed(false);setSaved(alreadySaved);window.setTimeout(()=>{setLook(next);setBuilding(false);window.setTimeout(()=>setRevealed(true),90)},delay)}
 function paletteCoverage(items:Piece[]){if(!selectedColors.length)return 0;const represented=new Set<string>();for(const p of items.filter(quickable)){const t=norm(`${p.name||''} ${p.meta||''}`);for(const c of selectedColors){const n=norm(c);if(n&&t.includes(n))represented.add(n)}}return represented.size}
 function isInsideSelectedPalette(p:Piece){if(!selectedColors.length)return false;const declared=norm(String(p.meta||'').split('·')[0]||'');const text=norm(`${p.name||''} ${p.meta||''}`);return selectedColors.some(c=>{const wanted=norm(c);return Boolean(wanted&&(declared===wanted||text.includes(wanted)))})}
 function quickPalettePool(p:Piece){let pool=manualReplacementCandidates(pieces,p,occasion,profile).filter(x=>String(x.id)!==String(p.id)) as Piece[];if(p.category==='Blusas')pool=pool.filter(x=>isOuterwear(x)===isOuterwear(p));return pool.filter(isInsideSelectedPalette)}
 function hasQuickPaletteAlternative(p:Piece){return quickPalettePool(p).length>0}
 function quickSwap(p:Piece){const current=look.length?look:displayLook;if(!current.length)return;let pool=quickPalettePool(p);if(!pool.length){notify('Não há outra peça desta paleta para este espaço. Use “Trocar por outra” para ver todo o Closet.');return}pool=[...pool].sort((a,b)=>{const nextA=current.map(x=>String(x.id)===String(p.id)?a:x),nextB=current.map(x=>String(x.id)===String(p.id)?b:x);const coverageDiff=paletteCoverage(nextB)-paletteCoverage(nextA);if(coverageDiff)return coverageDiff;return 0});const key=quickKey(p),idx=(quickCycles[key]||0)%pool.length,candidate=pool[idx];const next=finalize(current.map(x=>String(x.id)===String(p.id)?candidate:x),pieces,occasion);if(!semanticallyComplete(next)){notify('Essa opção da paleta quebraria o look. Tente a próxima.');setQuickCycles(v=>({...v,[key]:(v[key]||0)+1}));return}setQuickCycles(v=>({...v,[key]:(v[key]||0)+1}));setLook(next);setSaved(false);setTryOnImage('');setTryOnError('');notify(`${candidate.name} entrou no look`)}
 useEffect(()=>{let alive=true;(async()=>{const query=new URLSearchParams(window.location.search);const requestedOccasion=query.get('occasion');const savedId=query.get('saved');const requestedAnchor=query.get('anchor');const tripId=query.get('trip'),momentId=query.get('moment'),mode=query.get('mode');const wxMax=query.get('wxMax'),wxMin=query.get('wxMin'),wxRain=query.get('wxRain'),wxLabel=query.get('wxLabel');const weatherContext=(wxMax||wxMin||wxRain||wxLabel)?{tempMax:wxMax==null?null:Number(wxMax),tempMin:wxMin==null?null:Number(wxMin),rainChance:wxRain==null?null:Number(wxRain),label:wxLabel||''}:undefined;const s=await restoreClosetSession();if(!alive)return;if(!s){setBuilding(false);return}setSession(s);
 let activeTrip:Trip|null=null,activeMoment:TripMoment|null=null;if(tripId&&momentId){[activeTrip,activeMoment]=await Promise.all([loadTrip(s,tripId),loadTripMoment(s,momentId)]);if(activeTrip&&activeMoment&&activeMoment.trip_id===activeTrip.id){setTravelMode(true);setTrip(activeTrip);setTripMoment(activeMoment);setTravelSource(mode==='manual'?'manual':'stylist')}}
 const [rows,sp,savedLooks]=await Promise.all([loadClosetItems(s),loadStyleProfile(s),loadSavedLooks(s).catch(()=>[])]);if(!alive)return;const mapped=enrichWithRotation(mapRows(rows),savedLooks) as Piece[];let effectiveProfile:StyleProfile={...(sp||{}),...(weatherContext?{weather_context:weatherContext}:{})};if(activeTrip&&activeMoment){effectiveProfile={...effectiveProfile,travel_context:{tripId:activeTrip.id,destination:activeTrip.destination,momentId:activeMoment.id,moment:activeMoment.title,place:activeMoment.location_name||activeTrip.destination,environment:activeMoment.environment||'mixed',thermalPreference:activeTrip.thermal_preference,thermalNeed:activeMoment.thermal_need||null,tempMin:activeMoment.expected_temp_min??null,tempMax:activeMoment.expected_temp_max??null,rainChance:activeMoment.rain_probability??null}} as StyleProfile}
 setPieces(mapped);setProfile(effectiveProfile);if(savedId){const found=savedLooks.find(x=>x.id===savedId);if(found){setOccasion(found.occasion);const ids=new Set((found.item_ids||[]).map(String));const restored=mapped.filter(p=>ids.has(String(p.id)));reveal(finalize(restored,mapped,found.occasion),420,true);return}}
 const o=activeMoment?inferTravelOccasion(activeMoment):(requestedOccasion||sessionStorage.getItem('closet_last_occasion')||'Sair');setOccasion(o);if(requestedAnchor){const anchor=mapped.find(p=>String(p.id)===requestedAnchor);if(anchor){setAnchorId(String(anchor.id));const built=withShoeFallback(buildStyledLookWithAnchorV3(mapped,anchor,o,effectiveProfile,0) as Piece[],mapped,o,effectiveProfile);reveal(finalize(built,mapped,o),800);return}}const built=withShoeFallback(buildStyledLookV3(mapped,o,effectiveProfile,0) as Piece[],mapped,o,effectiveProfile);reveal(finalize(built,mapped,o),800)})().catch(()=>setBuilding(false));return()=>{alive=false}},[]);
 function remix(){const nextSeed=seed+1;setSeed(nextSeed);setTryOnImage('');setTryOnError('');setQuickCycles({});const anchor=anchorId?pieces.find(p=>String(p.id)===anchorId):null;const next=(anchor?buildStyledLookWithAnchorV3(pieces,anchor,occasion,profile,nextSeed):buildStyledLookV3(pieces,occasion,profile,nextSeed)) as Piece[];reveal(finalize(withShoeFallback(next,pieces,occasion,profile),pieces,occasion),850);notify(anchor?'Novo look mantendo sua peça':travelMode?'Nova opção para este momento':'Novo look sendo montado')}
 function applySwap(p:Piece){if(!swap)return;if(String(swap.id).startsWith('gap-')){const base=look.length?look:displayLook;const next=finalize([...base,p],pieces,occasion);setLook(next);setSaved(false);setSwap(null);setTryOnImage('');setTryOnError('');notify(`${p.name} completou o look`);return}const next=finalize(look.map(x=>x.id===swap.id?p:x),pieces,occasion);if(!semanticallyComplete(next)){notify('Essa troca deixaria o look incompleto.');return}if(anchorId&&String(swap.id)===anchorId)setAnchorId(String(p.id));setLook(next);setSaved(false);setSwap(null);setTryOnImage('');setTryOnError('');notify(`${p.name} entrou no look`)}
 function openItem(p:Piece){setItemMenu(p);setNote(p.stylistPreference?.note||'')}
 function buildAround(p:Piece){setAnchorId(String(p.id));setItemMenu(null);setTryOnImage('');setTryOnError('');const next=buildStyledLookWithAnchorV3(pieces,p,occasion,profile,seed+1) as Piece[];reveal(finalize(withShoeFallback(next,pieces,occasion,profile),pieces,occasion),760);notify(`Vou manter ${p.name} e completar o restante`)}
 async function saveCurrentLook(){if(!session||!complete||savingLook||saved)return;setSavingLook(true);try{if(travelMode&&tripMoment){await saveTripMomentLook(session,tripMoment.id,look.map(p=>String(p.id)),travelSource);setSaved(true);notify('Look salvo neste momento da viagem');return}await saveLook(session,{occasion,itemIds:look.map(p=>String(p.id)),rating:'saved',source:'stylist',context:{...ctx,...stylistV3Meta(profile),source:'stylist'}});setSaved(true);notify(`Look salvo em ${occasion}`)}catch(e:any){notify(e?.message||'Não consegui salvar este look.')}finally{setSavingLook(false)}}
 async function savePreference(pref:Record<string,any>,message:string){if(!session||!itemMenu)return;setSavingPref(true);try{const merged={...(itemMenu.stylistPreference||{}),...pref,note:pref.note??note};await updateClosetItemPreference(session,itemMenu.id,itemMenu.dbMetadata,merged);const update=(p:Piece)=>p.id===itemMenu.id?{...p,stylistPreference:merged,dbMetadata:{...(p.dbMetadata||{}),stylist_preference:merged}}:p;const nextPieces=pieces.map(update);setPieces(nextPieces);setLook(v=>finalize(v.map(update),nextPieces,occasion));setItemMenu(null);notify(message)}catch(e:any){notify(e?.message||'Não consegui salvar essa preferência.')}finally{setSavingPref(false)}}
 function removeFromLook(){if(!itemMenu)return;if(isMandatoryAccessory(itemMenu)){notify('Este acessório está marcado como obrigatório. Altere essa preferência antes de removê-lo.');return}const next=look.filter(p=>p.id!==itemMenu.id);if(!semanticallyComplete(next)){setSwap(itemMenu);setItemMenu(null);notify('Essa é uma peça essencial. Escolha outra para substituí-la.');return}if(anchorId===String(itemMenu.id))setAnchorId(null);setLook(next);setSaved(false);setItemMenu(null);setTryOnImage('');notify('Peça retirada deste look')}
 async function generateTryOn(){if(!look.length)return;setTryOnBusy(true);setTryOnError('');setTryOnImage('');try{const image=await makeLookReference(look);const r=await fetch('/api/closet/try-on',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,avatarId,occasion,items:look.map(p=>({name:p.name,category:p.category,meta:p.meta}))})});const data=await r.json();if(!r.ok||!data?.ok||!data?.image)throw new Error(data?.message||'Não consegui vestir este look.');setTryOnImage(String(data.image))}catch(e:any){const raw=String(e?.message||'');setTryOnError(/credits|billing|quota/i.test(raw)?'A visualização vestida está temporariamente indisponível. Seu look continua salvo aqui.':raw||'Não consegui vestir este look agora.')}finally{setTryOnBusy(false)}}
 const personalized=Object.keys(profile||{}).length>0,rotationActive=pieces.some(p=>Number(p.rotationPenalty||0)>0),weatherActive=Boolean(profile.weather_context&&Object.keys(profile.weather_context).length);const weather=profile.weather_context||{};const travel:any=(profile as any).travel_context||{};
 const backHref=travelMode&&trip?`/closet/travel/detail/?id=${encodeURIComponent(trip.id)}`:'/closet';
 if(!session&&!building)return <main className={styles.page}><div className={styles.empty}><span>SEU LOOK</span><h1>Entre no closet primeiro.</h1><p>Seu guarda-roupa precisa estar conectado para o stylist montar uma combinação.</p><button onClick={()=>window.location.href='/closet'}>Voltar ao closet</button></div></main>;
 return <main className={styles.page}>
  <header className={styles.header}><button onClick={()=>window.location.href=backHref}>‹</button><div><span>{travelMode?'TRAVEL CLOSET':anchorId?'COMEÇANDO POR UMA PEÇA':'STYLIST PESSOAL'}</span><strong>{travelMode?(tripMoment?.title||'Momento da viagem'):`Para ${occasion}`}</strong></div><button className={styles.more} onClick={()=>window.location.href=travelMode&&trip?backHref:'/closet/looks'}>{travelMode?'✦':'♡'}</button></header>
  {!tryOn?<section className={styles.experience}>
   <div className={`${styles.stage} ${revealed&&!building?styles.stageOpen:''}`}><div className={styles.backdrop}/><div className={styles.glow}/><div className={styles.platform}/><div className={styles.lookArea}>{displayLook.map((p,i)=><span key={p.id}><button className={`${styles.item} ${slot(p,i)}`} onClick={()=>openItem(p)} aria-label={`Opções para ${p.name}`}><img src={p.image} alt={p.name}/></button>{!building&&displayComplete&&quickable(p)&&hasQuickPaletteAlternative(p)&&<button className={`${styles.quickArrow} ${slot(p,i)}`} onClick={()=>quickSwap(p)} aria-label={`Ver outra opção da paleta para ${p.name}`} title="Ver próxima opção da paleta">›</button>}</span>)}{!building&&!displayComplete&&gaps.map(gap=><button key={gap.category} className={`${styles.gapSlot} ${gapSlot(gap.category)}`} onClick={()=>location.href=marketplaceForGap(gap)} aria-label={`Encontrar ${gap.label} no Marketplace`}><span className={styles.gapIcon}>＋</span><strong>{gap.label}</strong><small>{strictPalette&&selectedColors.length?selectedColors.join(' + '):'adequada ao contexto'}</small><b>Marketplace →</b></button>)}</div><i className={`${styles.curtain} ${styles.leftCurtain}`}/><i className={`${styles.curtain} ${styles.rightCurtain}`}/><div className={styles.stageCopy}>{building?(travelMode?'✦ preparando para este momento da viagem':'✦ combinando suas peças'):displayComplete?(anchorId?'✦ sua peça ficou fixa neste look':travelMode?`✦ pronto para ${tripMoment?.title?.toLowerCase()||'a viagem'}`:`✦ pronto para ${occasion.toLowerCase()}`):gaps.length?`✦ faltam ${gaps.map(x=>x.label).join(' + ')}${gapColorText}`:'✦ look incompleto'}</div></div>
   {!building&&!displayComplete&&gaps.map(gap=><div key={`card-${gap.category}`} className={styles.gapCard}><span>PEÇA QUE FALTA</span><strong>Falta {gap.label}{gapColorText}.</strong><p>{strictPalette?'A paleta estrita não permite substituir essa peça por outra cor. Você pode procurar a peça exata no Marketplace ou escolher manualmente uma alternativa do Closet.':'Não encontrei uma peça adequada ao contexto para completar este look automaticamente. Antes de comprar, você ainda pode escolher manualmente uma alternativa do seu Closet.'}</p><div><button onClick={()=>location.href=marketplaceForGap(gap)}>Encontrar no Marketplace</button><button onClick={()=>openClosetSuggestion(gap)}>Sugestão do Closet</button><button onClick={()=>location.href='/closet/add/'}>Adicionar ao Closet</button></div></div>)}
   <div className={styles.reason}><span>{travelMode?'TRAVEL STYLIST':weatherActive?'STYLIST V3 + CLIMA':personalized?'STYLIST V3 · PERFIL':'STYLIST V3'}</span><strong>{travelMode?`${trip?.destination}${tripMoment?.location_name?` · ${tripMoment.location_name}`:''}${tripMoment?.environment?` · ${tripMoment.environment==='indoor'?'ambiente interno':tripMoment.environment==='outdoor'?'ao ar livre':'ambiente misto'}`:''}`:anchorId?'Uma peça escolhida + seu gosto + ocasião.':weatherActive?`${weather.label||'Previsão'} · ${weather.tempMax!=null?`${Math.round(Number(weather.tempMax))}°`:''} influenciou este look.`:personalized?'Perfil + contexto + harmonia + paleta.':'Contexto + harmonia + regras de moda.'}</strong><small>{paletteExplanation.message} {travelMode?`Este look nasceu dentro da viagem “${trip?.name}”. Considerei seu perfil, o momento “${tripMoment?.title}”, o destino e sua sensibilidade térmica (${travel.thermalPreference||3}/5). `:''}{weatherActive?'Temperatura e chance de chuva alteraram a prioridade das peças. ':''}{rotationActive?'Também considerei o que você usou recentemente para evitar repetições desnecessárias. ':''}{ctx?.work_profile?.dress_code?`Dress code de trabalho: ${ctx.work_profile.dress_code}. `:''}As setas percorrem somente alternativas da paleta escolhida. Para ver qualquer peça do Closet, toque na peça e use “Trocar por outra”.</small></div>
   <div className={styles.actions}><button onClick={remix}>↻ {anchorId?'Outro com esta peça':travelMode?'Outra opção':'Sortear outro'}</button><button disabled={!complete} onClick={()=>{setTryOn(true);setTryOnError('')}}>♙ Ver vestido</button><button disabled={!complete||savingLook||saved} onClick={saveCurrentLook}>{saved?'♥ Salvo':savingLook?'Salvando…':travelMode?'♡ Salvar neste roteiro':'♡ Salvar look'}</button></div>
  </section>:<section className={styles.tryOnScreen}><TryOnStage pieces={look} models={avatarModels} avatarId={avatarId} image={tryOnImage} busy={tryOnBusy} error={tryOnError} onAvatarChange={id=>{setAvatarId(id);setTryOnImage('');setTryOnError('')}} onGenerate={generateTryOn} onSwap={p=>{setTryOn(false);openItem(p)}} onRemix={()=>{setTryOn(false);remix()}} onResetModel={()=>{setTryOnImage('');setTryOnError('')}} onClose={()=>setTryOn(false)}/></section>}
  {itemMenu&&<div className={styles.swapBackdrop} onClick={()=>setItemMenu(null)}><div className={`${styles.swapSheet} ${styles.itemSheet}`} onClick={e=>e.stopPropagation()}><div className={styles.swapHead}><div><span>ESSA PEÇA</span><strong>{itemMenu.name}</strong></div><button onClick={()=>setItemMenu(null)}>×</button></div><div className={styles.itemPreview}><img src={itemMenu.image} alt={itemMenu.name}/></div><div className={styles.itemOptions}><button onClick={()=>buildAround(itemMenu)}>✦ Montar outro look com esta peça</button><button onClick={()=>{setSwap(itemMenu);setItemMenu(null)}}>↻ Trocar por outra</button><button onClick={removeFromLook}>− Tirar deste look</button>{(itemMenu.category==='Acessórios'||itemMenu.category==='Bolsas')&&<><button disabled={savingPref} onClick={()=>savePreference({mandatory:true,mandatory_occasions:[]},'Vou incluir este acessório em todos os looks')}>Sempre comigo</button><button disabled={savingPref} onClick={()=>savePreference({mandatory:true,mandatory_occasions:[occasion]},`Vou incluir este acessório em ${occasion}`)}>Obrigatório em {occasion}</button>{isMandatoryAccessory(itemMenu)&&<button disabled={savingPref} onClick={()=>savePreference({mandatory:false,mandatory_occasions:[]},'Este acessório voltou a ser opcional')}>Deixar opcional</button>}</>}<button disabled={savingPref} onClick={()=>savePreference({frequency:'rare',only_occasions:[]},'Entendi: você usa pouco essa peça')}>Uso pouco</button><button disabled={savingPref} onClick={()=>savePreference({frequency:'special',only_occasions:['Evento','Festa','Encontro','Igreja']},'Vou guardar essa peça para ocasiões especiais')}>Só em ocasiões especiais</button><button disabled={savingPref} onClick={()=>savePreference({frequency:'special',only_occasions:['Evento']},'Entendi: essa peça fica para eventos especiais')}>Só em casamentos/eventos</button><button disabled={savingPref} className={styles.avoidButton} onClick={()=>savePreference({frequency:'never',only_occasions:[]},'Não vou mais sugerir essa peça')}>Não sugerir esta peça</button></div><label className={styles.noteField}>Observação para o stylist<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: só uso à noite, não gosto com tênis, uso mais em casamento..."/><button disabled={savingPref} onClick={()=>savePreference({note},'Observação salva. Vou lembrar disso')}>Salvar observação</button></label></div></div>}
  {swap&&<div className={styles.swapBackdrop} onClick={()=>setSwap(null)}><div className={styles.swapSheet} onClick={e=>e.stopPropagation()}><div className={styles.swapHead}><div><span>{String(swap.id).startsWith('gap-')?'SUGESTÃO DO CLOSET':'TROCAR ITEM'}</span><strong>{String(swap.id).startsWith('gap-')?'Escolha uma peça que funcione':'Escolha qualquer opção'}</strong><small>{String(swap.id).startsWith('gap-')?'Mostro primeiro as opções mais próximas da paleta e adequadas ao contexto.':'A paleta aparece primeiro, mas não limita sua escolha.'}</small></div><button onClick={()=>setSwap(null)}>×</button></div><div className={styles.swapGrid}>{candidates.slice(0,40).map(p=><button key={p.id} onClick={()=>applySwap(p)} className={pieceMatchesSelectedPalette(p,occasion)?styles.paletteMatch:''}><img src={p.image} alt={p.name}/>{pieceMatchesSelectedPalette(p,occasion)&&<span>na paleta</span>}</button>)}</div>{!candidates.length&&<p className={styles.swapEmpty}>Não há outra peça desta categoria no seu Closet.</p>}</div></div>}
  <div className={`${styles.toast} ${toast?styles.toastShow:''}`}>{toast}</div>
 </main>
}