'use client';

import { useEffect, useMemo, useState } from 'react';
import styles from './look-page.module.css';
import TryOnStage from '../TryOnStage';
import { loadClosetItems, restoreClosetSession, updateClosetItemPreference, type ClosetSession } from '../supabase';
import { loadSavedLooks, saveLook } from '../savedLooks';
import { loadStyleProfile } from '../styleProfile';
import { buildStyledLook, buildStyledLookWithAnchor, isCompleteLook, replacementCandidates, type StylistPiece, type StyleProfile } from '../lookEngine';

type Piece=StylistPiece&{dbMetadata?:Record<string,any>};
const avatarModels=[{id:'m-1',name:'Masculino clássico',hint:'Corpo médio · atlético',glyph:'M'},{id:'m-2',name:'Masculino slim',hint:'Corpo mais esguio',glyph:'M'},{id:'m-3',name:'Masculino amplo',hint:'Estrutura mais larga',glyph:'M'},{id:'f-1',name:'Feminino clássico',hint:'Corpo médio',glyph:'F'},{id:'f-2',name:'Feminino slim',hint:'Corpo mais esguio',glyph:'F'},{id:'f-3',name:'Feminino curvas',hint:'Corpo com mais curvas',glyph:'F'}];
function mapRows(rows:any[]):Piece[]{return rows.map(r=>({id:r.id,category:r.category,name:r.name,meta:[r.color,r.subcategory,r.pattern,r.style].filter(Boolean).join(' · '),image:r.image||'',dbMetadata:r.metadata||{},stylistPreference:r.metadata?.stylist_preference||{}}))}
function slot(p:Piece,i:number){if(p.category==='Vestidos')return styles.dress;if(p.category==='Blusas')return styles.top;if(p.category==='Calças')return styles.bottom;if(p.category==='Calçados')return styles.shoes;return[styles.accLeft,styles.accRight,styles.accLowerLeft,styles.accLowerRight][i%4]}
async function makeLookReference(items:Piece[]){const sources=await Promise.all(items.slice(0,7).map(p=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=p.image})));const c=document.createElement('canvas');c.width=1024;c.height=1024;const ctx=c.getContext('2d');if(!ctx)throw new Error('Não consegui preparar o look.');ctx.fillStyle='#f6f0e7';ctx.fillRect(0,0,1024,1024);const cols=2,rows=Math.ceil(sources.length/2),cellW=512,cellH=1024/Math.max(1,rows);sources.forEach((img,i)=>{const col=i%2,row=Math.floor(i/2),pad=42,maxW=cellW-pad*2,maxH=cellH-pad*2,scale=Math.min(maxW/img.width,maxH/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,col*cellW+(cellW-w)/2,row*cellH+(cellH-h)/2,w,h)});return c.toDataURL('image/png')}

export default function LookPage(){
 const [session,setSession]=useState<ClosetSession|null>(null),[pieces,setPieces]=useState<Piece[]>([]),[profile,setProfile]=useState<StyleProfile>({}),[occasion,setOccasion]=useState('Sair');
 const [look,setLook]=useState<Piece[]>([]),[seed,setSeed]=useState(0),[anchorId,setAnchorId]=useState<string|null>(null),[building,setBuilding]=useState(true),[revealed,setRevealed]=useState(false),[swap,setSwap]=useState<Piece|null>(null),[itemMenu,setItemMenu]=useState<Piece|null>(null),[note,setNote]=useState(''),[savingPref,setSavingPref]=useState(false),[savingLook,setSavingLook]=useState(false),[saved,setSaved]=useState(false),[toast,setToast]=useState('');
 const [tryOn,setTryOn]=useState(false),[avatarId,setAvatarId]=useState('m-1'),[tryOnImage,setTryOnImage]=useState(''),[tryOnBusy,setTryOnBusy]=useState(false),[tryOnError,setTryOnError]=useState('');
 const candidates=useMemo(()=>swap?replacementCandidates(pieces,swap,look,occasion,profile):[],[pieces,swap,look,occasion,profile]);
 function notify(m:string){setToast(m);window.setTimeout(()=>setToast(''),2200)}
 function reveal(next:Piece[],delay=1050,alreadySaved=false){setBuilding(true);setRevealed(false);setSaved(alreadySaved);window.setTimeout(()=>{setLook(next);setBuilding(false);window.setTimeout(()=>setRevealed(true),90)},delay)}
 useEffect(()=>{let alive=true;(async()=>{const query=new URLSearchParams(window.location.search);const requestedOccasion=query.get('occasion');const savedId=query.get('saved');const requestedAnchor=query.get('anchor');const s=await restoreClosetSession();if(!alive)return;if(!s){setBuilding(false);return}setSession(s);const [rows,sp,savedLooks]=await Promise.all([loadClosetItems(s),loadStyleProfile(s),savedId?loadSavedLooks(s):Promise.resolve([])]);if(!alive)return;const mapped=mapRows(rows);setPieces(mapped);setProfile(sp||{});if(savedId){const found=savedLooks.find(x=>x.id===savedId);if(found){setOccasion(found.occasion);const ids=new Set((found.item_ids||[]).map(String));const restored=mapped.filter(p=>ids.has(String(p.id)));reveal(restored,420,true);return}}const o=requestedOccasion||sessionStorage.getItem('closet_last_occasion')||'Sair';setOccasion(o);if(requestedAnchor){const anchor=mapped.find(p=>String(p.id)===requestedAnchor);if(anchor){setAnchorId(String(anchor.id));reveal(buildStyledLookWithAnchor(mapped,anchor,o,sp||{},0),800);return}}reveal(buildStyledLook(mapped,o,sp||{},0),800)})().catch(()=>setBuilding(false));return()=>{alive=false}},[]);
 function remix(){const nextSeed=seed+1;setSeed(nextSeed);setTryOnImage('');setTryOnError('');const anchor=anchorId?pieces.find(p=>String(p.id)===anchorId):null;reveal(anchor?buildStyledLookWithAnchor(pieces,anchor,occasion,profile,nextSeed):buildStyledLook(pieces,occasion,profile,nextSeed),850);notify(anchor?'Novo look mantendo sua peça ✦':'Novo look sendo montado ✦')}
 function applySwap(p:Piece){if(!swap)return;const next=look.map(x=>x.id===swap.id?p:x);if(!isCompleteLook(next)){notify('Essa troca deixaria o look incompleto.');return}if(anchorId&&String(swap.id)===anchorId)setAnchorId(String(p.id));setLook(next);setSaved(false);setSwap(null);setTryOnImage('');setTryOnError('');notify(`${p.name} entrou no look ✦`)}
 function openItem(p:Piece){setItemMenu(p);setNote(p.stylistPreference?.note||'')}
 function buildAround(p:Piece){setAnchorId(String(p.id));setItemMenu(null);setTryOnImage('');setTryOnError('');reveal(buildStyledLookWithAnchor(pieces,p,occasion,profile,seed+1),760);notify(`Vou manter ${p.name} e completar o restante ✦`)}
 async function saveCurrentLook(){if(!session||!complete||savingLook||saved)return;setSavingLook(true);try{await saveLook(session,{occasion,itemIds:look.map(p=>String(p.id)),rating:'love'});setSaved(true);notify(`Look salvo em ${occasion} ♡`)}catch(e:any){notify(e?.message||'Não consegui salvar este look.')}finally{setSavingLook(false)}}
 async function savePreference(pref:Record<string,any>,message:string){if(!session||!itemMenu)return;setSavingPref(true);try{const merged={...(itemMenu.stylistPreference||{}),...pref,note:pref.note??note};await updateClosetItemPreference(session,itemMenu.id,itemMenu.dbMetadata,merged);const update=(p:Piece)=>p.id===itemMenu.id?{...p,stylistPreference:merged,dbMetadata:{...(p.dbMetadata||{}),stylist_preference:merged}}:p;setPieces(v=>v.map(update));setLook(v=>v.map(update));setItemMenu(null);notify(message)}catch(e:any){notify(e?.message||'Não consegui salvar essa preferência.')}finally{setSavingPref(false)}}
 function removeFromLook(){if(!itemMenu)return;const next=look.filter(p=>p.id!==itemMenu.id);if(!isCompleteLook(next)){setSwap(itemMenu);setItemMenu(null);notify('Essa é uma peça essencial. Escolha outra para substituí-la.');return}if(anchorId===String(itemMenu.id))setAnchorId(null);setLook(next);setSaved(false);setItemMenu(null);setTryOnImage('');notify('Peça retirada deste look ✦')}
 async function generateTryOn(){if(!look.length)return;setTryOnBusy(true);setTryOnError('');setTryOnImage('');try{const image=await makeLookReference(look);const r=await fetch('/api/closet/try-on',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,avatarId,occasion,items:look.map(p=>({name:p.name,category:p.category,meta:p.meta}))})});const data=await r.json();if(!r.ok||!data?.ok||!data?.image)throw new Error(data?.message||'Não consegui vestir este look.');setTryOnImage(String(data.image))}catch(e:any){const raw=String(e?.message||'');setTryOnError(/credits|billing|quota/i.test(raw)?'A visualização vestida está temporariamente indisponível. Seu look continua salvo aqui.':raw||'Não consegui vestir este look agora.')}finally{setTryOnBusy(false)}}
 const complete=isCompleteLook(look),personalized=Object.keys(profile||{}).length>0;
 if(!session&&!building)return <main className={styles.page}><div className={styles.empty}><span>SEU LOOK</span><h1>Entre no closet primeiro.</h1><p>Seu guarda-roupa precisa estar conectado para o stylist montar uma combinação.</p><button onClick={()=>window.location.href='/closet'}>Voltar ao closet</button></div></main>;
 return <main className={styles.page}>
  <header className={styles.header}><button onClick={()=>window.location.href='/closet'}>‹</button><div><span>{anchorId?'COMEÇANDO POR UMA PEÇA':'STYLIST PESSOAL'}</span><strong>Para {occasion}</strong></div><button className={styles.more} onClick={()=>window.location.href='/closet/looks'}>♡</button></header>
  {!tryOn?<section className={styles.experience}>
   <div className={`${styles.stage} ${revealed&&!building?styles.stageOpen:''}`}><div className={styles.backdrop}/><div className={styles.glow}/><div className={styles.platform}/><div className={styles.lookArea}>{complete&&look.map((p,i)=><button key={p.id} className={`${styles.item} ${slot(p,i)}`} onClick={()=>openItem(p)} aria-label={`Opções para ${p.name}`}><img src={p.image} alt={p.name}/></button>)}</div>{!building&&!complete&&<div className={styles.invalid}><strong>Falta uma peça essencial.</strong><small>O stylist não revela um look incompleto.</small><button onClick={()=>window.location.href='/closet'}>Adicionar ao closet</button></div>}<i className={`${styles.curtain} ${styles.leftCurtain}`}/><i className={`${styles.curtain} ${styles.rightCurtain}`}/><div className={styles.stageCopy}>{building?'✦ combinando suas peças':complete?(anchorId?'✦ sua peça ficou fixa neste look':`✦ pronto para ${occasion.toLowerCase()}`):'✦ look incompleto'}</div></div>
   <div className={styles.reason}><span>{personalized?'BASEADO NO SEU PERFIL':'STYLIST V1'}</span><strong>{anchorId?'Uma peça escolhida + seu gosto + ocasião.':personalized?'Seu gosto + ocasião + harmonia.':'Ocasião + harmonia + regras de moda.'}</strong><small>Toque numa peça para trocar, retirar do look, montar outro conjunto a partir dela ou ensinar quando você costuma usá-la.</small></div>
   <div className={styles.actions}><button onClick={remix}>↻ {anchorId?'Outro com esta peça':'Sortear outro'}</button><button disabled={!complete} onClick={()=>{setTryOn(true);setTryOnError('')}}>♙ Ver vestido</button><button disabled={!complete||savingLook||saved} onClick={saveCurrentLook}>{saved?'♥ Salvo':savingLook?'Salvando…':'♡ Salvar look'}</button></div>
  </section>:<section className={styles.tryOnScreen}><TryOnStage pieces={look} models={avatarModels} avatarId={avatarId} image={tryOnImage} busy={tryOnBusy} error={tryOnError} onAvatarChange={id=>{setAvatarId(id);setTryOnImage('');setTryOnError('')}} onGenerate={generateTryOn} onSwap={p=>{setTryOn(false);openItem(p)}} onRemix={()=>{setTryOn(false);remix()}} onResetModel={()=>{setTryOnImage('');setTryOnError('')}} onClose={()=>setTryOn(false)}/></section>}
  {itemMenu&&<div className={styles.swapBackdrop} onClick={()=>setItemMenu(null)}><div className={`${styles.swapSheet} ${styles.itemSheet}`} onClick={e=>e.stopPropagation()}><div className={styles.swapHead}><div><span>ESSA PEÇA</span><strong>{itemMenu.name}</strong></div><button onClick={()=>setItemMenu(null)}>×</button></div><div className={styles.itemPreview}><img src={itemMenu.image} alt={itemMenu.name}/></div><div className={styles.itemOptions}><button onClick={()=>buildAround(itemMenu)}>✦ Montar outro look com esta peça</button><button onClick={()=>{setSwap(itemMenu);setItemMenu(null)}}>↻ Trocar por outra</button><button onClick={removeFromLook}>− Tirar deste look</button><button disabled={savingPref} onClick={()=>savePreference({frequency:'rare',only_occasions:[]},'Entendi: você usa pouco essa peça ✦')}>Uso pouco</button><button disabled={savingPref} onClick={()=>savePreference({frequency:'special',only_occasions:['Evento','Festa','Encontro','Igreja']},'Vou guardar essa peça para ocasiões especiais ✦')}>Só em ocasiões especiais</button><button disabled={savingPref} onClick={()=>savePreference({frequency:'special',only_occasions:['Evento']},'Entendi: essa peça fica para eventos especiais ✦')}>Só em casamentos/eventos</button><button disabled={savingPref} className={styles.avoidButton} onClick={()=>savePreference({frequency:'never',only_occasions:[]},'Não vou mais sugerir essa peça ✦')}>Não sugerir esta peça</button></div><label className={styles.noteField}>Observação para o stylist<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: só uso à noite, não gosto com tênis, uso mais em casamento..."/><button disabled={savingPref} onClick={()=>savePreference({note},'Observação salva. Vou lembrar disso ✦')}>Salvar observação</button></label></div></div>}
  {swap&&<div className={styles.swapBackdrop} onClick={()=>setSwap(null)}><div className={styles.swapSheet} onClick={e=>e.stopPropagation()}><div className={styles.swapHead}><div><span>TROCAR ITEM</span><strong>Escolha outra opção</strong></div><button onClick={()=>setSwap(null)}>×</button></div><div className={styles.swapGrid}>{candidates.slice(0,16).map(p=><button key={p.id} onClick={()=>applySwap(p)}><img src={p.image} alt={p.name}/></button>)}</div>{!candidates.length&&<p>Não há outra peça compatível desse tipo no closet.</p>}</div></div>}
  <div className={`${styles.toast} ${toast?styles.toastShow:''}`}>{toast}</div>
 </main>
}
