const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function cfg(env){return{url:String(env.CLOSET_SUPABASE_URL||env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,''),service:String(env.CLOSET_SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_SERVICE_ROLE_KEY||''),stripe:String(env.STRIPE_SECRET_KEY||''),secret:String(env.STRIPE_WEBHOOK_SECRET||'')}}
async function sb(c,path,init={}){const r=await fetch(`${c.url}${path}`,{...init,headers:{apikey:c.service,Authorization:`Bearer ${c.service}`,'Content-Type':'application/json',...(init.headers||{})}}),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error||`Supabase ${r.status}`);return d}
async function hmac(secret,message){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message));return Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function eq(a,b){if(!a||!b||a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
async function hash(text){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function sig(value){const out={v1:[]};for(const p of String(value||'').split(',')){const [k,v]=p.split('=',2);if(k==='t')out.t=v;if(k==='v1')out.v1.push(v)}return out}
async function stripeGet(c,path){const r=await fetch(`https://api.stripe.com/v1/${path}`,{headers:{Authorization:`Bearer ${c.stripe}`}}),d=await r.json();if(!r.ok)throw Error(d?.error?.message||'Stripe API error');return d}
async function record(c,{orderId,paymentId,eventId,status,amount,fee,method,raw,event}){return sb(c,'/rest/v1/rpc/closet_record_payment_event',{method:'POST',body:JSON.stringify({p_order_id:orderId,p_provider:'stripe_connect',p_provider_payment_id:paymentId,p_provider_event_id:eventId,p_status:status,p_amount:amount,p_fee:fee,p_method:method||'stripe',p_payload_hash:await hash(raw),p_summary:{stripe_event:event.type,payment_status:status,livemode:event.livemode}})})}
export async function onRequestPost({request,env}){const c=cfg(env);if(!c.url||!c.service||!c.stripe||!c.secret)return json({message:'Stripe webhook não configurado.'},503);const raw=await request.text(),parsed=sig(request.headers.get('stripe-signature'));if(!parsed.t||!parsed.v1.length)return json({message:'Assinatura ausente.'},401);const age=Math.abs(Date.now()/1000-Number(parsed.t));if(!Number.isFinite(age)||age>300)return json({message:'Assinatura expirada.'},401);const expected=await hmac(c.secret,`${parsed.t}.${raw}`);if(!parsed.v1.some(v=>eq(v,expected)))return json({message:'Assinatura inválida.'},401);let event;try{event=JSON.parse(raw)}catch{return json({message:'JSON inválido.'},400)};try{if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded'){const session=event.data?.object||{},orderId=String(session.client_reference_id||session.metadata?.closet_order_id||''),piId=String(session.payment_intent||'');if(orderId&&piId){const pi=await stripeGet(c,`payment_intents/${encodeURIComponent(piId)}?expand[]=latest_charge.balance_transaction`),charge=pi.latest_charge||{},bt=charge.balance_transaction||{},fee=typeof bt==='object'?Number(bt.fee||0)/100:0;await record(c,{orderId,paymentId:pi.id,eventId:event.id,status:pi.status==='succeeded'?'approved':pi.status,amount:Number(pi.amount_received||pi.amount||0)/100,fee,method:charge.payment_method_details?.type||'stripe',raw,event})}return json({ok:true})}
 if(event.type==='payment_intent.payment_failed'){const pi=event.data?.object||{},orderId=String(pi.metadata?.closet_order_id||'');if(orderId)await record(c,{orderId,paymentId:pi.id,eventId:event.id,status:'failed',amount:Number(pi.amount||0)/100,fee:0,method:'stripe',raw,event});return json({ok:true})}
 if(event.type==='charge.dispute.created'){const ch=event.data?.object||{},orderId=String(ch.metadata?.closet_order_id||'');if(orderId){const orders=await sb(c,`/rest/v1/closet_orders?select=seller_id,buyer_user_id&id=eq.${encodeURIComponent(orderId)}&limit=1`),o=orders?.[0];if(o)await sb(c,'/rest/v1/closet_buyer_risk_events',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({buyer_user_id:o.buyer_user_id,order_id:orderId,risk_type:'payment_chargeback_opened',severity:3,status:'open',metadata:{stripe_dispute_id:event.data?.object?.id}})});await sb(c,`/rest/v1/closet_payouts?order_id=eq.${encodeURIComponent(orderId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'held',hold_reason:'chargeback Stripe',updated_at:new Date().toISOString()})})}return json({ok:true})}
 return json({ok:true,ignored:event.type})}catch(e){return json({message:e?.message||'Falha ao processar evento Stripe.'},500)}}
