import {NextRequest,NextResponse} from 'next/server';

export const runtime='edge';

const base=(process.env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,'');
const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';

async function call(token:string,path:string,init:RequestInit){const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{apikey:anon,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})}});const t=await r.text();let data:any=null;try{data=t?JSON.parse(t):null}catch{data=t}if(!r.ok)throw new Error(data?.message||data?.error||`Supabase ${r.status}`);return data}

export async function POST(req:NextRequest){try{if(!base||!anon)return NextResponse.json({ok:false,message:'Marketplace não configurado.'},{status:503});const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return NextResponse.json({ok:false,message:'Sessão obrigatória.'},{status:401});const body=await req.json(),productId=String(body?.product_id||''),price=Number(body?.price||0),stock=Math.max(0,Math.floor(Number(body?.stock||0))),sku=body?.sku?String(body.sku):null,imageUrl=body?.image_url?String(body.image_url):null;if(!productId||!Number.isFinite(price)||price<0)return NextResponse.json({ok:false,message:'Produto e preço válidos são obrigatórios.'},{status:400});const variants=await call(token,'closet_product_variants',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({product_id:productId,sku,title:null,color:null,size:null,material:null,price,currency:'BRL',status:'active'})});const variant=variants?.[0];if(!variant?.id)throw new Error('Não foi possível criar a variante.');await call(token,'closet_product_inventory?on_conflict=variant_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({variant_id:variant.id,quantity_on_hand:stock,quantity_reserved:0,allow_backorder:false})});if(imageUrl)await call(token,'closet_product_media',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({product_id:productId,variant_id:variant.id,media_type:'image',url:imageUrl,position:0})});return NextResponse.json({ok:true,variant_id:variant.id})}catch(e:any){return NextResponse.json({ok:false,message:e?.message||'Não consegui completar o produto.'},{status:400})}}
