'use client';

import {useEffect,useMemo,useState} from 'react';
import {loadClosetItems,restoreClosetSession,type ClosetSession} from '../supabase';
import {loadStyleProfile} from '../styleProfile';
import styles from './stylist.module.css';

type Step='occasion'|'period'|'detail'|'palette';
type QuickOccasion='Igreja'|'Trabalho'|'Aula'|'Encontro'|'Festa'|'Evento'|'Passeio'|'Viagem';
type PaletteMode='auto'|'priority'|'strict';
const quickOccasions:QuickOccasion[]=['Igreja','Trabalho','Aula','Encontro','Festa','Evento','Passeio','Viagem'];
const details:Record<QuickOccasion,string[]>={Igreja:['Culto comum','Ministrar / servir','Evento especial'],Trabalho:['Dia normal','Reunião / apresentação','Evento profissional','Trabalho externo'],Aula:['Aula comum','Apresentação / seminário','Evento'],Encontro:['Casual','Jantar','Especial / mais arrumado'],Festa:['Casual','Arrumada','Formal'],Evento:['Casual arrumado','Cerimônia','Formal'],Passeio:['Passeio casual','Almoço / shopping','Jantar / noite'],Viagem:['Deslocamento','Passeio','Jantar / evento']};
const genericDetails=['Casual','Arrumado','Formal'];
const periods=[['manha','Manhã'],['tarde','Tarde'],['noite','Noite']] as const;
const basePalette=[['Preto','#171717'],['Grafite','#434343'],['Cinza','#7a7a78'],['Cinza claro','#c7c6c2'],['Branco','#f8f7f2'],['Off-white','#eee8d8'],['Bege','#d7c4a7'],['Caramelo','#a87143'],['Marrom','#6c4934'],['Vinho','#6f3840'],['Vermelho','#aa493f'],['Terracota','#a86145'],['Laranja','#c8793f'],['Amarelo','#d1aa42'],['Verde oliva','#74774d'],['Verde','#54705a'],['Verde escuro','#354c3d'],['Azul claro','#8db1ce'],['Azul','#567fa5'],['Azul-marinho','#27384f'],['Lilás','#a18cac'],['Roxo','#765b82'],['Rosa','#c98f98'],['Rosa claro','#ddb9bf']] as const;
const extraPalette=[['Areia','#d9c9aa'],['Nude','#d7b49e'],['Cáqui','#aa9b72'],['Chocolate','#4f3328'],['Café','#3b2922'],['Bordô','#612f3a'],['Marsala','#8a4b52'],['Mostarda','#b88b2e'],['Ferrugem','#a45232'],['Coral','#d97668'],['Pêssego','#e6aa83'],['Azul petróleo','#285b63'],['Azul royal','#315ca8'],['Azul celeste','#9ac8df'],['Turquesa','#42a6a4'],['Verde musgo','#59633d'],['Verde militar','#596044'],['Menta','#a9cbb7'],['Esmeralda','#28745a'],['Lavanda','#b8a7cb'],['Magenta','#a13d70'],['Fúcsia','#bd3f78']] as const;
function norm(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim()}
function normalizeColor(v:string){return v.trim().replace(/\s+/g,' ')}
function dressLabel(v:string){return ({formal:'Formal',social:'Social','social-casual':'Social casual',casual:'Casual',uniforme:'Uniforme',criativo:'Livre / criativo'} as Record<string,string>)[v]||v}

export default function StylistSetup(){
 const [session,setSession]=useState<ClosetSession|null>(null),[loading,setLoading]=useState(true),[step,setStep]=useState<Step>('occasion'),[anchor,setAnchor]=useState('');
 const [profile,setProfile]=useState<any>({});
 const [quickOccasion,setQuickOccasion]=useState<QuickOccasion|null>(null),[customOccasion,setCustomOccasion]=useState(''),[period,setPeriod]=useState(''),[detail,setDetail]=useState(''),[wardrobeColors,setWardrobeColors]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[paletteMode,setPaletteMode]=useState<PaletteMode>('auto'),[moreColors,setMoreColors]=useState(false);
 const progress=step==='occasion'?1:step==='period'?2:step==='detail'?3:4,occasion=customOccasion.trim()||quickOccasion||'',currentDetails=quickOccasion&&!customOccasion.trim()?details[quickOccasion]:genericDetails,canContinue=step==='occasion'?Boolean(occasion):step==='period'?Boolean(period):step==='detail'?Boolean(detail):true;
 const workProfile=profile?.work_profile||{},workContext=quickOccasion==='Trabalho'&&workProfile?.dress_code?`${workProfile.profession?`${workProfile.profession} · `:''}${dressLabel(workProfile.dress_code)}`:'';
 const summary=useMemo(()=>[occasion,period&&periods.find(x=>x[0]===period)?.[1],detail,workContext].filter(Boolean).join(' · '),[occasion,period,detail,workContext]);
 const closetSet=useMemo(()=>new Set(wardrobeColors.map(norm)),[wardrobeColors]),missingSelected=selected.filter(c=>!closetSet.has(norm(c))),visiblePalette=moreColors?[...basePalette,...extraPalette]:basePalette;
 useEffect(()=>{let alive=true;(async()=>{const q=new URLSearchParams(location.search);setAnchor(q.get('anchor')||'');const s=await restoreClosetSession();if(!alive)return;setSession(s);if(s){try{const [rows,p]=await Promise.all([loadClosetItems(s),loadStyleProfile(s)]);setWardrobeColors([...new Set(rows.map((r:any)=>normalizeColor(String(r.color||''))).filter(Boolean))]);setProfile(p||{})}catch{}}setLoading(false)})();return()=>{alive=false}},[]);
 function next(){if(step==='occasion')setStep('period');else if(step==='period')setStep('detail');else if(step==='detail')setStep('palette');else build()}
 function back(){if(step==='period')setStep('occasion');else if(step==='detail')setStep('period');else if(step==='palette')setStep('detail');else history.back()}
 function chooseOccasion(o:QuickOccasion){setQuickOccasion(o);setCustomOccasion('');setDetail('')}
 function typeOccasion(v:string){setCustomOccasion(v);if(v.trim())setQuickOccasion(null);setDetail('')}
 function toggleColor(c:string){if(paletteMode==='auto')setPaletteMode('priority');setSelected(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c])}
 function chooseAuto(){setPaletteMode('auto');setSelected([])}
 function build(){if(!occasion)return;const work=quickOccasion==='Trabalho'?{profession:String(workProfile?.profession||''),dress_code:String(workProfile?.dress_code||''),notes:String(workProfile?.notes||'')}:null;sessionStorage.setItem('closet_stylist_context',JSON.stringify({occasion,period,detail,colors:selected,paletteMode,work_profile:work,createdAt:new Date().toISOString()}));sessionStorage.setItem('closet_last_occasion',occasion);const params=new URLSearchParams({occasion});if(anchor)params.set('anchor',anchor);location.href=`/closet/look/?${params.toString()}`}
 if(loading)return <main className={styles.page}><div className={styles.loading}>Preparando seu stylist…</div></main>;
 if(!session)return <main className={styles.page}><section className={styles.empty}><span>STYLIST PESSOAL</span><h1>Entre no Closet primeiro.</h1><p>Seu guarda-roupa precisa estar conectado para montar um look.</p><button onClick={()=>location.href='/closet/'}>Voltar ao Closet</button></section></main>;
 return <main className={styles.page}><header><button onClick={back}>‹</button><div><span>STYLIST PESSOAL</span><strong>{anchor?'Complete sua peça':'Seu look de hoje'}</strong></div><button onClick={()=>location.href='/closet/'}>⌂</button></header><section className={styles.shell}><div className={styles.progress}><div style={{width:`${progress*25}%`}}/><span>{progress} de 4</span></div>
 {step==='occasion'&&<section className={styles.step}><span>1 · MOMENTO</span><h1>O que você vai fazer?</h1><p>{anchor?'Vou manter a peça escolhida e montar o restante a partir deste contexto.':'Use um atalho ou escreva livremente. O Stylist não fica preso a uma lista de ocasiões.'}</p><div className={styles.quickOccasions}>{quickOccasions.map(o=><button key={o} className={quickOccasion===o&&!customOccasion?styles.active:''} onClick={()=>chooseOccasion(o)}>{o}</button>)}</div><div className={styles.customOccasion}><label>Ou descreva do seu jeito</label><input value={customOccasion} onChange={e=>typeOccasion(e.target.value)} placeholder="Ex.: almoço de aniversário na casa de amigos"/><small>Casamento, show, palestra, parque, ensaio, reunião, consulta… escreva o que realmente vai acontecer.</small></div>{quickOccasion==='Trabalho'&&<div className={styles.profileContext}><span>SEU PERFIL DE TRABALHO</span>{workProfile?.dress_code?<><strong>{workContext}</strong><small>{workProfile.notes||'O Stylist vai usar esse dress code como regra-base para o look.'}</small></>:<><strong>Ainda não configurado</strong><small>Sem um dress code, “Trabalho” continua genérico.</small><button onClick={()=>location.href='/closet/style/'}>Definir meu trabalho</button></>}</div>}</section>}
 {step==='period'&&<section className={styles.step}><span>2 · HORÁRIO</span><h1>Que horas?</h1><p>Manhã, tarde e noite ajudam o motor a ajustar peso, formalidade e leitura das cores.</p><div className={styles.options}>{periods.map(([value,label])=><button key={value} className={period===value?styles.active:''} onClick={()=>setPeriod(value)}>{label}</button>)}</div></section>}
 {step==='detail'&&<section className={styles.step}><span>3 · CONTEXTO</span><h1>Como é esse momento?</h1><p>Uma última pista para o Stylist interpretar melhor “{occasion}”.</p><div className={styles.options}>{currentDetails.map(x=><button key={x} className={detail===x?styles.active:''} onClick={()=>setDetail(x)}>{x}</button>)}</div>{quickOccasion==='Trabalho'&&workProfile?.dress_code&&<div className={styles.contextNote}>Base permanente: <strong>{dressLabel(workProfile.dress_code)}</strong>{workProfile.profession?` · ${workProfile.profession}`:''}. A opção acima ajusta apenas o momento de hoje.</div>}</section>}
 {step==='palette'&&<section className={styles.step}><span>4 · PALETA DE HOJE</span><h1>Quais cores você quer usar?</h1><p>A cor orienta o look, mas não precisa tornar o guarda-roupa inutilizável.</p><div className={styles.paletteModes}><button className={paletteMode==='auto'?styles.active:''} onClick={chooseAuto}><strong>Stylist escolhe</strong><small>O motor decide a melhor harmonia.</small></button><button className={paletteMode==='priority'?styles.active:''} onClick={()=>setPaletteMode('priority')}><strong>Priorizar paleta</strong><small>Padrão recomendado. Usa suas cores e permite neutros/alternativas que harmonizem.</small></button><button className={paletteMode==='strict'?styles.active:''} onClick={()=>setPaletteMode('strict')}><strong>Paleta estrita</strong><small>Somente as cores escolhidas. Pode gerar lacunas.</small></button></div>{paletteMode!=='auto'&&<><div className={styles.paletteGrid}>{visiblePalette.map(([name,hex])=>{const has=closetSet.has(norm(name)),on=selected.includes(name);return <button key={name} title={`${name}${has?' · no seu Closet':' · você ainda não tem'}`} className={`${styles.swatchButton} ${on?styles.swatchActive:''}`} onClick={()=>toggleColor(name)}><i style={{background:hex}}>{on?<b>✓</b>:null}</i><span>{name}</span>{has?<small className={styles.hasDot}>•</small>:null}</button>})}</div><button type="button" className={styles.moreTones} onClick={()=>setMoreColors(v=>!v)}>{moreColors?'Ver cores principais':'Mais tons'} <span>{moreColors?'−':'+'}</span></button><small className={styles.paletteHint}>{paletteMode==='priority'?'O Stylist tenta usar essas cores primeiro. Se uma peça adequada não existir, ele procura uma alternativa harmoniosa no seu Closet antes de falar em Marketplace.':'Modo estrito: peças fora dessas cores não entram automaticamente no look.'}</small>{missingSelected.length>0&&<div className={styles.marketGap}><span>NÃO EXISTE NESTA COR</span><strong>{missingSelected.join(' + ')}</strong><p>Isso não significa que o look precise ficar incompleto. No modo Priorizar, o Stylist tenta uma alternativa harmoniosa antes de sugerir compra.</p></div>}</>}</section>}
 <div className={styles.summary}><span>SEU CONTEXTO</span><strong>{summary||'Vamos definir em poucos toques.'}</strong>{step==='palette'&&<small>{paletteMode==='auto'?'Paleta: Stylist escolhe':`${paletteMode==='strict'?'Paleta estrita':'Priorizar paleta'}: ${selected.length?selected.join(' + '):'nenhuma cor marcada'}`}</small>}</div><button className={styles.continue} disabled={!canContinue||(step==='palette'&&paletteMode!=='auto'&&!selected.length)} onClick={next}>{step==='palette'?'Montar meu look':'Continuar'}</button></section></main>
}
