'use client';

import {useEffect,useMemo,useState} from 'react';
import {loadClosetItems,restoreClosetSession,type ClosetSession} from '../supabase';
import {loadStyleProfile} from '../styleProfile';
import {loadSavedLooks,type SavedLook} from '../savedLooks';
import {forecastForDate,requestWeatherLocation,storedWeatherLocation,weatherStylistHint,type ClosetWeather} from '../weather';
import styles from './stylist.module.css';

type Step='occasion'|'period'|'detail'|'palette';
type QuickOccasion='Igreja'|'Trabalho'|'Aula'|'Encontro'|'Festa'|'Evento'|'Passeio'|'Viagem';
type PaletteMode='auto'|'priority'|'strict';
type StyleRoutine={id:string;title:string;occasion:string;detail?:string;period?:string;paletteMode?:PaletteMode;colors?:string[];work_profile?:Record<string,any>|null};

const quickOccasions:QuickOccasion[]=['Igreja','Trabalho','Aula','Encontro','Festa','Evento','Passeio','Viagem'];
const details:Record<QuickOccasion,string[]>={Igreja:['Culto comum','Ministrar / servir','Evento especial'],Trabalho:['Dia normal','Reunião / apresentação','Evento profissional','Trabalho externo'],Aula:['Aula comum','Apresentação / seminário','Evento'],Encontro:['Casual','Jantar','Especial / mais arrumado'],Festa:['Casual','Arrumada','Formal'],Evento:['Casual arrumado','Cerimônia','Formal'],Passeio:['Passeio casual','Almoço / shopping','Jantar / noite'],Viagem:['Deslocamento','Passeio','Jantar / evento']};
const genericDetails=['Casual','Arrumado','Formal'];
const periods=[['manha','Manhã'],['tarde','Tarde'],['noite','Noite']] as const;
const basePalette=[['Preto','#171717'],['Grafite','#434343'],['Cinza','#7a7a78'],['Cinza claro','#c7c6c2'],['Branco','#f8f7f2'],['Off-white','#eee8d8'],['Bege','#d7c4a7'],['Caramelo','#a87143'],['Marrom','#6c4934'],['Vinho','#6f3840'],['Vermelho','#aa493f'],['Terracota','#a86145'],['Laranja','#c8793f'],['Amarelo','#d1aa42'],['Verde oliva','#74774d'],['Verde','#54705a'],['Verde escuro','#354c3d'],['Azul claro','#8db1ce'],['Azul','#567fa5'],['Azul-marinho','#27384f'],['Lilás','#a18cac'],['Roxo','#765b82'],['Rosa','#c98f98'],['Rosa claro','#ddb9bf']] as const;
const extraPalette=[['Areia','#d9c9aa'],['Nude','#d7b49e'],['Cáqui','#aa9b72'],['Chocolate','#4f3328'],['Café','#3b2922'],['Bordô','#612f3a'],['Marsala','#8a4b52'],['Mostarda','#b88b2e'],['Ferrugem','#a45232'],['Coral','#d97668'],['Pêssego','#e6aa83'],['Azul petróleo','#285b63'],['Azul royal','#315ca8'],['Azul celeste','#9ac8df'],['Turquesa','#42a6a4'],['Verde musgo','#59633d'],['Verde militar','#596044'],['Menta','#a9cbb7'],['Esmeralda','#28745a'],['Lavanda','#b8a7cb'],['Magenta','#a13d70'],['Fúcsia','#bd3f78']] as const;

function norm(v:string){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/-/g,' ').replace(/\s+/g,' ').trim()}
function normalizeColor(v:string){return v.trim().replace(/\s+/g,' ')}
function dressLabel(v:string){return ({formal:'Formal',social:'Social','social-casual':'Social casual',casual:'Casual',uniforme:'Uniforme',criativo:'Livre / criativo'} as Record<string,string>)[v]||v}
function today(){const d=new Date(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${d.getFullYear()}-${m}-${day}`}
function currentPeriod(){const h=new Date().getHours();return h<12?'manha':h<18?'tarde':'noite'}
function periodLabel(v:string){return periods.find(x=>x[0]===v)?.[1]||v}
function greeting(){const h=new Date().getHours();return h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}
function defaultRoutine(id:string,work:any):StyleRoutine{const map:Record<string,StyleRoutine>={trabalho:{id:'trabalho',title:'Trabalho',occasion:'Trabalho',detail:'Dia normal',period:'auto',paletteMode:'auto',work_profile:work},igreja:{id:'igreja',title:'Igreja',occasion:'Igreja',detail:'Culto comum',period:'auto',paletteMode:'auto'},aula:{id:'aula',title:'Aula',occasion:'Aula',detail:'Aula comum',period:'auto',paletteMode:'auto'},eventos:{id:'eventos',title:'Eventos',occasion:'Evento',detail:'Casual arrumado',period:'auto',paletteMode:'auto'},lazer:{id:'lazer',title:'Dia a dia',occasion:'Passeio',detail:'Passeio casual',period:'auto',paletteMode:'auto'},academia:{id:'academia',title:'Academia',occasion:'Academia',detail:'Treino',period:'auto',paletteMode:'auto'}};return map[id]||{id,title:id,occasion:id,detail:'Casual',period:'auto',paletteMode:'auto'}}
function routinesFromProfile(profile:any){const work=profile?.work_profile||{};if(Array.isArray(profile?.style_routines)&&profile.style_routines.length)return profile.style_routines.map((r:any)=>({...defaultRoutine(String(r.id||r.occasion||'rotina'),work),...r,work_profile:r?.work_profile||(/trabalho/i.test(String(r.occasion||r.id))?work:null)})) as StyleRoutine[];const ids=Array.isArray(profile?.routine_contexts)?profile.routine_contexts:[];return ids.map((id:string)=>defaultRoutine(id,work))}
function routineUsage(){if(typeof window==='undefined')return{} as Record<string,number>;try{return JSON.parse(localStorage.getItem('closet.quickRoutineUsage')||'{}')||{}}catch{return{}}}
function bumpRoutine(id:string){try{const u=routineUsage();u[id]=Number(u[id]||0)+1;localStorage.setItem('closet.quickRoutineUsage',JSON.stringify(u))}catch{}}
function routineScore(r:StyleRoutine){const d=new Date(),day=d.getDay(),period=currentPeriod(),id=norm(`${r.id} ${r.occasion}`),usage=Number(routineUsage()[r.id]||0);let s=Math.min(6,usage*.55);if(/trabalho/.test(id)&&day>=1&&day<=5&&period!=='noite')s+=5;if(/aula/.test(id)&&day>=1&&day<=6&&period!=='noite')s+=3.5;if(/igreja/.test(id)&&day===0)s+=6;if(/academia/.test(id)&&(period==='manha'||period==='noite'))s+=2.5;if(/evento|festa/.test(id)&&([5,6].includes(day)||period==='noite'))s+=2;if(/lazer|passeio|dia a dia/.test(id)&&([0,6].includes(day)||period==='noite'))s+=1.8;if(r.period&&r.period!=='auto'&&r.period===period)s+=2.5;return s}

export default function StylistSetup(){
 const [session,setSession]=useState<ClosetSession|null>(null),[loading,setLoading]=useState(true),[step,setStep]=useState<Step>('occasion'),[anchor,setAnchor]=useState(''),[detailed,setDetailed]=useState(false);
 const [profile,setProfile]=useState<any>({}),[weather,setWeather]=useState<ClosetWeather|null>(null),[weatherBusy,setWeatherBusy]=useState(false),[weatherError,setWeatherError]=useState('');
 const [quickOccasion,setQuickOccasion]=useState<QuickOccasion|null>(null),[customOccasion,setCustomOccasion]=useState(''),[period,setPeriod]=useState(''),[detail,setDetail]=useState(''),[wardrobeColors,setWardrobeColors]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[paletteMode,setPaletteMode]=useState<PaletteMode>('auto'),[moreColors,setMoreColors]=useState(false),[showQuickPalette,setShowQuickPalette]=useState(false);
 const [savedLooks,setSavedLooks]=useState<SavedLook[]>([]),[pieceImages,setPieceImages]=useState<Record<string,string>>({});
 const routines=useMemo(()=>routinesFromProfile(profile),[profile]);
 const suggestedRoutine=useMemo(()=>routines.slice().sort((a,b)=>routineScore(b)-routineScore(a))[0]||null,[routines,profile]);
 const progress=step==='occasion'?1:step==='period'?2:step==='detail'?3:4,occasion=customOccasion.trim()||quickOccasion||'',currentDetails=quickOccasion&&!customOccasion.trim()?details[quickOccasion]:genericDetails,canContinue=step==='occasion'?Boolean(occasion):step==='period'?Boolean(period):step==='detail'?Boolean(detail):true;
 const workProfile=profile?.work_profile||{},workContext=quickOccasion==='Trabalho'&&workProfile?.dress_code?`${workProfile.profession?`${workProfile.profession} · `:''}${dressLabel(workProfile.dress_code)}`:'';
 const summary=useMemo(()=>[occasion,period&&periodLabel(period),detail,workContext].filter(Boolean).join(' · '),[occasion,period,detail,workContext]);
 const closetSet=useMemo(()=>new Set(wardrobeColors.map(norm)),[wardrobeColors]),missingSelected=selected.filter(c=>!closetSet.has(norm(c))),visiblePalette=moreColors?[...basePalette,...extraPalette]:basePalette;
 const recentLooks=useMemo(()=>savedLooks.slice().sort((a,b)=>new Date(b.last_worn_at||b.updated_at||b.created_at||0).getTime()-new Date(a.last_worn_at||a.updated_at||a.created_at||0).getTime()).slice(0,4),[savedLooks]);
 async function loadWeather(loc:{lat:number;lon:number}){setWeatherBusy(true);setWeatherError('');try{setWeather(await forecastForDate(today(),loc))}catch(e:any){setWeatherError(e?.message||'Não consegui consultar o clima.')}finally{setWeatherBusy(false)}}
 async function enableWeather(){try{const loc=await requestWeatherLocation();await loadWeather(loc)}catch(e:any){setWeatherError(e?.message||'Permita a localização para considerar o clima.')}}
 useEffect(()=>{let alive=true;(async()=>{const q=new URLSearchParams(location.search),a=q.get('anchor')||'';setAnchor(a);if(a||q.get('detailed')==='1')setDetailed(true);const s=await restoreClosetSession();if(!alive)return;setSession(s);if(s){try{const [rows,p,looks]=await Promise.all([loadClosetItems(s),loadStyleProfile(s),loadSavedLooks(s).catch(()=>[])]);if(!alive)return;setWardrobeColors([...new Set(rows.map((r:any)=>normalizeColor(String(r.color||''))).filter(Boolean))]);setPieceImages(Object.fromEntries(rows.map((r:any)=>[String(r.id),String(r.image||'')]))) ;setSavedLooks(looks);setProfile(p||{});const loc=storedWeatherLocation();if(loc)loadWeather(loc)}catch{}}setLoading(false)})();return()=>{alive=false}},[]);
 function weatherContext(){return weather?{date:weather.date,label:weather.label,tempMax:weather.tempMax,tempMin:weather.tempMin,feelsMax:weather.feelsMax,feelsMin:weather.feelsMin,rainChance:weather.rainChance,rainMm:weather.rainMm,windMax:weather.windMax,lat:weather.lat,lon:weather.lon,hint:weatherStylistHint(weather)}:null}
 function goToLook(input:{occasion:string;period:string;detail:string;colors:string[];paletteMode:PaletteMode;work_profile?:any;routine_id?:string;quick?:boolean}){const context={...input,weather:weatherContext(),thermal_sensitivity:Number(profile?.thermal_sensitivity??3),createdAt:new Date().toISOString()};sessionStorage.setItem('closet_stylist_context',JSON.stringify(context));sessionStorage.setItem('closet_last_occasion',input.occasion);const params=new URLSearchParams({occasion:input.occasion});if(weather){if(weather.tempMax!=null)params.set('wxMax',String(weather.tempMax));if(weather.tempMin!=null)params.set('wxMin',String(weather.tempMin));if(weather.rainChance!=null)params.set('wxRain',String(weather.rainChance));if(weather.label)params.set('wxLabel',weather.label)}if(anchor)params.set('anchor',anchor);location.href=`/closet/look/?${params.toString()}`}
 function quickBuild(r:StyleRoutine){bumpRoutine(r.id);goToLook({occasion:r.occasion,period:r.period&&r.period!=='auto'?r.period:currentPeriod(),detail:r.detail||'Rotina padrão',colors:selected,paletteMode,work_profile:r.work_profile||(/trabalho/i.test(r.occasion)?workProfile:null),routine_id:r.id,quick:true})}
 function adjustRoutine(r:StyleRoutine){setQuickOccasion((quickOccasions.find(x=>norm(x)===norm(r.occasion))||null) as QuickOccasion|null);setCustomOccasion(quickOccasions.some(x=>norm(x)===norm(r.occasion))?'':r.occasion);setPeriod(r.period&&r.period!=='auto'?r.period:currentPeriod());setDetail(r.detail||'Casual');setDetailed(true);setStep('period')}
 function next(){if(step==='occasion')setStep('period');else if(step==='period')setStep('detail');else if(step==='detail')setStep('palette');else buildDetailed()}
 function back(){if(!detailed){history.back();return}if(step==='period')setStep('occasion');else if(step==='detail')setStep('period');else if(step==='palette')setStep('detail');else if(!anchor&&routines.length)setDetailed(false);else history.back()}
 function chooseOccasion(o:QuickOccasion){setQuickOccasion(o);setCustomOccasion('');setDetail('')}
 function typeOccasion(v:string){setCustomOccasion(v);if(v.trim())setQuickOccasion(null);setDetail('')}
 function toggleColor(c:string){if(paletteMode==='auto')setPaletteMode('priority');setSelected(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c])}
 function chooseAuto(){setPaletteMode('auto');setSelected([])}
 function buildDetailed(){if(!occasion)return;const work=quickOccasion==='Trabalho'?{profession:String(workProfile?.profession||''),dress_code:String(workProfile?.dress_code||''),notes:String(workProfile?.notes||'')}:null;goToLook({occasion,period,detail,colors:selected,paletteMode,work_profile:work,quick:false})}
 if(loading)return <main className={styles.page}><div className={styles.loading}>Preparando seu stylist…</div></main>;
 if(!session)return <main className={styles.page}><section className={styles.empty}><span>STYLIST PESSOAL</span><h1>Entre no Closet primeiro.</h1><p>Seu guarda-roupa precisa estar conectado para montar um look.</p><button onClick={()=>location.href='/closet/'}>Voltar ao Closet</button></section></main>;
 if(!detailed&&routines.length&&!anchor)return <main className={styles.page}><header><button onClick={()=>history.back()}>‹</button><div><span>STYLIST PESSOAL</span><strong>Hoje</strong></div><button onClick={()=>location.href='/closet/'}>⌂</button></header><section className={`${styles.shell} ${styles.quickShell}`}>
  <section className={styles.todayHero}><div><span>STYLIST PESSOAL</span><h1>{greeting()}.<br/>O que vamos vestir?</h1><p>Seu perfil, clima, rotina e memória já estão prontos. Você só muda o que for diferente hoje.</p></div>{weather?<div className={styles.weatherCapsule}><strong>{weather.label}{weather.tempMax!=null?` · ${Math.round(weather.tempMax)}°`:''}</strong><small>{weatherStylistHint(weather)||'Clima conectado'}{weather.rainChance!=null?` · ${Math.round(weather.rainChance)}% de chuva`:''}</small></div>:<button className={styles.weatherLink} disabled={weatherBusy} onClick={enableWeather}>{weatherBusy?'Consultando clima…':'Usar clima da minha localização'}</button>}</section>
  {suggestedRoutine&&<section className={styles.primarySuggestion}><div className={styles.primaryMeta}><span>SUGESTÃO PARA AGORA</span><small>Baseado na sua rotina + {periodLabel(currentPeriod()).toLowerCase()}{weather?' + clima de hoje':''}</small></div><div className={styles.primaryBody}><div><h2>{suggestedRoutine.title}</h2><p>{suggestedRoutine.detail||'Contexto padrão'} · {suggestedRoutine.period&&suggestedRoutine.period!=='auto'?periodLabel(suggestedRoutine.period):periodLabel(currentPeriod())}</p>{/trabalho/i.test(suggestedRoutine.occasion)&&suggestedRoutine.work_profile?.dress_code&&<small>{suggestedRoutine.work_profile?.profession?`${suggestedRoutine.work_profile.profession} · `:''}{dressLabel(String(suggestedRoutine.work_profile.dress_code))}</small>}</div><button onClick={()=>quickBuild(suggestedRoutine)}>Montar look <b>→</b></button></div><button className={styles.primaryAdjust} onClick={()=>adjustRoutine(suggestedRoutine)}>Ajustar só hoje</button></section>}
  <section className={styles.quickSection}><div className={styles.sectionHead}><div><span>MINHAS ROTINAS</span><strong>Escolha outro contexto</strong></div><button onClick={()=>location.href='/closet/style/'}>Editar</button></div><div className={styles.routineRail}>{routines.map(r=><article key={r.id} className={`${styles.miniRoutine} ${suggestedRoutine?.id===r.id?styles.miniRoutineSuggested:''}`}><button className={styles.miniRoutineMain} onClick={()=>quickBuild(r)}><span>{suggestedRoutine?.id===r.id?'AGORA':'ROTINA'}</span><h3>{r.title}</h3><p>{r.detail||'Contexto padrão'}</p><small>{r.period&&r.period!=='auto'?periodLabel(r.period):periodLabel(currentPeriod())}</small><b>→</b></button><button className={styles.miniRoutineMenu} onClick={()=>adjustRoutine(r)} aria-label={`Ajustar ${r.title}`}>•••</button></article>)}<button className={styles.addRoutine} onClick={()=>location.href='/closet/style/'}><b>＋</b><span>Nova rotina</span></button></div></section>
  <section className={styles.quickSettings}><button className={styles.compactSetting} onClick={()=>setShowQuickPalette(v=>!v)}><div><span>PALETA DE HOJE</span><strong>{paletteMode==='auto'?'Stylist escolhe':selected.length?selected.join(' + '):'Escolher cores'}</strong></div><b>{showQuickPalette?'−':'›'}</b></button>{showQuickPalette&&<div className={styles.quickPaletteBody}><div className={styles.paletteModes}><button className={paletteMode==='auto'?styles.active:''} onClick={chooseAuto}><strong>Automática</strong><small>Stylist decide.</small></button><button className={paletteMode==='priority'?styles.active:''} onClick={()=>setPaletteMode('priority')}><strong>Priorizar</strong><small>Usa suas cores primeiro.</small></button><button className={paletteMode==='strict'?styles.active:''} onClick={()=>setPaletteMode('strict')}><strong>Estrita</strong><small>Só cores marcadas.</small></button></div>{paletteMode!=='auto'&&<div className={styles.paletteGrid}>{basePalette.map(([name,hex])=>{const has=closetSet.has(norm(name)),on=selected.includes(name);return <button key={name} className={`${styles.swatchButton} ${on?styles.swatchActive:''}`} onClick={()=>toggleColor(name)}><i style={{background:hex}}>{on?<b>✓</b>:null}</i><span>{name}</span>{has?<small className={styles.hasDot}>•</small>:null}</button>})}</div>}</div>}</section>
  <div className={styles.secondaryActions}><button onClick={()=>{setDetailed(true);setStep('occasion')}}>Outra ocasião</button><span>·</span><button onClick={()=>location.href='/closet/manual/'}>Montar manualmente</button></div>
  {recentLooks.length>0&&<section className={styles.quickSection}><div className={styles.sectionHead}><div><span>RECENTES</span><strong>Looks que você já salvou</strong></div><button onClick={()=>location.href='/closet/looks/'}>Ver todos</button></div><div className={styles.recentRail}>{recentLooks.map(look=><button key={look.id} className={styles.recentCard} onClick={()=>location.href='/closet/looks/'}><div>{(look.item_ids||[]).slice(0,3).map(id=>pieceImages[String(id)]?<img key={id} src={pieceImages[String(id)]} alt=""/>:null)}</div><strong>{look.occasion}</strong><small>{look.last_worn_at?'Usado recentemente':'Salvo recentemente'}</small></button>)}</div></section>}
 </section></main>;
 return <main className={styles.page}><header><button onClick={back}>‹</button><div><span>STYLIST PESSOAL</span><strong>{anchor?'Complete sua peça':'Ajustar look'}</strong></div><button onClick={()=>location.href='/closet/'}>⌂</button></header><section className={styles.shell}><div className={styles.progress}><div style={{width:`${progress*25}%`}}/><span>{progress} de 4</span></div>
 {step==='occasion'&&<section className={styles.step}><span>1 · MOMENTO</span><h1>O que você vai fazer?</h1><p>{anchor?'Vou manter a peça escolhida e montar o restante a partir deste contexto.':'Esse é o modo detalhado para exceções, eventos diferentes ou quando você quiser mudar sua rotina padrão.'}</p><div className={styles.quickOccasions}>{quickOccasions.map(o=><button key={o} className={quickOccasion===o&&!customOccasion?styles.active:''} onClick={()=>chooseOccasion(o)}>{o}</button>)}</div><div className={styles.customOccasion}><label>Ou descreva do seu jeito</label><input value={customOccasion} onChange={e=>typeOccasion(e.target.value)} placeholder="Ex.: almoço de aniversário na casa de amigos"/><small>Casamento, show, palestra, parque, ensaio, reunião, consulta… escreva o que realmente vai acontecer.</small></div>{quickOccasion==='Trabalho'&&<div className={styles.profileContext}><span>SEU PERFIL DE TRABALHO</span>{workProfile?.dress_code?<><strong>{workContext}</strong><small>{workProfile.notes||'O Stylist usa esse dress code como regra-base.'}</small></>:<><strong>Ainda não configurado</strong><button onClick={()=>location.href='/closet/style/'}>Definir meu trabalho</button></>}</div>}</section>}
 {step==='period'&&<section className={styles.step}><span>2 · HORÁRIO</span><h1>Que horas?</h1><p>Altere apenas se o momento de hoje for diferente da sua rotina.</p><div className={styles.options}>{periods.map(([value,label])=><button key={value} className={period===value?styles.active:''} onClick={()=>setPeriod(value)}>{label}</button>)}</div><div className={styles.profileContext}><span>CLIMA DE HOJE</span>{weather?<><strong>{weather.label}{weather.tempMin!=null&&weather.tempMax!=null?` · ${Math.round(weather.tempMin)}° a ${Math.round(weather.tempMax)}°`:''}</strong><small>{weatherStylistHint(weather)||'Previsão conectada ao Stylist.'}</small></>:<><strong>{weatherBusy?'Consultando o clima…':'Clima ainda não conectado'}</strong><small>{weatherError||'Ative a localização para o Stylist considerar temperatura e chuva.'}</small><button disabled={weatherBusy} onClick={enableWeather}>{weatherBusy?'Consultando…':'Usar clima da minha localização'}</button></>}</div></section>}
 {step==='detail'&&<section className={styles.step}><span>3 · CONTEXTO</span><h1>Como é esse momento?</h1><div className={styles.options}>{currentDetails.map(x=><button key={x} className={detail===x?styles.active:''} onClick={()=>setDetail(x)}>{x}</button>)}</div>{quickOccasion==='Trabalho'&&workProfile?.dress_code&&<div className={styles.contextNote}>Base permanente: <strong>{dressLabel(workProfile.dress_code)}</strong>{workProfile.profession?` · ${workProfile.profession}`:''}.</div>}</section>}
 {step==='palette'&&<section className={styles.step}><span>4 · PALETA DE HOJE</span><h1>Quer mudar as cores?</h1><p>Se não quiser decidir, deixe o Stylist escolher.</p><div className={styles.paletteModes}><button className={paletteMode==='auto'?styles.active:''} onClick={chooseAuto}><strong>Stylist escolhe</strong><small>O motor decide a harmonia.</small></button><button className={paletteMode==='priority'?styles.active:''} onClick={()=>setPaletteMode('priority')}><strong>Priorizar paleta</strong><small>Usa suas cores primeiro.</small></button><button className={paletteMode==='strict'?styles.active:''} onClick={()=>setPaletteMode('strict')}><strong>Paleta estrita</strong><small>Somente as cores escolhidas.</small></button></div>{paletteMode!=='auto'&&<><div className={styles.paletteGrid}>{visiblePalette.map(([name,hex])=>{const has=closetSet.has(norm(name)),on=selected.includes(name);return <button key={name} className={`${styles.swatchButton} ${on?styles.swatchActive:''}`} onClick={()=>toggleColor(name)}><i style={{background:hex}}>{on?<b>✓</b>:null}</i><span>{name}</span>{has?<small className={styles.hasDot}>•</small>:null}</button>})}</div><button type="button" className={styles.moreTones} onClick={()=>setMoreColors(v=>!v)}>{moreColors?'Ver cores principais':'Mais tons'} <span>{moreColors?'−':'+'}</span></button>{missingSelected.length>0&&<div className={styles.marketGap}><span>NÃO EXISTE NESTA COR</span><strong>{missingSelected.join(' + ')}</strong><p>No modo Priorizar, o Stylist tenta uma alternativa harmoniosa antes de sugerir compra.</p></div>}</>}</section>}
 <div className={styles.summary}><span>SEU CONTEXTO</span><strong>{summary||'Vamos definir em poucos toques.'}</strong>{weather&&<small>Clima: {weatherStylistHint(weather)||weather.label}</small>}</div><button className={styles.continue} disabled={!canContinue||(step==='palette'&&paletteMode!=='auto'&&!selected.length)} onClick={next}>{step==='palette'?'Montar meu look':'Continuar'}</button></section></main>
}
