'use client'
import {FormEvent,useState} from 'react'

const cases=[['ministerio','Meu ministério tentou dividir','Ensaio, culto ou apresentação.'],['segunda-voz','Tentei fazer uma segunda voz','Gravação individual, dueto ou collab.'],['funcionou','A divisão funcionou bem','Quero entender por que deu certo.'],['preciso-de-divisao','Não sabemos como dividir','Envie a melodia e explique a formação.']]
const appearances=[['video','Vídeo e áudio','Meu rosto pode aparecer.'],['blur','Vídeo desfocado','Minha imagem deve ser descaracterizada.'],['audio','Somente áudio','Não autorizo exibir as imagens.']]
const MAX_FILE_SIZE=1024*1024*1024,CHUNK_SIZE=8*1024*1024

function sendChunk(url:string,file:File,start:number){return new Promise<{done:boolean,fileId?:string}>((resolve,reject)=>{const end=Math.min(start+CHUNK_SIZE,file.size),x=new XMLHttpRequest();x.open('PUT',url);x.setRequestHeader('Content-Type',file.type);x.setRequestHeader('Content-Range',`bytes ${start}-${end-1}/${file.size}`);x.onerror=()=>reject(new Error('A conexão foi interrompida. Tente novamente.'));x.onload=()=>{if(x.status===308)return resolve({done:false});let data:any={};try{data=JSON.parse(x.responseText)}catch{};if(x.status>=200&&x.status<300&&data.id)return resolve({done:true,fileId:data.id});reject(new Error(data?.error?.message||'O Google Drive recusou o arquivo.'))};x.send(file.slice(start,end))})}

export default function Formulario(){
 const [category,setCategory]=useState(''),[appearance,setAppearance]=useState(''),[materialType,setMaterialType]=useState<'file'|'link'>('file'),[file,setFile]=useState<File|null>(null),[state,setState]=useState('idle'),[message,setMessage]=useState(''),[progress,setProgress]=useState(0),[protocol,setProtocol]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(materialType==='file'&&!file)return setMessage('Escolha um vídeo ou áudio.');if(file&&file.size>MAX_FILE_SIZE)return setMessage('O arquivo deve ter no máximo 1 GB.');const form=e.currentTarget,data=new FormData(form),payload:any=Object.fromEntries(data.entries());delete payload.file;setState('sending');setMessage('Registrando suas informações…');setProgress(2)
  try{
   const r=await fetch('/api/divisoes/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,materialType,category,appearance,fileName:file?.name||'',fileType:file?.type||'',fileSize:file?.size||0})}),created=await r.json();if(!r.ok)throw new Error(created.message||'Não foi possível iniciar o envio.')
   if(created.requiresUpload){
    const prep=await fetch(`/api/divisoes/upload?id=${encodeURIComponent(created.id)}&token=${encodeURIComponent(created.uploadToken)}`,{method:'POST'}),session=await prep.json();if(!prep.ok||!session.uploadUrl)throw new Error(session.message||'Não foi possível preparar o envio.')
    setMessage('Enviando direto ao Google Drive… não feche a página.');let start=0,fileId=''
    while(file&&start<file.size){const result=await sendChunk(session.uploadUrl,file,start);start=Math.min(start+CHUNK_SIZE,file.size);setProgress(Math.max(3,Math.round(start/file.size*96)));if(result.done){fileId=result.fileId||'';break}}
    if(!fileId)throw new Error('O Drive não confirmou a conclusão do envio.')
    const confirm=await fetch(`/api/divisoes/upload?id=${encodeURIComponent(created.id)}&token=${encodeURIComponent(created.uploadToken)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileId})}),confirmed=await confirm.json();if(!confirm.ok)throw new Error(confirmed.message||'Não foi possível confirmar o arquivo.')
   }
   setProtocol(created.id);setProgress(100);setState('success');setMessage('Seu material chegou e entrou na seleção do quadro.');form.reset();setFile(null);setCategory('');setAppearance('');setMaterialType('file')
  }catch(err:any){setState('error');setMessage(err?.message||'Ocorreu um erro. Tente novamente.')}}
 if(state==='success')return <div className="msd-success"><div>✓</div><i>MATERIAL RECEBIDO</i><h3>Agora é comigo.</h3><p>{message}</p><small>Protocolo: {protocol}</small><button onClick={()=>{setState('idle');setMessage('');setProgress(0)}}>Enviar outro caso</button></div>
 return <form className="msd-form" onSubmit={submit}>
  <fieldset disabled={state==='sending'}><legend>1. Quem está enviando?</legend><div className="msd-grid"><label>Seu nome completo<input name="name" required maxLength={120}/></label><label>WhatsApp<input name="whatsapp" required inputMode="tel" placeholder="(71) 99999-9999"/></label><label>Instagram<input name="instagram" placeholder="@seuperfil"/></label><label>Ministério ou igreja<input name="ministry" placeholder="Opcional"/></label><label className="wide">Cidade e estado<input name="city" required placeholder="Salvador, BA"/></label><input className="trap" name="website" tabIndex={-1} autoComplete="off"/></div></fieldset>
  <fieldset disabled={state==='sending'}><legend>2. Qual é o seu caso?</legend><div className="msd-choices">{cases.map(([v,t,d])=><label className={category===v?'chosen':''} key={v}><input type="radio" name="case" checked={category===v} onChange={()=>setCategory(v)} required/><strong>{t}</strong><small>{d}</small></label>)}</div></fieldset>
  <fieldset disabled={state==='sending'}><legend>3. Música e dificuldade</legend><div className="msd-grid"><label>Nome da música<input name="song" required/></label><label>Intérprete ou versão utilizada<input name="songVersion" required/></label><label>Tom, se souber<input name="key" placeholder="Ex.: F#"/></label><label>Fonte do acompanhamento<select name="audioSource" required defaultValue=""><option value="" disabled>Selecione</option><option value="acapella">A cappella</option><option value="instrumento-proprio">Instrumento gravado por nós</option><option value="banda-culto">Banda ao vivo ou culto</option><option value="playback">Playback/instrumental pronto</option><option value="outro">Outro</option></select></label><label className="wide">O que você quer que eu analise?<textarea name="question" required maxLength={1200} rows={5} placeholder="Conte onde vocês se perdem ou qual dúvida querem resolver."/></label></div></fieldset>
  <fieldset disabled={state==='sending'}><legend>4. Envie o trecho</legend><div className="msd-choices msd-send-modes"><label className={materialType==='file'?'chosen':''}><input type="radio" name="materialMode" checked={materialType==='file'} onChange={()=>setMaterialType('file')}/><strong>Enviar arquivo</strong><small>Vídeo ou áudio salvo no aparelho.</small></label><label className={materialType==='link'?'chosen':''}><input type="radio" name="materialMode" checked={materialType==='link'} onChange={()=>{setMaterialType('link');setFile(null)}}/><strong>Enviar link</strong><small>Instagram, YouTube, TikTok ou Drive.</small></label></div>{materialType==='file'?<><label className="msd-drop"><input name="file" type="file" required accept="video/mp4,video/quicktime,video/webm,audio/mpeg,audio/mp4,audio/wav,audio/x-m4a" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>↑</b><strong>{file?file.name:'Escolher vídeo ou áudio'}</strong><small>{file?`${(file.size/1048576).toFixed(1)} MB`:'MP4, MOV, WEBM, MP3, M4A ou WAV · até 1 GB'}</small></label><p className="msd-hint">O arquivo vai direto para o Google Drive do Foco em Canto. Mantenha a página aberta até concluir.</p></>:<div className="msd-grid msd-link-field"><label className="wide">Link público do material<input name="materialUrl" type="url" required placeholder="https://instagram.com/..."/><small>Confira se abre sem pedir senha ou autorização de acesso.</small></label></div>}</fieldset>
  <fieldset disabled={state==='sending'}><legend>5. Como podemos mostrar?</legend><div className="msd-appear">{appearances.map(([v,t,d])=><label className={appearance===v?'chosen':''} key={v}><input type="radio" name="show" checked={appearance===v} onChange={()=>setAppearance(v)} required/><strong>{t}</strong><small>{d}</small></label>)}</div><div className="msd-checks"><label><input type="checkbox" name="allowIdentification" value="sim"/>Autorizo citar meu nome, perfil e/ou ministério.</label><label><input type="checkbox" name="participantConsent" value="sim" required/>Tenho autorização das pessoas identificáveis presentes.</label><label><input type="checkbox" name="minorConsent" value="sim" required/>Não há menores sem autorização expressa do responsável.</label><label><input type="checkbox" name="rightsDeclaration" value="sim" required/>Gravei o material ou tenho permissão de quem gravou ou publicou.</label><label><input type="checkbox" name="editingPermission" value="sim" required/>Autorizo recortar, editar, comentar e utilizar o material em conteúdos educativos, promocionais e monetizados do Foco em Canto, respeitando a exibição escolhida.</label><label><input type="checkbox" name="termsAccepted" value="sim" required/>Li e aceito os <a href="#termos">termos de participação</a>.</label><label><input type="checkbox" name="updatesOptIn" value="sim"/>Quero receber avisos do quadro pelo WhatsApp.</label></div></fieldset>
  <details className="msd-terms" id="termos"><summary>Termos de participação e uso do material</summary><div><p><b>Seleção.</b> O envio é voluntário e não garante análise, publicação ou prazo de resposta.</p><p><b>Licença.</b> Você concede ao Foco em Canto licença gratuita, não exclusiva e por prazo indeterminado para armazenar, editar, comentar e publicar o material em seus canais, inclusive em conteúdo monetizado, dentro da exibição escolhida. A interrupção de usos futuros pode ser solicitada em suporte@focoemcanto.com.</p><p><b>Terceiros.</b> Você declara possuir as autorizações necessárias das pessoas presentes e dos responsáveis por eventuais menores.</p><p><b>Música.</b> A autorização cobre sua imagem, voz e gravação, mas não transfere direitos de composições, playbacks ou fonogramas de terceiros.</p><p><b>Dados.</b> Os dados serão usados para administrar a seleção, contato e comprovação das autorizações. Avisos por WhatsApp dependem da opção específica. Consulte a <a href="/privacy/">Política de Privacidade</a>.</p><p>Versão 03/09/2026.</p></div></details>
  {state==='sending'&&<div className="msd-progress"><p><span>{message}</span><b>{progress}%</b></p><div><i style={{width:`${progress}%`}}/></div></div>}{message&&state!=='sending'&&<p className="msd-error">{message}</p>}<button className="msd-submit" disabled={state==='sending'}>{state==='sending'?'Enviando material…':'Enviar minha divisão'}</button><small className="msd-note">Mantenha esta página aberta até a confirmação.</small>
 </form>
}
