const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function cfg(env){return{url:String(env.CLOSET_SUPABASE_URL||env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,''),anon:String(env.CLOSET_SUPABASE_ANON_KEY||env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''),service:String(env.CLOSET_SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_SERVICE_ROLE_KEY||'')}}
async function sb(c,path,token,init={}){const r=await fetch(`${c.url}${path}`,{...init,headers:{apikey:c.service||c.anon,Authorization:`Bearer ${token}`,...(init.headers||{})}}),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error||`Supabase ${r.status}`);return d}
function ext(name,type){const byName=String(name||'').split('.').pop()?.toLowerCase();if(byName&&/^(jpg|jpeg|png|webp|heic|heif|mp4|mov|webm|pdf)$/.test(byName))return byName;return type==='application/pdf'?'pdf':type==='image/png'?'png':type==='image/webp'?'webp':type?.startsWith('video/')?'mp4':'jpg'}
async function sha256(buffer){const h=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function cleanup(c,path){try{await sb(c,`/storage/v1/object/closet-marketplace-private/${path.split('/').map(encodeURIComponent).join('/')}`,c.service,{method:'DELETE'})}catch{}}
export async function onRequestPost({request,env}){const c=cfg(env),auth=request.headers.get('Authorization')||'',token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!c.url||!c.anon||!c.service)return json({message:'Backend de evidências não configurado.'},503);if(!token)return json({message:'Não autorizado.'},401);let uploadedPath='';try{const user=await sb(c,'/auth/v1/user',token),form=await request.formData(),disputeId=String(form.get('dispute_id')||''),caption=String(form.get('caption')||'').trim().slice(0,500),file=form.get('file');if(!user?.id||!disputeId||!(file instanceof File))return json({message:'Disputa e arquivo são obrigatórios.'},400);if(file.size<=0)return json({message:'O arquivo está vazio.'},400);if(file.size>25*1024*1024)return json({message:'Arquivo maior que 25 MB.'},413);if(!(/^image\/(jpeg|png|webp|heic|heif)$|^video\/(mp4|quicktime|webm)$|^application\/pdf$/.test(file.type||'')))return json({message:'Formato não permitido. Envie foto, vídeo ou PDF.'},415);
const visible=await sb(c,`/rest/v1/closet_disputes?select=id,status&id=eq.${encodeURIComponent(disputeId)}&limit=1`,token);if(!Array.isArray(visible)||!visible[0])return json({message:'Disputa não encontrada ou sem acesso.'},404);if(['decided','closed','cancelled'].includes(String(visible[0].status)))return json({message:'Este caso já foi encerrado e não aceita novas evidências.'},409);
const existing=await sb(c,`/rest/v1/closet_dispute_evidence?select=id&dispute_id=eq.${encodeURIComponent(disputeId)}&limit=25`,token);if(Array.isArray(existing)&&existing.length>=20)return json({message:'Este caso atingiu o limite de 20 evidências. Use a conversa para complementar as informações ou aguarde a mediação.'},409);
const bytes=await file.arrayBuffer(),hash=await sha256(bytes);if(Array.isArray(existing)&&existing.length){const duplicate=await sb(c,`/rest/v1/closet_dispute_evidence?select=id&dispute_id=eq.${encodeURIComponent(disputeId)}&content_hash=eq.${encodeURIComponent(hash)}&limit=1`,token);if(Array.isArray(duplicate)&&duplicate[0])return json({message:'Este mesmo arquivo já foi anexado ao caso.'},409)}
const path=`${user.id}/disputes/${disputeId}/${crypto.randomUUID()}.${ext(file.name,file.type)}`;uploadedPath=path;await sb(c,`/storage/v1/object/closet-marketplace-private/${path.split('/').map(encodeURIComponent).join('/')}`,c.service,{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:bytes});const evidenceType=file.type==='application/pdf'?'document':file.type.startsWith('video/')?'video':'photo';const evidence=await sb(c,'/rest/v1/rpc/closet_register_dispute_evidence',token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({p_dispute_id:disputeId,p_evidence_type:evidenceType,p_storage_path:path,p_external_url:null,p_content_hash:hash,p_mime_type:file.type||null,p_caption:caption||null})});uploadedPath='';return json({ok:true,evidence})}catch(e){if(uploadedPath)await cleanup(c,uploadedPath);return json({message:e?.message||'Não consegui anexar a evidência.'},500)}}
