'use client';
import {useEffect,useMemo,useState} from 'react';
import {loadClosetItems,restoreClosetSession,type ClosetSession} from '../../supabase';
import {loadTrip,loadTripMoments,loadTripMomentItems,loadTripPacking,setTripPackingState,type Trip,type TripMoment,type TripMomentItem,type TripPackingItem} from '../../travelStore';
import {travelLookThermalStatus} from '../../travelIntelligence';
import {buildSmartPacking,buildTripRadar} from '../../travelPlanner';
import TravelMomentWeather from '../TravelMomentWeather';
import TripRadarCard from './TripRadarCard';
import TripBasicsCard from './TripBasicsCard';
import styles from './trip.module.css';

type ClosetItem={id:string;name:string;category:string;color?:string|null;subcategory?:string|null;image?:string;metadata?:Record<string,any>};
type Tab='route'|'looks'|'packing';
function available(item:ClosetItem|undefined){return Boolean(item)&&(!item!.metadata?.wardrobe_status||item!.metadata?.wardrobe_status==='available')}

export default function TripPage(){
 const [session,setSession]=useState<ClosetSession|null>(null),[trip,setTrip]=useState<Trip|null>(null),[moments,setMoments]=useState<TripMoment[]>([]),[momentItems,setMomentItems]=useState<TripMomentItem[]>([]),[packing,setPacking]=useState<TripPackingItem[]>([]),[closet,setCloset]=useState<ClosetItem[]>([]),[tab,setTab]=useState<Tab>('route'),[expanded,setExpanded]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const tripId=new URLSearchParams(location.search).get('id')||'';(async()=>{if(!tripId)throw new Error('Viagem não identificada.');const s=await restoreClosetSession();setSession(s);if(!s)throw new Error('Entre na sua conta para abrir esta viagem.');const [t,m,mi,p,c]=await Promise.all([loadTrip(s,tripId),loadTripMoments(s,tripId),loadTripMomentItems(s,tripId),loadTripPacking(s,tripId),loadClosetItems(s)]);if(!t)throw new Error('Não encontrei esta viagem.');setTrip(t);setMoments(m);setMomentItems(mi);setPacking(p);setCloset(c as ClosetItem[])})().catch(e=>setError(e?.message||'Não consegui abrir a viagem.')).finally(()=>setLoading(false))},[]);
 const itemMap=useMemo(()=>new Map(closet.map(x=>[String(x.id),x])),[closet]);
 const looks=useMemo(()=>moments.map(m=>{const links=momentItems.filter(x=>x.moment_id===m.id),resolved=links.map(x=>itemMap.get(String(x.item_id))),items=resolved.filter(Boolean) as ClosetItem[],missing=links.length-items.length,unavailable=items.filter(x=>!available(x)),usable=items.filter(x=>available(x)),travel=trip?{thermalPreference:trip.thermal_preference,thermalNeed:m.thermal_need||null,tempMin:m.expected_temp_min??null,tempMax:m.expected_temp_max??null,rainChance:m.rain_probability??null}:{},thermal=trip&&usable.length?travelLookThermalStatus(usable,travel,m,trip):null;return{moment:m,links,items,usable,missing,unavailable,needsReview:missing>0||unavailable.length>0,thermal}}).filter(x=>x.links.length),[moments,momentItems,itemMap,trip]);
 const thermalGaps=useMemo(()=>looks.filter(x=>!x.needsReview&&x.thermal&&x.thermal.tone!=='ok'),[looks]);
 const availabilityReviewIds=useMemo(()=>looks.filter(x=>x.needsReview).map(x=>x.moment.id),[looks]);
 const weatherReviewIds=useMemo(()=>moments.filter(m=>m.metadata?.weather_review_needed).map(m=>m.id),[moments]);
 const reviewIds=useMemo(()=>Array.from(new Set([...weatherReviewIds,...availabilityReviewIds])),[weatherReviewIds,availabilityReviewIds]);
 const smartPacking=useMemo(()=>buildSmartPacking(moments,momentItems,packing,closet.filter(available),trip?.packing_mode||'balanced'),[moments,momentItems,packing,closet,trip?.packing_mode]);
 const radar=useMemo(()=>trip?buildTripRadar(trip,moments,momentItems,packing,thermalGaps.map(x=>x.moment.id),reviewIds):null,[trip,moments,momentItems,packing,thermalGaps,reviewIds]);
 const packedCount=packing.filter(x=>x.packed).length,packedIds=new Set(packing.filter(x=>x.packed).map(x=>String(x.item_id))),coveredLooks=looks.filter(x=>!x.needsReview&&x.items.every(p=>packedIds.has(String(p.id)))).length;
 const marketCategory=thermalGaps.some(x=>x.thermal?.tone==='critical')?'Casacos e jaquetas':'Camadas e agasalhos',marketQuery=thermalGaps.some(x=>x.thermal?.tone==='critical')?'casaco térmico puffer parka segunda pele':'cardigan suéter jaqueta camada';
 async function togglePacked(row:TripPackingItem){if(!session||!trip)return;const next=!row.packed;setPacking(v=>v.map(x=>x.item_id===row.item_id?{...x,packed:next}:x));try{await setTripPackingState(session,trip.id,row.item_id,next)}catch{setPacking(v=>v.map(x=>x.item_id===row.item_id?{...x,packed:!next}:x))}}
 function updateMomentLocal(updated:TripMoment){setMoments(v=>v.map(x=>x.id===updated.id?updated:x))}
 function market(){if(!trip)return;location.href=`/closet/store/?category=${encodeURIComponent(marketCategory)}&q=${encodeURIComponent(marketQuery)}&trip=${encodeURIComponent(trip.id)}${thermalGaps[0]?.moment.id?`&moment=${encodeURIComponent(thermalGaps[0].moment.id)}`:''}`}
 if(loading)return <main className={styles.page}><div className={styles.center}>Abrindo sua viagem…</div></main>;
 if(error||!trip)return <main className={styles.page}><div className={styles.center}><h1>Não consegui abrir.</h1><p>{error}</p><button onClick={()=>location.href='/closet/travel'}>Voltar às viagens</button></div></main>;
 return <main className={styles.page}>
  <header><button onClick={()=>location.href='/closet/travel'}>‹</button><div><span>TRAVEL CLOSET</span><strong>{trip.name}</strong></div><button onClick={()=>location.href='/closet'}>⌂</button></header>
  <section className={styles.hero}><span>{trip.destination.toUpperCase()}</span><h1>{trip.name}</h1><p>{new Date(`${trip.start_date}T12:00:00`).toLocaleDateString('pt-BR')} → {new Date(`${trip.end_date}T12:00:00`).toLocaleDateString('pt-BR')}</p></section>
  <section className={styles.summaryRail}><button onClick={()=>setTab('route')}><span>ROTEIRO</span><strong>{moments.length}</strong><small>momentos</small></button><button onClick={()=>setTab('looks')}><span>LOOKS</span><strong>{looks.filter(x=>!x.needsReview).length}</strong><small>{availabilityReviewIds.length?`${availabilityReviewIds.length} revisar`:'prontos'}</small></button><button onClick={()=>setTab('packing')}><span>MALA</span><strong>{packedCount}/{packing.length}</strong><small>{coveredLooks}/{looks.length} momentos</small></button></section>
  {radar&&<TripRadarCard radar={radar} onTab={setTab} onMarket={market}/>}<nav className={styles.tabs}><button className={tab==='route'?styles.active:''} onClick={()=>setTab('route')}>Roteiro</button><button className={tab==='looks'?styles.active:''} onClick={()=>setTab('looks')}>Looks</button><button className={tab==='packing'?styles.active:''} onClick={()=>setTab('packing')}>Mala</button></nav>
  {tab==='route'&&<section className={styles.route}><div className={styles.routeHead}><div><span>SEUS MOMENTOS</span><h2>Roteiro da viagem</h2></div><button onClick={()=>location.href=`/closet/travel/edit/?id=${trip.id}`}>Editar viagem</button></div>{moments.length?moments.map((m,i)=>{const d=m.starts_at?new Date(m.starts_at):null,look=looks.find(x=>x.moment.id===m.id),ready=Boolean(look&&!look.needsReview);return <article key={m.id}><b>{String(i+1).padStart(2,'0')}</b><div><small>{d?`${d.toLocaleDateString('pt-BR')} · ${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`:'Sem horário definido'}</small><strong>{m.title}</strong><p>{m.location_name||trip.destination}</p>{session&&<TravelMomentWeather session={session} trip={trip} moment={m} onUpdate={updateMomentLocal}/>} {ready&&<em className={styles.ready}>✓ look definido</em>}{look?.needsReview&&<em className={styles.ready}>⚠ look precisa ser adaptado</em>}<div className={styles.actions}><button onClick={()=>location.href=`/closet/travel/look/manual/?trip=${trip.id}&moment=${m.id}`}>Montar manualmente</button><button onClick={()=>location.href=`/closet/travel/look/?trip=${trip.id}&moment=${m.id}`}>✦ {look?.needsReview?'Adaptar com Stylist':ready?'Rever com Stylist':'Stylist sugerir'}</button></div></div></article>}):<div className={styles.empty}>Nenhum momento foi adicionado ainda.</div>}</section>}
  {tab==='looks'&&<section className={styles.looksSection}><div className={styles.sectionTitle}><span>LOOKBOOK DA VIAGEM</span><h2>Seus looks, momento a momento.</h2><p>Previsão, proteção e peças reunidas no mesmo lugar.</p></div>{looks.length?<div className={styles.lookList}>{looks.map(({moment,items,links,thermal,needsReview,unavailable,missing})=>{const open=expanded===moment.id,locked=links.find(x=>x.locked);return <article className={styles.lookCard} key={moment.id}><button className={styles.lookCardMain} onClick={()=>setExpanded(open?null:moment.id)}><div className={styles.lookThumbs}>{items.slice(0,4).map((p,i)=><span key={p.id} style={{zIndex:5-i,opacity:available(p)?1:.42}}><img src={p.image} alt=""/></span>)}</div><div className={styles.lookCopy}><small>{needsReview?'⚠ PEÇA INDISPONÍVEL':moment.metadata?.weather_review_needed?'⚠ PREVISÃO MUDOU':'LOOK SALVO'}</small><strong>{moment.title}</strong><p>{items.length} peças · {moment.location_name||trip.destination}</p>{needsReview&&<em className={`${styles.thermalBadge} ${styles.thermalAttention}`}>! adaptar look</em>}{!needsReview&&thermal&&<em className={`${styles.thermalBadge} ${thermal.tone==='ok'?styles.thermalOk:thermal.tone==='attention'?styles.thermalAttention:styles.thermalCritical}`}>{thermal.tone==='ok'?'✓':'!'} {thermal.label}</em>}</div><b>{open?'−':'+'}</b></button>{open&&<div className={styles.lookDetails}>{needsReview&&<p style={{margin:'0 0 12px',fontSize:12,lineHeight:1.5,color:'#775f50'}}>Este look não está mais pronto para uso. {unavailable.length?`${unavailable.length} peça${unavailable.length>1?'s estão':' está'} fora de uso. `:''}{missing?`${missing} peça${missing>1?'s foram':' foi'} removida do closet.`:''} O Stylist pode substituir apenas o necessário.</p>}<div className={styles.pieceStrip}>{items.map(p=><div key={p.id} className={locked&&String(locked.item_id)===String(p.id)?styles.lockedPiece:''} style={{opacity:available(p)?1:.45}}><img src={p.image} alt={p.name}/><small>{p.name}{!available(p)?' · indisponível':''}</small></div>)}</div><div className={styles.lookActions}><button onClick={()=>location.href=`/closet/travel/look/manual/?trip=${trip.id}&moment=${moment.id}`}>Editar peças</button><button onClick={()=>location.href=`/closet/travel/look/?trip=${trip.id}&moment=${moment.id}`}>✦ {needsReview?'Adaptar look':'Recalcular look'}</button></div></div>}</article>})}</div>:<div className={styles.premiumEmpty}><strong>Seu lookbook ainda está vazio.</strong><button onClick={()=>setTab('route')}>Ir para o roteiro</button></div>}</section>}
  {tab==='packing'&&<section className={styles.packingSection}><div className={styles.sectionTitle}><span>MALA INTELIGENTE</span><h2>{packing.length?`${packedCount} de ${packing.length} peças separadas.`:'A mala nasce dos seus looks.'}</h2><p>{trip.packing_mode==='compact'?'Modo compacto: priorizando peças que resolvem vários momentos.':trip.packing_mode==='variety'?'Modo variedade: mais opções sem perder a coerência da viagem.':'Modo equilibrado: reutilização sem deixar a mala repetitiva.'}</p></div><TripBasicsCard trip={trip}/>{packing.length?<div className={styles.packingProgress}><div><span style={{width:`${Math.round(packedCount/packing.length*100)}%`}}/></div><strong>{Math.round(packedCount/packing.length*100)}% da mala</strong></div>:null}{smartPacking.some(x=>x.uses>1)&&<section className={styles.dependencyCard}><div><span>PEÇAS-CHAVE</span><strong>Estas peças resolvem mais de um momento.</strong><p>Elas aparecem primeiro porque esquecer uma delas afeta vários looks.</p></div><div className={styles.dependencyRail}>{smartPacking.filter(x=>x.uses>1).slice(0,6).map(x=><article key={x.item.id} className={x.packed?styles.dependencyReady:styles.dependencyPending}><img src={x.item.image} alt={x.item.name}/><div><strong>{x.item.name}</strong><small>{x.uses} looks</small><em>{x.packed?'✓ separada':x.reason}</em></div></article>)}</div></section>}{thermalGaps.length>0&&<section className={styles.marketGap}><span>COMPLETAR A MALA</span><strong>{thermalGaps.length} {thermalGaps.length===1?'momento pede':'momentos pedem'} proteção melhor.</strong><p>Primeiro usamos o seu Closet. Como ainda existe uma lacuna real, posso procurar somente o que falta.</p><button onClick={market}>Ver peças recomendadas →</button></section>}{availabilityReviewIds.length>0&&<section className={styles.marketGap}><span>REVISAR ANTES DE FECHAR A MALA</span><strong>{availabilityReviewIds.length} {availabilityReviewIds.length===1?'look mudou porque uma peça saiu de uso.':'looks mudaram porque há peças fora de uso.'}</strong><p>Adapte esses momentos antes de considerar a mala pronta.</p><button onClick={()=>setTab('looks')}>Revisar looks →</button></section>}{packing.length?<div className={styles.packingList}>{smartPacking.map(x=>{const row=packing.find(r=>String(r.item_id)===String(x.item.id));if(!row)return null;return <button key={row.item_id} className={`${styles.packItem} ${row.packed?styles.packDone:''}`} onClick={()=>togglePacked(row)}><span className={styles.check}>{row.packed?'✓':''}</span><img src={x.item.image} alt={x.item.name}/><div><strong>{x.item.name}</strong><small>{[x.item.category,x.item.color].filter(Boolean).join(' · ')}</small>{x.uses>1&&<span className={styles.usageNote}>usada em {x.uses} looks</span>}</div>{row.purchased_for_trip&&<em>nova</em>}</button>})}</div>:<div className={styles.premiumEmpty}><strong>Nada para colocar na mala ainda.</strong><button onClick={()=>setTab('route')}>Planejar looks</button></div>}</section>}
 </main>
}
