'use client'

import { useEffect, useMemo, useState } from 'react'

type Student={id:string;name:string;whatsapp:string;email?:string;modality:string;address?:string;neighborhood?:string;city?:string;day:string;dayOrder:number;time:string;monthlyValue?:string;paymentDay?:string;notes?:string;status:'active'|'inactive'}
type Slot={id:string;day:string;dayOrder:number;time:string;modality:string;status:'available'|'occupied'|'blocked';studentId?:string;studentName?:string;studentWhatsapp?:string}
type Lead={id:string;name:string;whatsapp:string;modality:string;availability:string[];flexible?:boolean;startIntent?:string;status:string}

const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
function wa(phone:string,message:string){const p=phone.startsWith('55')?phone:`55${phone}`;return `https://wa.me/${p}?text=${encodeURIComponent(message)}`}
function maps(student:Student){const q=[student.address,student.neighborhood,student.city].filter(Boolean).join(', ');return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function period(time:string){const h=Number(time.split(':')[0]);return h<12?'Manhã':h<18?'Tarde':'Noite'}
function matchScore(lead:Lead,slot:Slot){if(!(lead.modality==='Tenho interesse nas duas'||lead.modality===slot.modality))return 0;const target=`${slot.day} - ${period(slot.time)}`;const rows=lead.availability||[];const exact=rows.includes(`${target} | ${slot.time}`);const any=rows.includes(`${target} | Qualquer horário`);const legacy=rows.includes(target);let s=exact?88:any?82:legacy?78:rows.some(r=>r.startsWith(slot.day))&&lead.flexible?60:0;if(!s)return 0;if(lead.startIntent==='Imediatamente')s+=12;else if(lead.startIntent==='Nos próximos 30 dias')s+=7;return Math.min(s,100)}

export default function AgendaVisual(){
 const [students,setStudents]=useState<Student[]>([]),[slots,setSlots]=useState<Slot[]>([]),[leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Student|null>(null),[openSlot,setOpenSlot]=useState<Slot|null>(null)
 async function load(){setLoading(true);const [a,b]=await Promise.all([fetch('/api/admin/alunos',{cache:'no-store'}),fetch('/api/admin/aulas',{cache:'no-store'})]);if(a.ok){const d=await a.json();setStudents(d.students||[])}if(b.ok){const d=await b.json();setSlots(d.slots||[]);setLeads(d.leads||[])}setLoading(false)}
 useEffect(()=>{load()},[])
 async function release(student:Student){if(!confirm(`Liberar o horário de ${student.name}?`))return;const r=await fetch('/api/admin/alunos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'release',id:student.id})});if(r.ok){setSelected(null);await load()}}
 const active=useMemo(()=>students.filter(s=>s.status==='active'),[students])
 const free=useMemo(()=>slots.filter(s=>s.status==='available'),[slots])
 const matches=useMemo(()=>openSlot?leads.filter(l=>['waiting','contacted','offered'].includes(l.status)).map(l=>({lead:l,score:matchScore(l,openSlot)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score):[],[openSlot,leads])
 return <main className="av-page">
  <header className="av-top"><div><span>FOCO EM CANTO</span><h1>Agenda de aulas</h1><p>Seus alunos, horários e deslocamentos em uma visão rápida.</p></div><div className="av-top-actions"><a href="/gestao/aulas/alunos">+ Cadastrar aluno</a><a className="ghost" href="/gestao/aulas">Gestão completa</a></div></header>
  <section className="av-shell">
   <div className="av-stats"><div><small>Alunos ativos</small><strong>{active.length}</strong></div><div><small>Vagas disponíveis</small><strong>{free.length}</strong></div><div><small>Interessados</small><strong>{leads.filter(l=>l.status==='waiting').length}</strong></div></div>
   {loading?<div className="av-empty">Carregando agenda...</div>:<div className="av-days">{days.map(day=>{const dayStudents=active.filter(s=>s.day===day).sort((a,b)=>a.time.localeCompare(b.time));const dayFree=free.filter(s=>s.day===day).sort((a,b)=>a.time.localeCompare(b.time));return <section className="av-day" key={day}><div className="av-day-head"><h2>{day}</h2><span>{dayStudents.length} aula{dayStudents.length===1?'':'s'}</span></div><div className="av-events">{dayStudents.map(student=><button className={`av-event ${student.modality==='Presencial'?'presencial':'online'}`} key={student.id} onClick={()=>setSelected(student)}><div className="av-time">{student.time}</div><div className="av-event-main"><strong>{student.name}</strong><span>{student.modality==='Presencial'?`📍 ${[student.neighborhood,student.city].filter(Boolean).join(' • ')||'Local não informado'}`:'💻 Online'}</span>{student.modality==='Presencial'&&student.address?<small>{student.address}</small>:null}</div><div className="av-chevron">›</div></button>)}{dayFree.map(slot=><button className="av-event available" key={slot.id} onClick={()=>setOpenSlot(slot)}><div className="av-time">{slot.time}</div><div className="av-event-main"><strong>Vaga disponível</strong><span>{slot.modality} • ver candidatos compatíveis</span></div><div className="av-chevron">›</div></button>)}{!dayStudents.length&&!dayFree.length?<div className="av-mini-empty">Nenhuma aula ou vaga cadastrada.</div>:null}</div></section>})}</div>}
  </section>
  {selected&&<div className="av-modal-bg" onClick={()=>setSelected(null)}><div className="av-modal" onClick={e=>e.stopPropagation()}><button className="av-close" onClick={()=>setSelected(null)}>×</button><span className="av-kicker">AULA FIXA</span><h2>{selected.name}</h2><div className="av-detail-grid"><div><small>Horário</small><strong>{selected.day} • {selected.time}</strong></div><div><small>Modalidade</small><strong>{selected.modality}</strong></div><div><small>Mensalidade</small><strong>{selected.monthlyValue?`R$ ${selected.monthlyValue}`:'—'}</strong></div><div><small>Pagamento</small><strong>{selected.paymentDay?`Dia ${selected.paymentDay}`:'—'}</strong></div></div>{selected.modality==='Presencial'&&<div className="av-address"><small>ENDEREÇO</small><strong>{selected.address||'Endereço não informado'}</strong><span>{[selected.neighborhood,selected.city].filter(Boolean).join(' • ')}</span></div>}{selected.notes&&<div className="av-notes">{selected.notes}</div>}<div className="av-actions"><a target="_blank" href={wa(selected.whatsapp,`Oi, ${selected.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos.`)}>WhatsApp</a>{selected.modality==='Presencial'&&(selected.address||selected.neighborhood)&&<a target="_blank" href={maps(selected)}>Abrir rota</a>}<a href={`/gestao/aulas/alunos?editar=${selected.id}`}>Editar ficha</a><button onClick={()=>release(selected)}>Liberar vaga</button></div></div></div>}
  {openSlot&&<div className="av-modal-bg" onClick={()=>setOpenSlot(null)}><div className="av-modal" onClick={e=>e.stopPropagation()}><button className="av-close" onClick={()=>setOpenSlot(null)}>×</button><span className="av-kicker">VAGA DISPONÍVEL</span><h2>{openSlot.day} • {openSlot.time}</h2><p className="av-sub">{openSlot.modality} • {matches.length} candidato{matches.length===1?'':'s'} compatível{matches.length===1?'':'eis'}</p><div className="av-match-list">{matches.map(({lead,score})=><article key={lead.id}><div className="av-score">{score}%</div><div><strong>{lead.name}</strong><span>{lead.startIntent||'Início não informado'}</span></div><a target="_blank" href={wa(lead.whatsapp,`Oi, ${lead.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos Cruz 😊 Surgiu uma vaga ${openSlot.modality.toLowerCase()} na ${openSlot.day.toLowerCase()}, às ${openSlot.time}, compatível com a disponibilidade que você informou. Você ainda tem interesse?`)}>Oferecer vaga</a></article>)}{!matches.length?<div className="av-empty">Ainda não há candidatos compatíveis.</div>:null}</div></div></div>}
 </main>
}
