'use client'

import { useEffect, useMemo, useState } from 'react'

type Lead={id:string;createdAt:string;status:string;name:string;whatsapp:string;instagram?:string;source?:string;modality:string;neighborhood?:string;city?:string;availability:string[];flexible?:boolean;level?:string;startIntent?:string;goal?:string;experience?:string}
type Slot={id:string;day:string;dayOrder:number;time:string;modality:string;status:'available'|'occupied'|'blocked';studentName?:string;studentWhatsapp?:string}

const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
const statusLabel:Record<string,string>={waiting:'Na lista',contacted:'Contatado',offered:'Vaga oferecida',enrolled:'Matriculado',inactive:'Inativo'}

function wa(phone:string,message:string){const p=phone.startsWith('55')?phone:`55${phone}`;return `https://wa.me/${p}?text=${encodeURIComponent(message)}`}
function matchScore(lead:Lead,slot:Slot){let s=0;const exact=lead.availability?.some(a=>a.startsWith(slot.day));if(exact)s+=55;if(lead.modality==='Tenho interesse nas duas'||lead.modality===slot.modality)s+=25;if(lead.flexible)s+=8;if(lead.startIntent==='Imediatamente')s+=12;else if(lead.startIntent==='Nos próximos 30 dias')s+=7;return Math.min(s,100)}

export default function AulasManager(){
 const [leads,setLeads]=useState<Lead[]>([]),[slots,setSlots]=useState<Slot[]>([]),[tab,setTab]=useState<'agenda'|'interessados'>('agenda'),[loading,setLoading]=useState(true)
 const [day,setDay]=useState('Segunda'),[time,setTime]=useState('09:00'),[modality,setModality]=useState('Online'),[selectedSlot,setSelectedSlot]=useState<Slot|null>(null)
 async function load(){setLoading(true);const r=await fetch('/api/admin/aulas',{cache:'no-store'});if(r.ok){const d=await r.json();setLeads(d.leads||[]);setSlots(d.slots||[])}setLoading(false)}
 useEffect(()=>{load()},[])
 async function action(payload:any){const r=await fetch('/api/admin/aulas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok)await load();return r.ok}
 async function addSlot(){await action({action:'saveSlot',slot:{day,dayOrder:days.indexOf(day)+1,time,modality,status:'available'}})}
 const stats=useMemo(()=>({waiting:leads.filter(l=>l.status==='waiting').length,students:leads.filter(l=>l.status==='enrolled').length,available:slots.filter(s=>s.status==='available').length}),[leads,slots])
 const matches=useMemo(()=>selectedSlot?leads.filter(l=>['waiting','contacted','offered'].includes(l.status)).map(l=>({lead:l,score:matchScore(l,selectedSlot)})).filter(x=>x.score>=55).sort((a,b)=>b.score-a.score):[],[selectedSlot,leads])
 return <main className="ga-page"><header className="ga-top"><div><span>FOCO EM CANTO</span><h1>Gestão de Aulas</h1></div><a href="/aulasindividuais" target="_blank">Ver página pública ↗</a></header>
 <section className="ga-shell"><div className="ga-stats"><div><small>Alunos ativos</small><strong>{stats.students}</strong></div><div><small>Vagas abertas</small><strong>{stats.available}</strong></div><div><small>Na lista de interesse</small><strong>{stats.waiting}</strong></div></div>
 <nav className="ga-tabs"><button className={tab==='agenda'?'active':''} onClick={()=>setTab('agenda')}>Agenda e vagas</button><button className={tab==='interessados'?'active':''} onClick={()=>setTab('interessados')}>Lista de interesse</button></nav>
 {loading?<div className="ga-empty">Carregando sua gestão...</div>:tab==='agenda'?<>
 <div className="ga-add"><div><strong>Novo horário</strong><span>Cadastre horários que você aceita ocupar com alunos.</span></div><select value={day} onChange={e=>setDay(e.target.value)}>{days.map(d=><option key={d}>{d}</option>)}</select><input type="time" value={time} onChange={e=>setTime(e.target.value)}/><select value={modality} onChange={e=>setModality(e.target.value)}><option>Online</option><option>Presencial</option></select><button onClick={addSlot}>Adicionar</button></div>
 <div className="ga-week">{days.map(d=><section key={d}><h3>{d}</h3><div className="ga-day-list">{slots.filter(s=>s.day===d).map(slot=><article key={slot.id} className={`ga-slot ${slot.status}`}><div><b>{slot.time}</b><span>{slot.modality}</span></div><div><strong>{slot.status==='occupied'?(slot.studentName||'Aluno'):(slot.status==='blocked'?'Bloqueado':'Vaga disponível')}</strong><small>{slot.status==='available'?'Clique para ver candidatos compatíveis':''}</small></div><div className="ga-slot-actions">{slot.status==='available'&&<button onClick={()=>setSelectedSlot(slot)}>Encontrar candidatos</button>}<select value={slot.status} onChange={e=>action({action:'saveSlot',slot:{...slot,status:e.target.value}})}><option value="available">Disponível</option><option value="occupied">Ocupado</option><option value="blocked">Bloqueado</option></select><button className="danger" onClick={()=>action({action:'deleteSlot',id:slot.id})}>×</button></div></article>)}{!slots.some(s=>s.day===d)&&<div className="ga-mini-empty">Nenhum horário cadastrado.</div>}</div></section>)}</div>
 </>:<div className="ga-leads">{leads.map(lead=><article key={lead.id}><div className="ga-lead-main"><div className="ga-avatar">{lead.name.charAt(0).toUpperCase()}</div><div><strong>{lead.name}</strong><span>{lead.modality} • {lead.startIntent||'início não informado'}</span><small>{lead.availability?.join(' • ')}</small></div></div><div className="ga-tags"><span>{lead.goal||'Objetivo não informado'}</span><span>{statusLabel[lead.status]||lead.status}</span></div><div className="ga-lead-actions"><a target="_blank" href={wa(lead.whatsapp,`Oi, ${lead.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊 Você se cadastrou na minha lista de interesse para aulas individuais de canto e estou entrando em contato sobre sua disponibilidade.`)}>WhatsApp</a><select value={lead.status} onChange={e=>action({action:'updateLeadStatus',id:lead.id,status:e.target.value})}>{Object.entries(statusLabel).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div></article>)}{!leads.length&&<div className="ga-empty">Ainda não há cadastros na lista.</div>}</div>}
 </section>
 {selectedSlot&&<div className="ga-modal-backdrop" onClick={()=>setSelectedSlot(null)}><div className="ga-modal" onClick={e=>e.stopPropagation()}><div className="ga-modal-head"><div><span>CANDIDATOS COMPATÍVEIS</span><h2>{selectedSlot.day} • {selectedSlot.time} • {selectedSlot.modality}</h2></div><button onClick={()=>setSelectedSlot(null)}>×</button></div>{matches.length?matches.map(({lead,score})=><article className="ga-match" key={lead.id}><div className="ga-score">{score}%</div><div><strong>{lead.name}</strong><span>{lead.availability.join(' • ')}</span><small>{lead.startIntent||''} {lead.flexible?'• Tem flexibilidade':''}</small></div><a target="_blank" href={wa(lead.whatsapp,`Oi, ${lead.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos Cruz 😊 Você se cadastrou na minha lista de interesse para aulas individuais de canto. Surgiu uma vaga ${selectedSlot.modality.toLowerCase()} na ${selectedSlot.day.toLowerCase()}, às ${selectedSlot.time}, e ela é compatível com a disponibilidade que você informou. Queria saber se ainda tem interesse em começar. Se tiver, me responde por aqui que te passo os próximos passos. 🎤`)} onClick={()=>action({action:'updateLeadStatus',id:lead.id,status:'offered'})}>Oferecer vaga</a></article>):<div className="ga-empty">Nenhum candidato compatível com essa vaga ainda.</div>}</div></div>}
 </main>
}
