'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import styles from './unified-aulas.module.css'

type Lead={id:string;status:string;name?:string;whatsapp?:string;modality?:string;availability?:string[];flexible?:boolean;startIntent?:string;goal?:string}
type Student={id:string;name?:string;whatsapp?:string;email?:string;modality?:string;address?:string;neighborhood?:string;city?:string;day?:string;dayOrder?:number;time?:string;monthlyValue?:string;paymentDay?:string;notes?:string;color?:string;status:'active'|'inactive'}
type Slot={id:string;day:string;dayOrder:number;time:string;modality:string;status:'available'|'occupied'|'blocked';studentId?:string;studentName?:string;studentWhatsapp?:string}
type AgendaItem={kind:'student';time:string;student:Student}|{kind:'slot';time:string;slot:Slot}

const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
const palette=[
 {name:'Roxo',value:'#7427b9'},{name:'Violeta',value:'#4f1b93'},{name:'Azul',value:'#236da0'},{name:'Turquesa',value:'#168c8c'},{name:'Verde',value:'#26784d'},{name:'Oliva',value:'#6d7f2b'},{name:'Dourado',value:'#aa7220'},{name:'Laranja',value:'#b85620'},{name:'Rosa',value:'#ad386f'},{name:'Vinho',value:'#873044'},
]
const emptyStudent={name:'',whatsapp:'',email:'',modality:'Online',address:'',neighborhood:'',city:'Salvador',day:'Segunda',dayOrder:1,time:'09:00',monthlyValue:'',paymentDay:'',notes:'',color:'#7427b9',status:'active' as const}
const emptySlot={day:'Segunda',dayOrder:1,time:'09:00',modality:'Online',status:'available' as const}

function text(value:unknown){return typeof value==='string'?value:''}
function studentName(s:Student){return text(s.name).trim()||'Aluno sem nome'}
function leadName(l:Lead){return text(l.name).trim()||'Interessado'}
function wa(phoneValue:unknown,message:string){const digits=text(phoneValue).replace(/\D/g,'');if(!digits)return '#';const p=digits.startsWith('55')?digits:`55${digits}`;return `https://wa.me/${p}?text=${encodeURIComponent(message)}`}
function maps(s:Student){const q=[text(s.address),text(s.neighborhood),text(s.city)].filter(Boolean).join(', ');return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function period(time:string){const h=Number(time.split(':')[0]||0);return h<12?'Manhã':h<18?'Tarde':'Noite'}
function parsedAvailability(value:string){const [window,detail='']=value.split('|').map(v=>v.trim());return{window,detail}}
function scoreLead(lead:Lead,slot:Slot){const modality=text(lead.modality);const slotAcceptsBoth=slot.modality==='Online ou Presencial';const modalityMatches=slotAcceptsBoth?['Online','Presencial','Tenho interesse nas duas'].includes(modality):(modality==='Tenho interesse nas duas'||modality===slot.modality);if(!modalityMatches)return 0;const target=`${slot.day} - ${period(slot.time)}`;const availability=Array.isArray(lead.availability)?lead.availability:[];const parsed=availability.map(parsedAvailability);const exact=parsed.some(x=>x.window===target&&x.detail===slot.time);const any=parsed.some(x=>x.window===target&&x.detail==='Qualquer horário');const legacy=availability.includes(target);const sameDay=parsed.some(x=>x.window.startsWith(slot.day));let s=exact?75:any?68:legacy?62:(sameDay&&lead.flexible?45:0);if(!s)return 0;if(lead.startIntent==='Imediatamente')s+=15;else if(lead.startIntent==='Nos próximos 30 dias')s+=8;return Math.min(s,100)}
function availabilityText(items?:string[]){return(Array.isArray(items)?items:[]).map(v=>{const p=parsedAvailability(v);return p.detail?`${p.window}: ${p.detail}`:p.window}).join(' • ')}
function statusLabel(status:Slot['status']){return status==='available'?'Disponível':status==='occupied'?'Ocupado':'Bloqueado'}

export default function UnifiedAulasManagerV3(){
 const [tab,setTab]=useState<'agenda'|'alunos'|'interesse'>('agenda')
 const [students,setStudents]=useState<Student[]>([]),[leads,setLeads]=useState<Lead[]>([]),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(true)
 const [editing,setEditing]=useState<Partial<Student>|null>(null),[selectedSlot,setSelectedSlot]=useState<Slot|null>(null),[openingSlot,setOpeningSlot]=useState(false),[newSlot,setNewSlot]=useState({...emptySlot}),[error,setError]=useState('')

 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/admin/aulas',{cache:'no-store'}),fetch('/api/admin/alunos',{cache:'no-store'})]);if(a.ok){const d=await a.json();setLeads(Array.isArray(d.leads)?d.leads:[]);setSlots(Array.isArray(d.slots)?d.slots:[])}if(b.ok){const d=await b.json();setStudents(Array.isArray(d.students)?d.students:[])}}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function studentAction(payload:any){const r=await fetch('/api/admin/alunos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||'Não foi possível salvar.');return false}setError('');await load();return true}
 async function aulasAction(payload:any){const r=await fetch('/api/admin/aulas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||'Não foi possível salvar o horário.');return false}setError('');await load();return true}
 async function saveStudent(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const form=new FormData(e.currentTarget);const day=String(form.get('day')||'Segunda');const student={...editing,...Object.fromEntries(form.entries()),color:editing.color||'#7427b9',dayOrder:days.indexOf(day)+1,status:'active'};if(await studentAction({action:'save',student}))setEditing(null)}
 async function releaseStudent(s:Student){if(confirm(`Liberar o horário de ${studentName(s)}?`))await studentAction({action:'release',id:s.id})}
 async function saveOpenSlot(e:FormEvent<HTMLFormElement>){e.preventDefault();const slot={...newSlot,dayOrder:days.indexOf(newSlot.day)+1};if(await aulasAction({action:'saveSlot',slot})){setOpeningSlot(false);setNewSlot({...emptySlot});setTab('agenda')}}
 async function changeSlotStatus(slot:Slot,status:Slot['status']){await aulasAction({action:'saveSlot',slot:{...slot,status}})}
 async function removeSlot(slot:Slot){if(confirm(`Remover o horário de ${slot.time} da ${slot.day.toLowerCase()}?`))await aulasAction({action:'deleteSlot',id:slot.id})}

 const activeStudents=students.filter(s=>s&&s.status==='active')
 const waiting=leads.filter(l=>l&&['waiting','contacted','offered'].includes(text(l.status)))
 const availableSlots=slots.filter(s=>s&&s.status==='available'&&!s.studentId)
 const matches=useMemo(()=>selectedSlot?waiting.map(lead=>({lead,score:scoreLead(lead,selectedSlot)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score):[],[selectedSlot,waiting])

 if(loading)return <main className={styles.page}><div className={styles.loading}>Carregando sua gestão...</div></main>
 return <main className={styles.page}>
  <header className={styles.top}><div><span>FOCO EM CANTO</span><h1>Gestão de Aulas</h1></div><div className={styles.topActions}><a href="/aulasindividuais" target="_blank">Página pública ↗</a><button onClick={()=>setEditing({...emptyStudent})}>+ Cadastrar aluno</button></div></header>
  <div className={styles.shell}>
   <section className={styles.stats}><div><small>Alunos ativos</small><strong>{activeStudents.length}</strong></div><div><small>Vagas abertas</small><strong>{availableSlots.length}</strong></div><div><small>Lista de interesse</small><strong>{waiting.length}</strong></div></section>
   <nav className={styles.tabs}><button className={tab==='agenda'?styles.active:''} onClick={()=>setTab('agenda')}>Agenda</button><button className={tab==='alunos'?styles.active:''} onClick={()=>setTab('alunos')}>Alunos</button><button className={tab==='interesse'?styles.active:''} onClick={()=>setTab('interesse')}>Lista de interesse</button></nav>

   {tab==='agenda'&&<><div className={styles.sectionBar}><div><h2>Agenda semanal</h2><p>Alunos e horários disponíveis organizados em ordem cronológica.</p></div><button onClick={()=>setOpeningSlot(true)}>+ Abrir vaga</button></div><section className={styles.agenda}>{days.map(day=>{
    const dayStudents=activeStudents.filter(s=>text(s.day)===day)
    const manualSlots=slots.filter(s=>s.day===day&&!s.studentId)
    const items:AgendaItem[]=[...dayStudents.map(student=>({kind:'student' as const,time:text(student.time),student})),...manualSlots.map(slot=>({kind:'slot' as const,time:slot.time,slot}))].sort((a,b)=>a.time.localeCompare(b.time))
    const vacancies=manualSlots.filter(s=>s.status==='available').length
    return <article className={styles.day} key={day}><div className={styles.dayHead}><h2>{day}</h2><span>{dayStudents.length} aula{dayStudents.length===1?'':'s'}{vacancies?` • ${vacancies} vaga${vacancies===1?'':'s'}`:''}</span></div><div className={styles.events}>{items.map(item=>item.kind==='student'?<button className={styles.event} style={{background:text(item.student.color)||(text(item.student.modality)==='Presencial'?'#7427b9':'#236da0')}} key={`student-${item.student.id}`} onClick={()=>setEditing({...item.student})}><div className={styles.time}>{text(item.student.time)||'--:--'}</div><div className={styles.eventBody}><strong>{studentName(item.student)}</strong><span>{text(item.student.modality)||'Online'}{text(item.student.modality)==='Presencial'&&text(item.student.neighborhood)?` • ${text(item.student.neighborhood)}`:''}</span>{text(item.student.modality)==='Presencial'&&<small>{[text(item.student.address),text(item.student.city)].filter(Boolean).join(' • ')}</small>}</div><div className={styles.chevron}>›</div></button>:<div key={`slot-${item.slot.id}`} className={`${styles.event} ${item.slot.status==='available'?styles.vacancy:''}`} style={item.slot.status==='occupied'?{background:'#222832'}:item.slot.status==='blocked'?{background:'#181b20',opacity:.68}:undefined}><button type="button" onClick={()=>item.slot.status==='available'&&setSelectedSlot(item.slot)} style={{display:'contents',color:'inherit',border:0,background:'transparent',cursor:item.slot.status==='available'?'pointer':'default'}}><div className={styles.time}>{item.slot.time}</div><div className={styles.eventBody}><strong>{item.slot.status==='available'?'Vaga disponível':item.slot.status==='occupied'?'Horário ocupado':'Horário bloqueado'}</strong><span>{item.slot.modality}</span><small>{item.slot.status==='available'?'Ver candidatos compatíveis':'Status manual do horário'}</small></div></button><div style={{display:'flex',gap:6,alignItems:'center',justifyContent:'flex-end'}}><select aria-label="Status do horário" value={item.slot.status} onChange={e=>changeSlotStatus(item.slot,e.target.value as Slot['status'])} onClick={e=>e.stopPropagation()} style={{height:36,borderRadius:9,border:'1px solid rgba(255,255,255,.12)',background:'#161c23',color:'#fff',padding:'0 8px',fontSize:11,fontWeight:700}}><option value="available">Disponível</option><option value="occupied">Ocupado</option><option value="blocked">Bloqueado</option></select><button type="button" aria-label="Remover horário" onClick={()=>removeSlot(item.slot)} style={{height:36,width:36,borderRadius:9,border:'1px solid rgba(255,255,255,.08)',background:'#31191d',color:'#f0a4ae',fontWeight:900,cursor:'pointer'}}>×</button></div></div>)}{!items.length&&<div className={styles.emptyDay}>Nenhuma aula ou vaga cadastrada.</div>}</div></article>})}</section></>}

   {tab==='alunos'&&<section className={styles.studentList}><div className={styles.sectionBar}><div><h2>Seus alunos</h2><p>Ficha completa, horário fixo e informações para deslocamento.</p></div><button onClick={()=>setEditing({...emptyStudent})}>+ Novo aluno</button></div>{students.filter(Boolean).map((s,index)=>{const name=studentName(s);const phone=text(s.whatsapp);return <article className={styles.studentCard} key={s.id||`student-${index}`}><div className={styles.avatar} style={{background:text(s.color)||'#242c36',color:'#fff'}}>{name.charAt(0).toUpperCase()}</div><div className={styles.studentMain}><strong>{name}</strong><span>{text(s.day)||'Dia não informado'} • {text(s.time)||'--:--'} • {text(s.modality)||'Online'}</span><small>{text(s.modality)==='Presencial'?[text(s.address),text(s.neighborhood),text(s.city)].filter(Boolean).join(', ')||'Endereço não informado':'Aula online'}</small></div><div className={styles.studentMeta}><span>{text(s.monthlyValue)?`R$ ${text(s.monthlyValue)}`:'Valor não informado'}</span><span>{text(s.paymentDay)?`Venc. dia ${text(s.paymentDay)}`:'Sem vencimento'}</span></div><div className={styles.actions}>{phone?<a href={wa(phone,`Oi, ${name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊`)} target="_blank">WhatsApp</a>:null}{text(s.modality)==='Presencial'&&[text(s.address),text(s.neighborhood),text(s.city)].some(Boolean)?<a href={maps(s)} target="_blank">Rota</a>:null}<button onClick={()=>setEditing({...s})}>Editar</button>{s.status==='active'&&<button className={styles.release} onClick={()=>releaseStudent(s)}>Liberar vaga</button>}</div></article>})}{!students.length&&<div className={styles.bigEmpty}>Nenhum aluno cadastrado ainda.</div>}</section>}

   {tab==='interesse'&&<section className={styles.leads}><div className={styles.sectionBar}><div><h2>Lista de interesse</h2><p>Pessoas que solicitaram uma vaga pela página pública.</p></div></div>{leads.filter(Boolean).map((l,index)=>{const name=leadName(l);const phone=text(l.whatsapp);return <article className={styles.leadCard} key={l.id||`lead-${index}`}><div><strong>{name}</strong><span>{text(l.modality)||'Modalidade não informada'} • {l.startIntent||'início não informado'}</span><small>{availabilityText(l.availability)||'Disponibilidade não informada'}</small></div><div className={styles.goal}>{l.goal||'Objetivo não informado'}</div>{phone?<a href={wa(phone,`Oi, ${name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊 Você se cadastrou na minha lista de interesse para aulas individuais de canto.`)} target="_blank">WhatsApp</a>:null}</article>})}{!leads.length&&<div className={styles.bigEmpty}>Ainda não há pessoas na lista de interesse.</div>}</section>}
  </div>

  {editing&&<div className={styles.backdrop} onClick={()=>setEditing(null)}><form className={styles.modal} onSubmit={saveStudent} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>FICHA DO ALUNO</span><h2>{editing.id?'Editar aluno':'Cadastrar aluno'}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className={styles.formGrid}><label>Nome *<input name="name" required defaultValue={text(editing.name)}/></label><label>WhatsApp<input name="whatsapp" defaultValue={text(editing.whatsapp)}/></label><label>E-mail<input name="email" type="email" defaultValue={text(editing.email)}/></label><label>Modalidade<select name="modality" defaultValue={text(editing.modality)||'Online'}><option>Online</option><option>Presencial</option></select></label><label>Dia<select name="day" defaultValue={text(editing.day)||'Segunda'}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Horário *<input name="time" type="time" required defaultValue={text(editing.time)||'09:00'}/></label><label>Mensalidade<input name="monthlyValue" inputMode="decimal" defaultValue={text(editing.monthlyValue)} placeholder="500"/></label><label>Dia do pagamento<input name="paymentDay" inputMode="numeric" defaultValue={text(editing.paymentDay)} placeholder="10"/></label><label className={styles.full}>Endereço<input name="address" defaultValue={text(editing.address)} placeholder="Rua, número, complemento"/></label><label>Bairro<input name="neighborhood" defaultValue={text(editing.neighborhood)}/></label><label>Cidade<input name="city" defaultValue={text(editing.city)||'Salvador'}/></label><div className={styles.full} style={{display:'flex',flexDirection:'column',gap:8}}><span style={{fontSize:12,fontWeight:800,color:'#bec5ce'}}>Cor da faixa na agenda</span><div style={{display:'flex',gap:9,flexWrap:'wrap',padding:'10px 0 4px'}}>{palette.map(item=><button type="button" key={item.value} title={item.name} aria-label={`Usar cor ${item.name}`} onClick={()=>setEditing(current=>current?{...current,color:item.value}:current)} style={{width:34,height:34,borderRadius:999,border:(text(editing.color)||'#7427b9')===item.value?'3px solid #fff':'2px solid rgba(255,255,255,.2)',background:item.value,cursor:'pointer',boxShadow:(text(editing.color)||'#7427b9')===item.value?'0 0 0 3px rgba(255,255,255,.12)':'none'}} />)}</div><small style={{color:'#8993a0'}}>Essa cor será usada sempre para identificar este aluno na agenda.</small></div><label className={styles.full}>Observações<textarea name="notes" rows={4} defaultValue={text(editing.notes)}/></label></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.modalActions}>{editing.id&&editing.status==='active'&&<button type="button" className={styles.release} onClick={()=>releaseStudent(editing as Student)}>Liberar vaga</button>}<button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className={styles.save}>Salvar aluno</button></div></form></div>}

  {openingSlot&&<div className={styles.backdrop} onClick={()=>setOpeningSlot(false)}><form className={styles.modal} onSubmit={saveOpenSlot} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>NOVO HORÁRIO</span><h2>Adicionar horário à agenda</h2></div><button type="button" onClick={()=>setOpeningSlot(false)}>×</button></div><p style={{color:'#8993a0',marginTop:0}}>Cadastre o horário e defina se ele começa disponível, ocupado ou bloqueado.</p><div className={styles.formGrid}><label>Dia<select value={newSlot.day} onChange={e=>setNewSlot(s=>({...s,day:e.target.value,dayOrder:days.indexOf(e.target.value)+1}))}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Horário<input type="time" required value={newSlot.time} onChange={e=>setNewSlot(s=>({...s,time:e.target.value}))}/></label><label>Modalidade<select value={newSlot.modality} onChange={e=>setNewSlot(s=>({...s,modality:e.target.value}))}><option>Online</option><option>Presencial</option><option>Online ou Presencial</option></select></label><label>Status<select value={newSlot.status} onChange={e=>setNewSlot(s=>({...s,status:e.target.value as Slot['status']}))}><option value="available">Disponível</option><option value="occupied">Ocupado</option><option value="blocked">Bloqueado</option></select></label></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.modalActions}><button type="button" onClick={()=>setOpeningSlot(false)}>Cancelar</button><button className={styles.save}>Adicionar horário</button></div></form></div>}

  {selectedSlot&&<div className={styles.backdrop} onClick={()=>setSelectedSlot(null)}><div className={styles.modal} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>VAGA DISPONÍVEL</span><h2>{selectedSlot.day} • {selectedSlot.time} • {selectedSlot.modality}</h2></div><button onClick={()=>setSelectedSlot(null)}>×</button></div><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:16,padding:'12px',background:'#171d24',borderRadius:12}}><span style={{fontSize:12,color:'#9ba4af'}}>Status do horário:</span><select value={selectedSlot.status} onChange={async e=>{const status=e.target.value as Slot['status'];await changeSlotStatus(selectedSlot,status);setSelectedSlot(status==='available'?{...selectedSlot,status}:null)}} style={{height:36,borderRadius:9,border:'1px solid rgba(255,255,255,.12)',background:'#10151b',color:'#fff',padding:'0 9px'}}><option value="available">Disponível</option><option value="occupied">Ocupado</option><option value="blocked">Bloqueado</option></select><button onClick={async()=>{await removeSlot(selectedSlot);setSelectedSlot(null)}} style={{marginLeft:'auto',height:36,borderRadius:9,border:'1px solid rgba(255,255,255,.08)',background:'#31191d',color:'#f0a4ae',padding:'0 11px',fontWeight:800,cursor:'pointer'}}>Remover horário</button></div><div className={styles.matches}>{matches.map(({lead,score})=>{const name=leadName(lead);const phone=text(lead.whatsapp);return <article key={lead.id}><b>{score}%</b><div><strong>{name}</strong><span>{availabilityText(lead.availability)}</span></div>{phone?<a target="_blank" href={wa(phone,`Oi, ${name.split(' ')[0]}! Tudo bem? Aqui é o Marcos Cruz 😊 Surgiu uma vaga ${selectedSlot.modality==='Online ou Presencial'?'online ou presencial':selectedSlot.modality.toLowerCase()} na ${selectedSlot.day.toLowerCase()}, às ${selectedSlot.time}, compatível com sua disponibilidade. Você ainda tem interesse?`)} onClick={()=>aulasAction({action:'updateLeadStatus',id:lead.id,status:'offered'})}>Oferecer vaga</a>:null}</article>})}{!matches.length&&<div className={styles.bigEmpty}>Nenhum candidato compatível ainda.</div>}</div></div></div>}
 </main>
}
