'use client'

import { FormEvent, useEffect, useState } from 'react'
import styles from './unified-aulas.module.css'

type Lead={id:string;status?:string;name?:string;whatsapp?:string;modality?:string;availability?:string[];flexible?:boolean;startIntent?:string;goal?:string}
type Student={id:string;name?:string;whatsapp?:string;email?:string;modality?:string;address?:string;neighborhood?:string;city?:string;day?:string;time?:string;monthlyValue?:string;paymentDay?:string;notes?:string;color?:string;status?:string}
type Slot={id:string;day:string;dayOrder?:number;time:string;modality:string;status:'available'|'occupied'|'blocked';studentId?:string}

type Tab='agenda'|'alunos'|'interesse'
const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
const short=['Seg','Ter','Qua','Qui','Sex','Sáb']
const colors=['#7427b9','#4f1b93','#236da0','#168c8c','#26784d','#6d7f2b','#aa7220','#b85620','#ad386f','#873044']
const blankStudent={name:'',whatsapp:'',email:'',modality:'Online',address:'',neighborhood:'',city:'Salvador',day:'Segunda',time:'09:00',monthlyValue:'',paymentDay:'',notes:'',color:'#7427b9',status:'active'}
const blankSlot={day:'Segunda',time:'09:00',modality:'Online',status:'available' as const}
const t=(v:unknown)=>typeof v==='string'?v:''
const n=(v:unknown)=>t(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()
const turn=(time:string)=>{const h=Number((time||'00:00').split(':')[0]);return h<12?'Manhã':h<18?'Tarde':'Noite'}
const wa=(phone:unknown,msg:string)=>{const d=t(phone).replace(/\D/g,'');if(!d)return '#';return `https://wa.me/${d.startsWith('55')?d:`55${d}`}?text=${encodeURIComponent(msg)}`}
function score(lead:Lead,slot:Slot){const lm=n(lead.modality),sm=n(slot.modality);if(!(sm.includes('online ou presencial')||lm.includes('duas')||lm.includes('ambas')||lm===sm))return 0;const target=n(`${slot.day} - ${turn(slot.time)}`);const av=Array.isArray(lead.availability)?lead.availability:[];let best=0;for(const raw of av.slice(0,40)){const [w='',d='']=String(raw).split('|').map(x=>x.trim());const nw=n(w),nd=n(d);if(nw===target&&nd===n(slot.time))best=Math.max(best,95);else if(nw===target&&nd.includes('qualquer'))best=Math.max(best,88);else if(nw===target)best=Math.max(best,72);else if(nw.startsWith(n(slot.day))&&lead.flexible)best=Math.max(best,55)}if(n(lead.startIntent)==='imediatamente')best=Math.min(100,best+5);return best}
function safeAvailability(value:unknown){if(!Array.isArray(value))return 'Disponibilidade não informada';return value.slice(0,30).map(v=>t(v).slice(0,100)).filter(Boolean).join(' • ')||'Disponibilidade não informada'}

export default function UnifiedAulasManagerV6(){
 const [ready,setReady]=useState(false)
 const [tab,setTab]=useState<Tab>('agenda')
 const [day,setDay]=useState('Segunda')
 const [students,setStudents]=useState<Student[]>([]),[leads,setLeads]=useState<Lead[]>([]),[slots,setSlots]=useState<Slot[]>([])
 const [loading,setLoading]=useState(true),[error,setError]=useState('')
 const [editing,setEditing]=useState<Partial<Student>|null>(null),[opening,setOpening]=useState(false),[newSlot,setNewSlot]=useState({...blankSlot})
 const [selected,setSelected]=useState<Slot|null>(null),[matches,setMatches]=useState<{lead:Lead;score:number}[]>([])

 useEffect(()=>{const p=new URLSearchParams(window.location.search);const raw=p.get('aba');setTab(raw==='alunos'||raw==='interesse'?raw:'agenda');setReady(true)},[])
 useEffect(()=>{if(!ready)return;let cancelled=false;(async()=>{setLoading(true);try{
   if(tab==='agenda'){
    const [a,b]=await Promise.all([fetch('/api/admin/aulas',{cache:'no-store'}),fetch('/api/admin/alunos',{cache:'no-store'})]);
    if(cancelled)return;
    if(a.ok){const d=await a.json();setLeads(Array.isArray(d.leads)?d.leads:[]);setSlots(Array.isArray(d.slots)?d.slots:[])}
    if(b.ok){const d=await b.json();setStudents(Array.isArray(d.students)?d.students:[])}
   }else if(tab==='alunos'){
    const b=await fetch('/api/admin/alunos',{cache:'no-store'});if(cancelled)return;if(b.ok){const d=await b.json();setStudents(Array.isArray(d.students)?d.students:[])}
   }else{
    const a=await fetch('/api/admin/aulas',{cache:'no-store'});if(cancelled)return;if(a.ok){const d=await a.json();setLeads(Array.isArray(d.leads)?d.leads:[]);setSlots([])}
   }
  }finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[ready,tab])

 async function post(url:string,payload:any){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||'Não foi possível salvar.');return false}setError('');return true}
 async function reloadAgenda(){const [a,b]=await Promise.all([fetch('/api/admin/aulas',{cache:'no-store'}),fetch('/api/admin/alunos',{cache:'no-store'})]);if(a.ok){const d=await a.json();setLeads(Array.isArray(d.leads)?d.leads:[]);setSlots(Array.isArray(d.slots)?d.slots:[])}if(b.ok){const d=await b.json();setStudents(Array.isArray(d.students)?d.students:[])}}
 async function reloadStudents(){const b=await fetch('/api/admin/alunos',{cache:'no-store'});if(b.ok){const d=await b.json();setStudents(Array.isArray(d.students)?d.students:[])}}
 async function saveStudent(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget),chosen=String(f.get('day')||'Segunda');const student={...editing,...Object.fromEntries(f.entries()),dayOrder:days.indexOf(chosen)+1,color:editing.color||'#7427b9',status:'active'};if(await post('/api/admin/alunos',{action:'save',student})){setEditing(null);tab==='agenda'?await reloadAgenda():await reloadStudents()}}
 async function releaseStudent(s:Student){if(confirm(`Liberar o horário de ${s.name||'este aluno'}?`)&&await post('/api/admin/alunos',{action:'release',id:s.id})){tab==='agenda'?await reloadAgenda():await reloadStudents()}}
 async function addSlot(e:FormEvent){e.preventDefault();const slot={...newSlot,dayOrder:days.indexOf(newSlot.day)+1};if(await post('/api/admin/aulas',{action:'saveSlot',slot})){setOpening(false);setDay(newSlot.day);setNewSlot({...blankSlot});await reloadAgenda()}}
 async function updateSlot(status:Slot['status']){if(!selected)return;const next={...selected,status};if(await post('/api/admin/aulas',{action:'saveSlot',slot:next})){setSlots(v=>v.map(x=>x.id===next.id?next:x));setSelected(next)}}
 async function removeSlot(){if(!selected||!confirm(`Remover ${selected.day} ${selected.time}?`))return;if(await post('/api/admin/aulas',{action:'deleteSlot',id:selected.id})){setSlots(v=>v.filter(x=>x.id!==selected.id));setSelected(null)}}
 function inspect(slot:Slot){const waiting=leads.filter(l=>['waiting','contacted','offered'].includes(t(l.status)));const ranked=waiting.slice(0,500).map(lead=>({lead,score:score(lead,slot)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);setMatches(ranked);setSelected(slot)}

 if(!ready||loading)return <main className={styles.page}><div className={styles.loading}>Carregando sua gestão...</div></main>
 const active=students.filter(s=>s&&s.status==='active')
 const waiting=leads.filter(l=>l&&['waiting','contacted','offered'].includes(t(l.status)))
 const open=slots.filter(s=>s&&s.status==='available'&&!s.studentId)
 const dayItems=tab==='agenda'?[...active.filter(s=>s.day===day).map(s=>({kind:'student' as const,time:t(s.time),student:s})),...slots.filter(s=>s&&s.day===day&&!s.studentId).map(slot=>({kind:'slot' as const,time:t(slot.time),slot}))].sort((a,b)=>a.time.localeCompare(b.time)):[]

 return <main className={styles.page}>
  <header className={styles.top}><div><span>FOCO EM CANTO</span><h1>Gestão de Aulas</h1></div><div className={styles.topActions}><a href="/aulasindividuais" target="_blank">Página pública ↗</a>{tab!=='interesse'&&<button onClick={()=>setEditing({...blankStudent})}>+ Cadastrar aluno</button>}</div></header>
  <div className={styles.shell}>
   {tab==='agenda'&&<section className={styles.stats}><div><small>Alunos ativos</small><strong>{active.length}</strong></div><div><small>Vagas abertas</small><strong>{open.length}</strong></div><div><small>Lista de interesse</small><strong>{waiting.length}</strong></div></section>}
   <nav className={styles.tabs}><a className={tab==='agenda'?styles.active:''} href="/gestao/aulas?aba=agenda">Agenda</a><a className={tab==='alunos'?styles.active:''} href="/gestao/aulas?aba=alunos">Alunos</a><a className={tab==='interesse'?styles.active:''} href="/gestao/aulas?aba=interesse">Lista de interesse</a></nav>

   {tab==='agenda'&&<><div className={styles.sectionBar}><div><h2>Agenda semanal</h2><p>Um dia por vez para manter a gestão rápida.</p></div><button onClick={()=>{setNewSlot({...blankSlot,day});setOpening(true)}}>+ Abrir vaga</button></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:14}}>{days.map((d,i)=><button key={d} onClick={()=>setDay(d)} style={{padding:'10px 14px',borderRadius:10,border:'1px solid rgba(255,255,255,.1)',background:day===d?'#efcc89':'#12171d',color:day===d?'#17120b':'#aab2bc',fontWeight:800,cursor:'pointer'}}>{short[i]}</button>)}</div><section className={styles.agenda} style={{gridTemplateColumns:'1fr'}}><article className={styles.day}><div className={styles.dayHead}><h2>{day}</h2><span>{dayItems.length} item{dayItems.length===1?'':'s'}</span></div><div className={styles.events}>{dayItems.map(item=>item.kind==='student'?<button key={`s-${item.student.id}`} className={styles.event} style={{background:t(item.student.color)||'#7427b9'}} onClick={()=>setEditing({...item.student})}><div className={styles.time}>{item.time||'--:--'}</div><div className={styles.eventBody}><strong>{t(item.student.name)||'Aluno'}</strong><span>{t(item.student.modality)||'Online'}{item.student.neighborhood?` • ${item.student.neighborhood}`:''}</span><small>{t(item.student.address)}</small></div><div className={styles.chevron}>›</div></button>:<button key={`v-${item.slot.id}`} className={`${styles.event} ${item.slot.status==='available'?styles.vacancy:''}`} style={item.slot.status==='occupied'?{background:'#222832'}:item.slot.status==='blocked'?{background:'#181b20'}:undefined} onClick={()=>inspect(item.slot)}><div className={styles.time}>{item.time}</div><div className={styles.eventBody}><strong>{item.slot.status==='available'?'Vaga disponível':item.slot.status==='occupied'?'Horário ocupado':'Horário bloqueado'}</strong><span>{t(item.slot.modality)}</span><small>Clique para gerenciar</small></div><div className={styles.chevron}>›</div></button>)}{!dayItems.length&&<div className={styles.emptyDay}>Nenhuma aula ou vaga neste dia.</div>}</div></article></section></>}

   {tab==='alunos'&&<section className={styles.studentList}><div className={styles.sectionBar}><div><h2>Seus alunos</h2><p>Cadastros e horários fixos.</p></div><button onClick={()=>setEditing({...blankStudent})}>+ Novo aluno</button></div>{students.slice(0,500).map((s,i)=><article className={styles.studentCard} key={t(s.id)||`student-${i}`}><div className={styles.avatar} style={{background:t(s.color)||'#242c36'}}>{(t(s.name)||'A').charAt(0).toUpperCase()}</div><div className={styles.studentMain}><strong>{t(s.name)||'Aluno'}</strong><span>{t(s.day)||'-'} • {t(s.time)||'--:--'} • {t(s.modality)||'Online'}</span><small>{t(s.modality)==='Presencial'?[t(s.address),t(s.neighborhood),t(s.city)].filter(Boolean).join(', '):'Aula online'}</small></div><div className={styles.studentMeta}><span>{s.monthlyValue?`R$ ${t(s.monthlyValue)}`:'Valor não informado'}</span><span>{s.paymentDay?`Venc. dia ${t(s.paymentDay)}`:'Sem vencimento'}</span></div><div className={styles.actions}>{s.whatsapp&&<a href={wa(s.whatsapp,`Oi, ${(t(s.name)||'').split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊`)} target="_blank">WhatsApp</a>}<button onClick={()=>setEditing({...s})}>Editar</button>{s.status==='active'&&<button className={styles.release} onClick={()=>releaseStudent(s)}>Liberar vaga</button>}</div></article>)}</section>}

   {tab==='interesse'&&<section className={styles.leads}><div className={styles.sectionBar}><div><h2>Lista de interesse</h2><p>{leads.length} cadastro{leads.length===1?'':'s'} recebido{leads.length===1?'':'s'} pela página pública.</p></div></div>{leads.slice(0,500).map((l,i)=>{const name=t(l.name)||'Interessado';return <article className={styles.leadCard} key={t(l.id)||`lead-${i}`}><div><strong>{name}</strong><span>{t(l.modality)||'Modalidade não informada'} • {t(l.startIntent)||'início não informado'}</span><small>{safeAvailability(l.availability)}</small></div><div className={styles.goal}>{t(l.goal)||'Objetivo não informado'}</div>{l.whatsapp&&<a href={wa(l.whatsapp,`Oi, ${name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊`)} target="_blank">WhatsApp</a>}</article>})}{!leads.length&&<div className={styles.bigEmpty}>Ainda não há interessados cadastrados.</div>}</section>}
  </div>

  {editing&&<div className={styles.backdrop} onClick={()=>setEditing(null)}><form className={styles.modal} onSubmit={saveStudent} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>FICHA DO ALUNO</span><h2>{editing.id?'Editar aluno':'Cadastrar aluno'}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className={styles.formGrid}><label>Nome *<input name="name" required defaultValue={t(editing.name)}/></label><label>WhatsApp<input name="whatsapp" defaultValue={t(editing.whatsapp)}/></label><label>E-mail<input name="email" defaultValue={t(editing.email)}/></label><label>Modalidade<select name="modality" defaultValue={t(editing.modality)||'Online'}><option>Online</option><option>Presencial</option></select></label><label>Dia<select name="day" defaultValue={t(editing.day)||'Segunda'}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Horário<input name="time" type="time" required defaultValue={t(editing.time)||'09:00'}/></label><label>Mensalidade<input name="monthlyValue" defaultValue={t(editing.monthlyValue)}/></label><label>Dia do pagamento<input name="paymentDay" defaultValue={t(editing.paymentDay)}/></label><label className={styles.full}>Endereço<input name="address" defaultValue={t(editing.address)}/></label><label>Bairro<input name="neighborhood" defaultValue={t(editing.neighborhood)}/></label><label>Cidade<input name="city" defaultValue={t(editing.city)||'Salvador'}/></label><div className={styles.full}><span>Cor da faixa</span><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:8}}>{colors.map(c=><button type="button" key={c} onClick={()=>setEditing(v=>v?{...v,color:c}:v)} style={{width:30,height:30,borderRadius:99,background:c,border:editing.color===c?'3px solid white':'1px solid #555'}} />)}</div></div><label className={styles.full}>Observações<textarea name="notes" rows={3} defaultValue={t(editing.notes)}/></label></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.modalActions}><button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className={styles.save}>Salvar aluno</button></div></form></div>}
  {opening&&<div className={styles.backdrop} onClick={()=>setOpening(false)}><form className={styles.modal} onSubmit={addSlot} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>NOVO HORÁRIO</span><h2>Abrir vaga</h2></div><button type="button" onClick={()=>setOpening(false)}>×</button></div><div className={styles.formGrid}><label>Dia<select value={newSlot.day} onChange={e=>setNewSlot(v=>({...v,day:e.target.value}))}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Horário<input type="time" value={newSlot.time} onChange={e=>setNewSlot(v=>({...v,time:e.target.value}))}/></label><label>Modalidade<select value={newSlot.modality} onChange={e=>setNewSlot(v=>({...v,modality:e.target.value}))}><option>Online</option><option>Presencial</option><option>Online ou Presencial</option></select></label><label>Status<select value={newSlot.status} onChange={e=>setNewSlot(v=>({...v,status:e.target.value as Slot['status']}))}><option value="available">Disponível</option><option value="occupied">Ocupado</option><option value="blocked">Bloqueado</option></select></label></div><div className={styles.modalActions}><button type="button" onClick={()=>setOpening(false)}>Cancelar</button><button className={styles.save}>Salvar</button></div></form></div>}
  {selected&&<div className={styles.backdrop} onClick={()=>setSelected(null)}><div className={styles.modal} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>HORÁRIO</span><h2>{selected.day} • {selected.time}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><p style={{color:'#9aa3ae'}}>{selected.modality}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}><button onClick={()=>updateSlot('available')}>Disponível</button><button onClick={()=>updateSlot('occupied')}>Ocupado</button><button onClick={()=>updateSlot('blocked')}>Bloqueado</button><button onClick={removeSlot}>Remover</button></div>{selected.status==='available'&&<div className={styles.matches}>{matches.map(({lead,score},i)=>{const name=t(lead.name)||'Interessado';return <article key={t(lead.id)||`match-${i}`}><b>{score}%</b><div><strong>{name}</strong><span>{safeAvailability(lead.availability)}</span></div>{lead.whatsapp&&<a href={wa(lead.whatsapp,`Oi, ${name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊 Surgiu uma vaga na ${selected.day.toLowerCase()}, às ${selected.time}. Você ainda tem interesse?`)} target="_blank">Oferecer vaga</a>}</article>})}{!matches.length&&<div className={styles.bigEmpty}>Nenhum candidato compatível.</div>}</div>}</div></div>}
 </main>
}
