'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import styles from './unified-aulas.module.css'

type Lead={id:string;status:string;name:string;whatsapp:string;modality:string;availability:string[];flexible?:boolean;startIntent?:string;goal?:string}
type Student={id:string;name:string;whatsapp:string;email?:string;modality:string;address?:string;neighborhood?:string;city?:string;day:string;dayOrder:number;time:string;monthlyValue?:string;paymentDay?:string;notes?:string;status:'active'|'inactive'}
type Slot={id:string;day:string;dayOrder:number;time:string;modality:string;status:'available'|'occupied'|'blocked';studentId?:string;studentName?:string;studentWhatsapp?:string}

const days=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
const emptyStudent={name:'',whatsapp:'',email:'',modality:'Online',address:'',neighborhood:'',city:'Salvador',day:'Segunda',dayOrder:1,time:'09:00',monthlyValue:'',paymentDay:'',notes:'',status:'active' as const}

function wa(phone:string,message:string){const digits=phone.replace(/\D/g,'');const p=digits.startsWith('55')?digits:`55${digits}`;return `https://wa.me/${p}?text=${encodeURIComponent(message)}`}
function maps(s:Student){const q=[s.address,s.neighborhood,s.city].filter(Boolean).join(', ');return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function period(time:string){const h=Number(time.split(':')[0]||0);return h<12?'Manhã':h<18?'Tarde':'Noite'}
function parsedAvailability(value:string){const [window,detail='']=value.split('|').map(v=>v.trim());return{window,detail}}
function scoreLead(lead:Lead,slot:Slot){if(!(lead.modality==='Tenho interesse nas duas'||lead.modality===slot.modality))return 0;const target=`${slot.day} - ${period(slot.time)}`;const parsed=(lead.availability||[]).map(parsedAvailability);const exact=parsed.some(x=>x.window===target&&x.detail===slot.time);const any=parsed.some(x=>x.window===target&&x.detail==='Qualquer horário');const legacy=(lead.availability||[]).includes(target);const sameDay=parsed.some(x=>x.window.startsWith(slot.day));let s=exact?75:any?68:legacy?62:(sameDay&&lead.flexible?45:0);if(!s)return 0;if(lead.startIntent==='Imediatamente')s+=15;else if(lead.startIntent==='Nos próximos 30 dias')s+=8;return Math.min(s,100)}
function availabilityText(items:string[]){return(items||[]).map(v=>{const p=parsedAvailability(v);return p.detail?`${p.window}: ${p.detail}`:p.window}).join(' • ')}

export default function UnifiedAulasManager(){
 const [tab,setTab]=useState<'agenda'|'alunos'|'interesse'>('agenda')
 const [students,setStudents]=useState<Student[]>([]),[leads,setLeads]=useState<Lead[]>([]),[slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(true)
 const [editing,setEditing]=useState<Partial<Student>|null>(null),[selectedSlot,setSelectedSlot]=useState<Slot|null>(null),[error,setError]=useState('')

 async function load(){setLoading(true);const [a,b]=await Promise.all([fetch('/api/admin/aulas',{cache:'no-store'}),fetch('/api/admin/alunos',{cache:'no-store'})]);if(a.ok){const d=await a.json();setLeads(d.leads||[]);setSlots(d.slots||[])}if(b.ok){const d=await b.json();setStudents(d.students||[])}setLoading(false)}
 useEffect(()=>{load()},[])
 async function studentAction(payload:any){const r=await fetch('/api/admin/alunos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||'Não foi possível salvar.');return false}setError('');await load();return true}
 async function aulasAction(payload:any){const r=await fetch('/api/admin/aulas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok)await load();return r.ok}
 async function saveStudent(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const form=new FormData(e.currentTarget);const student={...editing,...Object.fromEntries(form.entries()),dayOrder:days.indexOf(String(form.get('day')))+1,status:'active'};if(await studentAction({action:'save',student}))setEditing(null)}
 async function releaseStudent(s:Student){if(confirm(`Liberar o horário de ${s.name}?`))await studentAction({action:'release',id:s.id})}

 const activeStudents=students.filter(s=>s.status==='active')
 const waiting=leads.filter(l=>['waiting','contacted','offered'].includes(l.status))
 const availableSlots=slots.filter(s=>s.status==='available')
 const matches=useMemo(()=>selectedSlot?waiting.map(lead=>({lead,score:scoreLead(lead,selectedSlot)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score):[],[selectedSlot,waiting])

 if(loading)return <main className={styles.page}><div className={styles.loading}>Carregando sua gestão...</div></main>
 return <main className={styles.page}>
  <header className={styles.top}><div><span>FOCO EM CANTO</span><h1>Gestão de Aulas</h1></div><div className={styles.topActions}><a href="/aulasindividuais" target="_blank">Página pública ↗</a><button onClick={()=>setEditing({...emptyStudent})}>+ Cadastrar aluno</button></div></header>
  <div className={styles.shell}>
   <section className={styles.stats}><div><small>Alunos ativos</small><strong>{activeStudents.length}</strong></div><div><small>Vagas abertas</small><strong>{availableSlots.length}</strong></div><div><small>Lista de interesse</small><strong>{waiting.length}</strong></div></section>
   <nav className={styles.tabs}><button className={tab==='agenda'?styles.active:''} onClick={()=>setTab('agenda')}>Agenda</button><button className={tab==='alunos'?styles.active:''} onClick={()=>setTab('alunos')}>Alunos</button><button className={tab==='interesse'?styles.active:''} onClick={()=>setTab('interesse')}>Lista de interesse</button></nav>

   {tab==='agenda'&&<section className={styles.agenda}>{days.map(day=>{const dayStudents=activeStudents.filter(s=>s.day===day).sort((a,b)=>a.time.localeCompare(b.time));const dayVacancies=availableSlots.filter(s=>s.day===day&&!s.studentId).sort((a,b)=>a.time.localeCompare(b.time));return <article className={styles.day} key={day}><div className={styles.dayHead}><h2>{day}</h2><span>{dayStudents.length} aula{dayStudents.length===1?'':'s'}</span></div><div className={styles.events}>{dayStudents.map(s=><button className={`${styles.event} ${s.modality==='Presencial'?styles.presencial:styles.online}`} key={s.id} onClick={()=>setEditing({...s})}><div className={styles.time}>{s.time}</div><div className={styles.eventBody}><strong>{s.name}</strong><span>{s.modality}{s.modality==='Presencial'&&s.neighborhood?` • ${s.neighborhood}`:''}</span>{s.modality==='Presencial'&&<small>{[s.address,s.city].filter(Boolean).join(' • ')}</small>}</div><div className={styles.chevron}>›</div></button>)}{dayVacancies.map(v=><button className={`${styles.event} ${styles.vacancy}`} key={v.id} onClick={()=>setSelectedSlot(v)}><div className={styles.time}>{v.time}</div><div className={styles.eventBody}><strong>Vaga disponível</strong><span>{v.modality}</span><small>Ver candidatos compatíveis</small></div><div className={styles.chevron}>›</div></button>)}{!dayStudents.length&&!dayVacancies.length&&<div className={styles.emptyDay}>Nenhuma aula cadastrada.</div>}</div></article>})}</section>}

   {tab==='alunos'&&<section className={styles.studentList}><div className={styles.sectionBar}><div><h2>Seus alunos</h2><p>Ficha completa, horário fixo e informações para deslocamento.</p></div><button onClick={()=>setEditing({...emptyStudent})}>+ Novo aluno</button></div>{students.map(s=><article className={styles.studentCard} key={s.id}><div className={styles.avatar}>{s.name.charAt(0).toUpperCase()}</div><div className={styles.studentMain}><strong>{s.name}</strong><span>{s.day} • {s.time} • {s.modality}</span><small>{s.modality==='Presencial'?[s.address,s.neighborhood,s.city].filter(Boolean).join(', '):'Aula online'}</small></div><div className={styles.studentMeta}><span>{s.monthlyValue?`R$ ${s.monthlyValue}`:'Valor não informado'}</span><span>{s.paymentDay?`Venc. dia ${s.paymentDay}`:'Sem vencimento'}</span></div><div className={styles.actions}><a href={wa(s.whatsapp,`Oi, ${s.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊`)} target="_blank">WhatsApp</a>{s.modality==='Presencial'&&<a href={maps(s)} target="_blank">Rota</a>}<button onClick={()=>setEditing({...s})}>Editar</button>{s.status==='active'&&<button className={styles.release} onClick={()=>releaseStudent(s)}>Liberar vaga</button>}</div></article>)}{!students.length&&<div className={styles.bigEmpty}>Nenhum aluno cadastrado ainda.</div>}</section>}

   {tab==='interesse'&&<section className={styles.leads}><div className={styles.sectionBar}><div><h2>Lista de interesse</h2><p>Pessoas que solicitaram uma vaga pela página pública.</p></div></div>{leads.map(l=><article className={styles.leadCard} key={l.id}><div><strong>{l.name}</strong><span>{l.modality} • {l.startIntent||'início não informado'}</span><small>{availabilityText(l.availability)}</small></div><div className={styles.goal}>{l.goal||'Objetivo não informado'}</div><a href={wa(l.whatsapp,`Oi, ${l.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos 😊 Você se cadastrou na minha lista de interesse para aulas individuais de canto.`)} target="_blank">WhatsApp</a></article>)}</section>}
  </div>

  {editing&&<div className={styles.backdrop} onClick={()=>setEditing(null)}><form className={styles.modal} onSubmit={saveStudent} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>FICHA DO ALUNO</span><h2>{editing.id?'Editar aluno':'Cadastrar aluno'}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className={styles.formGrid}><label>Nome *<input name="name" required defaultValue={editing.name||''}/></label><label>WhatsApp<input name="whatsapp" defaultValue={editing.whatsapp||''}/></label><label>E-mail<input name="email" type="email" defaultValue={editing.email||''}/></label><label>Modalidade<select name="modality" defaultValue={editing.modality||'Online'}><option>Online</option><option>Presencial</option></select></label><label>Dia<select name="day" defaultValue={editing.day||'Segunda'}>{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Horário *<input name="time" type="time" required defaultValue={editing.time||'09:00'}/></label><label>Mensalidade<input name="monthlyValue" inputMode="decimal" defaultValue={editing.monthlyValue||''} placeholder="500"/></label><label>Dia do pagamento<input name="paymentDay" inputMode="numeric" defaultValue={editing.paymentDay||''} placeholder="10"/></label><label className={styles.full}>Endereço<input name="address" defaultValue={editing.address||''} placeholder="Rua, número, complemento"/></label><label>Bairro<input name="neighborhood" defaultValue={editing.neighborhood||''}/></label><label>Cidade<input name="city" defaultValue={editing.city||'Salvador'}/></label><label className={styles.full}>Observações<textarea name="notes" rows={4} defaultValue={editing.notes||''}/></label></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.modalActions}>{editing.id&&editing.status==='active'&&<button type="button" className={styles.release} onClick={()=>releaseStudent(editing as Student)}>Liberar vaga</button>}<button type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className={styles.save}>Salvar aluno</button></div></form></div>}

  {selectedSlot&&<div className={styles.backdrop} onClick={()=>setSelectedSlot(null)}><div className={styles.modal} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><span>VAGA DISPONÍVEL</span><h2>{selectedSlot.day} • {selectedSlot.time} • {selectedSlot.modality}</h2></div><button onClick={()=>setSelectedSlot(null)}>×</button></div><div className={styles.matches}>{matches.map(({lead,score})=><article key={lead.id}><b>{score}%</b><div><strong>{lead.name}</strong><span>{availabilityText(lead.availability)}</span></div><a target="_blank" href={wa(lead.whatsapp,`Oi, ${lead.name.split(' ')[0]}! Tudo bem? Aqui é o Marcos Cruz 😊 Surgiu uma vaga ${selectedSlot.modality.toLowerCase()} na ${selectedSlot.day.toLowerCase()}, às ${selectedSlot.time}, compatível com sua disponibilidade. Você ainda tem interesse?`)} onClick={()=>aulasAction({action:'updateLeadStatus',id:lead.id,status:'offered'})}>Oferecer vaga</a></article>)}{!matches.length&&<div className={styles.bigEmpty}>Nenhum candidato compatível ainda.</div>}</div></div></div>}
 </main>
}
