import { isAdminAuthenticated } from '../../_lib/admin-auth.js'

const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})
function cfg(env){return{url:String(env.CLOSET_SUPABASE_URL||env.NEXT_PUBLIC_SUPABASE_URL||'').replace(/\/$/,''),key:String(env.CLOSET_SUPABASE_SERVICE_ROLE_KEY||env.SUPABASE_SERVICE_ROLE_KEY||'')}}
async function sb(env,path,init={}){const c=cfg(env);if(!c.url||!c.key)throw Error('Supabase do Closet não configurado.');const r=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,'Content-Type':'application/json',...(init.headers||{})}}),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.error||`Supabase ${r.status}`);return d}
const q=v=>encodeURIComponent(v)
export async function onRequestGet({request,env}){if(!(await isAdminAuthenticated(request,env)))return json({message:'Não autorizado.'},401);try{const [sellerRisk,buyerRisk,payouts,returns,disputes,sellers,orders]=await Promise.all([
 sb(env,'closet_seller_risk_events?select=*&status=eq.open&order=severity.desc,created_at.asc&limit=300'),
 sb(env,'closet_buyer_risk_events?select=*&status=eq.open&order=severity.desc,created_at.asc&limit=300').catch(()=>[]),
 sb(env,'closet_payouts?select=*&status=in.(held,pending,eligible)&order=created_at.asc&limit=300'),
 sb(env,'closet_returns?select=*&status=not.in.(completed,resolved,rejected,cancelled)&order=requested_at.asc&limit=300'),
 sb(env,'closet_disputes?select=*&status=in.(opened,seller_response,negotiating,mediation)&order=seller_response_due_at.asc.nullslast&limit=300'),
 sb(env,'closet_sellers?select=id,display_name,status,risk_status,verification_level&limit=500'),
 sb(env,'closet_orders?select=id,order_number,seller_id,buyer_user_id,status,total_amount,created_at,delivered_at,payout_eligible_at&order=created_at.desc&limit=500')
 ]);return json({ok:true,sellerRisk,buyerRisk,payouts,returns,disputes,sellers,orders,now:new Date().toISOString()})}catch(e){return json({message:e?.message||'Falha na central de risco.'},500)}}
export async function onRequestPatch({request,env}){if(!(await isAdminAuthenticated(request,env)))return json({message:'Não autorizado.'},401);let b={};try{b=await request.json()}catch{return json({message:'Dados inválidos.'},400)}try{const action=String(b.action||'');if(action==='resolve_seller_risk'){const rows=await sb(env,`closet_seller_risk_events?id=eq.${q(b.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:'resolved',resolved_at:new Date().toISOString(),metadata:{resolution_note:String(b.note||'Revisado pelo admin')}})});return json({ok:true,row:rows?.[0]})}if(action==='seller_risk_status'){const status=String(b.status||'');if(!['normal','watch','restricted','payout_hold','suspended','banned'].includes(status))return json({message:'Status de risco inválido.'},422);const sellerStatus=status==='suspended'||status==='banned'?'suspended':status==='restricted'?'restricted':undefined;const payload={risk_status:status,updated_at:new Date().toISOString()};if(sellerStatus)payload.status=sellerStatus;const rows=await sb(env,`closet_sellers?id=eq.${q(b.seller_id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});return json({ok:true,row:rows?.[0]})}if(action==='run_deadlines'){const r=await sb(env,'rpc/closet_advance_marketplace_deadlines',{method:'POST',body:'{}'});return json({ok:true,result:r})}return json({message:'Ação inválida.'},400)}catch(e){return json({message:e?.message||'Falha ao atualizar risco.'},500)}}
